% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{book}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={MATH 135: AMC I},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs}
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{5}
\usepackage{pgf}
\usepackage{pgfplots}

\title{MATH 135: AMC I}
\author{}
\date{\vspace{-2.5em}}

\begin{document}
\maketitle

{
\setcounter{tocdepth}{1}
\tableofcontents
}
\textbf{Macalester College}\\
\textbf{Fall 2021}

\hypertarget{preface}{%
\chapter*{Preface}\label{preface}}
\addcontentsline{toc}{chapter}{Preface}

This is the class handbook for Math 135 AMC I at Macalester College. The content here was made by \href{https://mathbeveridge.github.io}{Andrew Beveridge}
and draws upon:

\begin{itemize}
\tightlist
\item
  Material prepared by \href{https://www.macalester.edu/~kheysse/}{Kristin Heysse}, \href{https://www.loriziegelmeier.com/}{Lori Ziegelmeier} and other faculty in the \href{https://www.macalester.edu/mscs/}{Department of Mathematics, Statistics and Computer Science} at \href{https://www.macalester.edu/}{Macalester College}.
\item
  The open textbook \href{http://www.opentextbookstore.com/details.php?id=14}{Applied Calculus} by Shana Calaway, Dale Hoffman, and David Lippman.
\end{itemize}

%\includegraphics{https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png}

This work is licensed under a \href{https://creativecommons.org/licenses/by-nc-sa/4.0/}{Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License}.

\hypertarget{r-studio-primer}{%
\chapter{R Studio Primer}\label{r-studio-primer}}

In our class, we will be using RStudio, a developing environment commonly used for modeling and statistics. In real world mathematics, you will need to be able to work with data and apply your calculus concepts directly. That's what we'll do in RStudio, as it provides an excellent sandbox for us to play in. R (what RStudio is based on) is the programming language used by professional statisticians, so these skills will be useful no matter what field you go into!

However, just like any programming language, there is a startup cost. The learning curve for RStudio can be pretty steep, particularly if you've never done any coding before. Don't worry, that's where this guide comes in! In here you'll find all sorts of explanation and examples for some of the coding we'll be doing in (and out of) class. I promise, it'll be worth in the end, and you'll be a coding master.

\hypertarget{getting-oriented}{%
\section{Getting Oriented}\label{getting-oriented}}

\hypertarget{first-login}{%
\subsection{First login}\label{first-login}}

You'll get into RStudio via the url \url{https://rstudio.macalester.edu}. It's linked in our Moodle page if you're feeling a little lazy. Your login is your Macalester username and password. You'll be given the following page (with your username in the uppper right corner):

\includegraphics{images/FirstPage.png}

I tend to ignore the projects and just activate a new session by clicking that panel.

\hypertarget{the-rstudio-window}{%
\subsection{The RStudio window}\label{the-rstudio-window}}

Once you've got an active session, you'll be shown the following window. We'll talk about its parts, starting with the four panels you'll see. This picture is from a previous version of RStudio, but everything should work the same!

\includegraphics{images/RStudioWindow.png}

\hypertarget{panels}{%
\subsubsection{Panels}\label{panels}}

\begin{itemize}
\tightlist
\item
  Source: This is where you will edit RMarkdown notebooks, which are described much more in the RMarkdown section.
\item
  Console: This is RStudio's command line. It's a great place to test code and serves as a basic calculator.
\item
  Environment, history: this panel keeps track of your work. The environment tab shows all the variables you have named in the session (including data, functions, and lists) and gives you a preview of them. The history tab tracks the pieces of code you run.
\item
  Everything else: this is where you'll find a lot of stuff, including the files you build and the plots you create of data/functions. It also has the packages list (described in the next subsection) and the help window, which can show you documentation of commands.
\end{itemize}

Now that we know what we're looking at, let's talk specifics. We'll talk a lot more about the source panel in the RMarkdown section.

\hypertarget{specific-functions}{%
\subsubsection{Specific functions}\label{specific-functions}}

\begin{itemize}
\tightlist
\item
  The new document button. This is how you'll make new files in your source window.
\item
  The quit session button. Somtimes it's best to just start over if you can't figure out why something it not working. You'll be kicked back to that first page from the previous section.
\item
  The clean environment button. Use this when you want to clear all you variables, including data sets.
\item
  The files buttons. You'll use these to create, delete, and organize RMarkdown files and data files. See the data section for more information on how to upload data.
\end{itemize}

\hypertarget{command-line-console}{%
\subsubsection{Command Line Console}\label{command-line-console}}

The command line console is the most basic way to run code. It's great for simple calculations and to test out code before you run it. We'll run longer blocks of code in our notebooks. You can try out a few calculations here.

\textbf{Notice!} Once you run a command (by pressing enter) it is gone to history. You don't go back and edit previous lines if you find a mistake. Instead, you run the command again with the fixed piece in a new line. Thankfully, RStudio makes this not so terrible. By pushing the UP button on your keyboard, you can scroll through previous commands that you've used.

\hypertarget{packages}{%
\subsection{Packages}\label{packages}}

RStudio is open source, which means many people write packages to augment what it can do by default. Their work is our gain, and we'll need a few packages to be able to access what we want. In the lower right hand panel click on the packages tab. Then click on the check boxes next to the following packages:

\begin{itemize}
\tightlist
\item
  fetch: this package knows how to load in data files
\item
  mosaic, mosaicCore, mosaicData: these contain the specific built-ins which create and plot functions for us. By checking the box by them, we import their functions into the session. Easy enough.
\item
  mosaicCalc: Some of the function commands from the mosaic family of packages don't interact well with the built in derivative and antiderivative functions in RStudio. mosaicCalc fixes this

  \begin{itemize}
  \tightlist
  \item
    If you don't see mosaicCalc, then you need to download it. Run the following line of code in your console: \texttt{install.packages("mosaicCalc")} Once you do this, make sure that the mosaicCal box is checked in the packages list
  \end{itemize}
\end{itemize}

\hypertarget{rmarkdown}{%
\section{RMarkdown}\label{rmarkdown}}

In AMC1, we'll be working with code a lot: writing it, running it, analyzing it, and commenting on it. We'll also be going back to code we've already used and tweaking it to solve new but related questions. For all of these reasons, we're going to use RMarkdown notebooks. The notebook will run large chunks of code at a time and show the output right next to the code. It's also easier for you to comment on the code you've written and go back to it later.

The best way to get working on this is to upload the template that I've put in the course Moodle page and just start experimenting with what's there. I'm sure you'll get it sorted!

\hypertarget{rstudio-quick-referrence}{%
\chapter{RStudio Quick Referrence}\label{rstudio-quick-referrence}}

\hypertarget{common-functions}{%
\section{Common Functions}\label{common-functions}}

\begin{longtable}[]{@{}lll@{}}
\toprule
\begin{minipage}[b]{0.30\columnwidth}\raggedright
function\strut
\end{minipage} & \begin{minipage}[b]{0.30\columnwidth}\raggedright
R command\strut
\end{minipage} & \begin{minipage}[b]{0.30\columnwidth}\raggedright
comments\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.30\columnwidth}\raggedright
\(x^2\)\strut
\end{minipage} & \begin{minipage}[t]{0.30\columnwidth}\raggedright
\texttt{x\^{}2}\strut
\end{minipage} & \begin{minipage}[t]{0.30\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.30\columnwidth}\raggedright
\(4x^2 -7x + 3\)\strut
\end{minipage} & \begin{minipage}[t]{0.30\columnwidth}\raggedright
\texttt{4*x\^{}2\ -\ 7*x\ +\ 3}\strut
\end{minipage} & \begin{minipage}[t]{0.30\columnwidth}\raggedright
You must \textbf{always} include the \texttt{*} when you multiply\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.30\columnwidth}\raggedright
\(\sqrt{x}\)\strut
\end{minipage} & \begin{minipage}[t]{0.30\columnwidth}\raggedright
\texttt{sqrt(x)} or \texttt{x\^{}(1/2)}\strut
\end{minipage} & \begin{minipage}[t]{0.30\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.30\columnwidth}\raggedright
\(\sqrt[3]{x}\)\strut
\end{minipage} & \begin{minipage}[t]{0.30\columnwidth}\raggedright
\texttt{x\^{}(1/3)}\strut
\end{minipage} & \begin{minipage}[t]{0.30\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.30\columnwidth}\raggedright
\(\sin(x)\)\strut
\end{minipage} & \begin{minipage}[t]{0.30\columnwidth}\raggedright
\texttt{sin(x)}\strut
\end{minipage} & \begin{minipage}[t]{0.30\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.30\columnwidth}\raggedright
\(\cos(x)\)\strut
\end{minipage} & \begin{minipage}[t]{0.30\columnwidth}\raggedright
\texttt{cos(x)}\strut
\end{minipage} & \begin{minipage}[t]{0.30\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.30\columnwidth}\raggedright
\(e^x\)\strut
\end{minipage} & \begin{minipage}[t]{0.30\columnwidth}\raggedright
\texttt{exp(x)}\strut
\end{minipage} & \begin{minipage}[t]{0.30\columnwidth}\raggedright
\texttt{exp} is a \textbf{function} (like \texttt{sin} and \texttt{cos}), so you do NOT need a \texttt{\^{}}\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.30\columnwidth}\raggedright
\(\mbox{ln}(x)\)\strut
\end{minipage} & \begin{minipage}[t]{0.30\columnwidth}\raggedright
\texttt{log(x)}\strut
\end{minipage} & \begin{minipage}[t]{0.30\columnwidth}\raggedright
RStudio uses the natural logarithm as the default\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.30\columnwidth}\raggedright
\(\log(x) = \log_{10}(x)\)\strut
\end{minipage} & \begin{minipage}[t]{0.30\columnwidth}\raggedright
\texttt{log10(x)}\strut
\end{minipage} & \begin{minipage}[t]{0.30\columnwidth}\raggedright
Humans default to ``log base 10.'' RStudio does not!\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.30\columnwidth}\raggedright
\(\log_{b}(x)\)\strut
\end{minipage} & \begin{minipage}[t]{0.30\columnwidth}\raggedright
\texttt{log(x,b)}\strut
\end{minipage} & \begin{minipage}[t]{0.30\columnwidth}\raggedright
You can use any number \(b\) as the base for your logarithm\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\hypertarget{defining-your-own-function}{%
\section{Defining your own function}\label{defining-your-own-function}}

The \texttt{makeFun} command is part of the mosaic package.

\begin{longtable}[]{@{}lll@{}}
\toprule
\begin{minipage}[b]{0.30\columnwidth}\raggedright
desired function\strut
\end{minipage} & \begin{minipage}[b]{0.30\columnwidth}\raggedright
R command\strut
\end{minipage} & \begin{minipage}[b]{0.30\columnwidth}\raggedright
comments\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.30\columnwidth}\raggedright
\(f(x) = x^2 +5x + 6\)\strut
\end{minipage} & \begin{minipage}[t]{0.30\columnwidth}\raggedright
\texttt{f\ =\ makeFun(x\^{}2\ +\ 5*x\ +\ 6\ \textasciitilde{}\ x)}\strut
\end{minipage} & \begin{minipage}[t]{0.30\columnwidth}\raggedright
remember your \texttt{*} signs!\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.30\columnwidth}\raggedright
\(g(x) = \sin^2(x) - \frac{1}{2}\)\strut
\end{minipage} & \begin{minipage}[t]{0.30\columnwidth}\raggedright
\texttt{g\ =\ makeFun(sin(x)\^{}2\ -\ 1/2\ \textasciitilde{}\ x)}\strut
\end{minipage} & \begin{minipage}[t]{0.30\columnwidth}\raggedright
note the placement of \texttt{\^{}2}\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.30\columnwidth}\raggedright
\(P(t) = 5 e^{.25 t}\)\strut
\end{minipage} & \begin{minipage}[t]{0.30\columnwidth}\raggedright
\texttt{P\ =\ makeFun(5\ *\ exp(0.25\ *\ t)\ \textasciitilde{}\ t)}\strut
\end{minipage} & \begin{minipage}[t]{0.30\columnwidth}\raggedright
\texttt{exp} does not need a \texttt{\^{}}\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.30\columnwidth}\raggedright
\(Q(t) = 12.38 (1.041)^t\)\strut
\end{minipage} & \begin{minipage}[t]{0.30\columnwidth}\raggedright
\texttt{Q\ =\ makeFun(12.38\ *\ (1.041)\^{}t\ \textasciitilde{}\ t)}\strut
\end{minipage} & \begin{minipage}[t]{0.30\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

Notes:

\begin{itemize}
\tightlist
\item
  The general syntax is \texttt{makeFun(\ OUTPUT\ \textasciitilde{}\ INPUT\ )} where the OUTPUT is a function of the INPUT.
\item
  You must \textbf{assign this to a variable} so that you can use it later. So your command must \textbf{start with} \texttt{f\ =\ ...} so that you get a function named \texttt{f}.
\item
  The variable (\texttt{x} or \texttt{t}, etc) that appears in the OUTPUT \textbf{must match} the INPUT variable that appears after the tilde \texttt{\textasciitilde{}}. The the command \texttt{makeFun(x\^{}2\ \textasciitilde{}\ t)} won't work because the \texttt{x\^{}2} is not a function of \texttt{t}.
\end{itemize}

\hypertarget{creating-lists-of-data}{%
\section{Creating Lists of Data}\label{creating-lists-of-data}}

Use \texttt{c()} to ``combine'' some values into a list. Assign the list to a variable so that you can use it later.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{my_primes =}\StringTok{ }\KeywordTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{, }\DecValTok{3}\NormalTok{, }\DecValTok{5}\NormalTok{, }\DecValTok{7}\NormalTok{, }\DecValTok{11}\NormalTok{, }\DecValTok{13}\NormalTok{, }\DecValTok{17}\NormalTok{, }\DecValTok{19}\NormalTok{, }\DecValTok{23}\NormalTok{, }\DecValTok{29}\NormalTok{)}
\NormalTok{my_primes}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1]  2  3  5  7 11 13 17 19 23 29
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{my_data =}\StringTok{ }\KeywordTok{c}\NormalTok{(}\DecValTok{5}\NormalTok{, }\DecValTok{-2}\NormalTok{, }\DecValTok{7}\NormalTok{, }\DecValTok{3}\NormalTok{, }\DecValTok{-10}\NormalTok{, }\DecValTok{15}\NormalTok{)}
\NormalTok{my_data}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1]   5  -2   7   3 -10  15
\end{verbatim}

Use \texttt{seq()} to generate a sequential list of values in a specified range. The optional third parameter tells RStudio to increment by that value instead of incrementing by 1.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{my_seq1 =}\StringTok{ }\KeywordTok{seq}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{10}\NormalTok{)}
\NormalTok{my_seq1}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1]  1  2  3  4  5  6  7  8  9 10
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{my_seq2 =}\StringTok{ }\KeywordTok{seq}\NormalTok{(}\DecValTok{5}\NormalTok{, }\DecValTok{6}\NormalTok{, }\FloatTok{0.25}\NormalTok{)}
\NormalTok{my_seq2}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 5.00 5.25 5.50 5.75 6.00
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{my_seq3 =}\StringTok{ }\KeywordTok{seq}\NormalTok{(}\DecValTok{5}\NormalTok{, }\DecValTok{6}\NormalTok{, }\FloatTok{0.1}\NormalTok{)}
\NormalTok{my_seq3}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1] 5.0 5.1 5.2 5.3 5.4 5.5 5.6 5.7 5.8 5.9 6.0
\end{verbatim}

\hypertarget{plotting-data}{%
\section{Plotting Data}\label{plotting-data}}

Use \texttt{plotPoints} to plot a list of \(y\)-axis data versus a list of \(x\)-axis data. Separate these lists with a tilde \texttt{\textasciitilde{}}.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{X =}\StringTok{ }\KeywordTok{seq}\NormalTok{(}\DecValTok{1}\OperatorTok{:}\DecValTok{5}\NormalTok{)}
\NormalTok{Y =}\StringTok{ }\NormalTok{X}\OperatorTok{^}\DecValTok{2}
\KeywordTok{plotPoints}\NormalTok{(Y }\OperatorTok{~}\StringTok{ }\NormalTok{X)}
\end{Highlighting}
\end{Shaded}

\includegraphics{_bookdown_files/math135_handbook_files/figure-latex/unnamed-chunk-28-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{x_data =}\StringTok{ }\KeywordTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{,}\DecValTok{3}\NormalTok{,}\DecValTok{5}\NormalTok{,}\DecValTok{8}\NormalTok{,}\DecValTok{13}\NormalTok{)}
\NormalTok{y_data =}\StringTok{ }\KeywordTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{,}\DecValTok{4}\NormalTok{,}\DecValTok{8}\NormalTok{,}\DecValTok{4}\NormalTok{,}\DecValTok{2}\NormalTok{)}
\KeywordTok{plotPoints}\NormalTok{(y_data }\OperatorTok{~}\StringTok{ }\NormalTok{x_data)}
\end{Highlighting}
\end{Shaded}

\includegraphics{_bookdown_files/math135_handbook_files/figure-latex/unnamed-chunk-29-1.pdf}

\hypertarget{plotting-functions}{%
\section{Plotting Functions}\label{plotting-functions}}

Use \texttt{plotFun} to plot a function.

\begin{itemize}
\tightlist
\item
  As with \texttt{plotPoints}, we use a tilde \texttt{\textasciitilde{}} to separate the output variable (the function) from the input variable.
\item
  The optional \texttt{xlim} argument specifies the domain for the plot.
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plotFun}\NormalTok{(}\KeywordTok{sin}\NormalTok{(x) }\OperatorTok{~}\StringTok{ }\NormalTok{x)}
\end{Highlighting}
\end{Shaded}

\includegraphics{_bookdown_files/math135_handbook_files/figure-latex/unnamed-chunk-30-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plotFun}\NormalTok{(}\KeywordTok{sin}\NormalTok{(x) }\OperatorTok{~}\StringTok{ }\NormalTok{x, }\DataTypeTok{xlim=}\KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{2}\OperatorTok{*}\NormalTok{pi))}
\end{Highlighting}
\end{Shaded}

\includegraphics{_bookdown_files/math135_handbook_files/figure-latex/unnamed-chunk-30-2.pdf}

We can layer one plot on top of another by using the \texttt{add=TRUE} argument.

\begin{itemize}
\tightlist
\item
  You only need to specify the \texttt{xlim} for the \textbf{first plot} because the second one is added to the first.
\item
  It's helpful to change the color for subsequent plots. Use the argument \texttt{col="red"} using any color name you like (RStudio knows a lot of colors!)
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plotFun}\NormalTok{(}\DecValTok{2} \OperatorTok{*}\StringTok{ }\KeywordTok{sin}\NormalTok{(x) }\OperatorTok{~}\StringTok{ }\NormalTok{x, }\DataTypeTok{xlim=}\KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{2}\OperatorTok{*}\NormalTok{pi))}
\end{Highlighting}
\end{Shaded}

\includegraphics{_bookdown_files/math135_handbook_files/figure-latex/unnamed-chunk-31-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plotFun}\NormalTok{(}\KeywordTok{cos}\NormalTok{(}\DecValTok{3}\OperatorTok{*}\NormalTok{x) }\OperatorTok{~}\StringTok{ }\NormalTok{x, }\DataTypeTok{add=}\OtherTok{TRUE}\NormalTok{, }\DataTypeTok{col=}\StringTok{'green'}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{_bookdown_files/math135_handbook_files/figure-latex/unnamed-chunk-31-2.pdf}

We can label the axes using \texttt{xlab} and \texttt{ylab}. When you are layering two plots, you must specify these labels in the first function that you plot!

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plotFun}\NormalTok{(}\DecValTok{2} \OperatorTok{*}\StringTok{ }\KeywordTok{sin}\NormalTok{(x) }\OperatorTok{~}\StringTok{ }\NormalTok{x, }\DataTypeTok{xlim=}\KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{2}\OperatorTok{*}\NormalTok{pi), }\DataTypeTok{xlab=}\StringTok{'time'}\NormalTok{, }\DataTypeTok{ylab=}\StringTok{'displacement'}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{_bookdown_files/math135_handbook_files/figure-latex/unnamed-chunk-32-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plotFun}\NormalTok{(}\KeywordTok{cos}\NormalTok{(}\DecValTok{3}\OperatorTok{*}\NormalTok{x) }\OperatorTok{~}\StringTok{ }\NormalTok{x, }\DataTypeTok{add=}\OtherTok{TRUE}\NormalTok{, }\DataTypeTok{col=}\StringTok{'green'}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{_bookdown_files/math135_handbook_files/figure-latex/unnamed-chunk-32-2.pdf}

The \texttt{plotFun} command takes a whole variety of parameters, here are a few useful ones:

\begin{itemize}
\tightlist
\item
  \texttt{xlim}, \texttt{ylim}: sets the range of your \(x\)-axis. Example: \texttt{xlim=range(1,4),\ ylim=range(3,60)}
\item
  \texttt{col}: sets the color of the function you plot. RStudio will recognize most basic colors, which you will pass as strings. Example: \texttt{col="red"}
\item
  \texttt{add}: you'll use this when you want to add multiple functions to the same plot. We'll see an example of it below.
  Example: \texttt{add=TRUE}
\item
  \texttt{xlab}, \texttt{ylab}: for labeling your axes. You'll pass this as a string as well. Example: \texttt{xlab="time",\ ylab="red=velocity,\ blue=position"}
\end{itemize}

Let's try some of this out. I broke the third line so it would all fit, you don't need to!

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{f=}\KeywordTok{makeFun}\NormalTok{(x}\OperatorTok{^}\DecValTok{3}\OperatorTok{+}\DecValTok{3}\OperatorTok{~}\NormalTok{x)}
\NormalTok{g=}\KeywordTok{makeFun}\NormalTok{(}\DecValTok{3}\OperatorTok{*}\NormalTok{x}\OperatorTok{^}\DecValTok{2}\OperatorTok{~}\NormalTok{x)}
\KeywordTok{plotFun}\NormalTok{(}\KeywordTok{f}\NormalTok{(x)}\OperatorTok{~}\NormalTok{x, }\DataTypeTok{xlim=}\KeywordTok{range}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{4}\NormalTok{), }\DataTypeTok{ylim=}\KeywordTok{range}\NormalTok{(}\DecValTok{3}\NormalTok{,}\DecValTok{60}\NormalTok{), }
        \DataTypeTok{col=}\StringTok{"blue"}\NormalTok{,}\DataTypeTok{xlab=}\StringTok{"time"}\NormalTok{, }\DataTypeTok{ylab=}\StringTok{"red=velocity, blue=position"}\NormalTok{)}
\KeywordTok{plotFun}\NormalTok{(}\KeywordTok{g}\NormalTok{(x)}\OperatorTok{~}\NormalTok{x, }\DataTypeTok{col=}\StringTok{"red"}\NormalTok{, }\DataTypeTok{add=}\OtherTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{_bookdown_files/math135_handbook_files/figure-latex/unnamed-chunk-33-1} \includegraphics{_bookdown_files/math135_handbook_files/figure-latex/unnamed-chunk-33-2} \end{center}

RStudio is a little weird about plots in the RMarkdown in that you might get multiples if you're adding plots together. If you want the chunk to hold all plots until the end, add \texttt{fig.show=\textquotesingle{}hold\textquotesingle{}} into the script braces at the top of the chunk.

\hypertarget{plotting-data-and-functions}{%
\section{Plotting Data and Functions}\label{plotting-data-and-functions}}

We can also combine plots of data and functions using \texttt{add=TRUE}.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{time_data =}\StringTok{ }\KeywordTok{seq}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{50}\NormalTok{, }\DecValTok{10}\NormalTok{)}
\NormalTok{pop_data =}\StringTok{ }\KeywordTok{c}\NormalTok{(}\FloatTok{6.82}\NormalTok{, }\FloatTok{9.63}\NormalTok{, }\FloatTok{14.3}\NormalTok{, }\FloatTok{20.48}\NormalTok{, }\FloatTok{28.94}\NormalTok{, }\FloatTok{42.25}\NormalTok{)}

\KeywordTok{plotPoints}\NormalTok{(pop_data }\OperatorTok{~}\StringTok{ }\NormalTok{time_data, }\DataTypeTok{xlab=}\StringTok{'years since 1950'}\NormalTok{, }\DataTypeTok{ylab=}\StringTok{'population (millions)'}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{_bookdown_files/math135_handbook_files/figure-latex/unnamed-chunk-34-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{P =}\StringTok{ }\KeywordTok{makeFun}\NormalTok{( }\FloatTok{6.82} \OperatorTok{*}\StringTok{ }\NormalTok{(}\FloatTok{1.037}\NormalTok{)}\OperatorTok{^}\NormalTok{t }\OperatorTok{~}\StringTok{ }\NormalTok{t)}

\KeywordTok{plotFun}\NormalTok{(}\KeywordTok{P}\NormalTok{(t) }\OperatorTok{~}\StringTok{ }\NormalTok{t, }\DataTypeTok{add=}\OtherTok{TRUE}\NormalTok{, }\DataTypeTok{col=}\StringTok{'orange'}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{_bookdown_files/math135_handbook_files/figure-latex/unnamed-chunk-34-2.pdf}

\hypertarget{fitting-a-function-to-data}{%
\section{Fitting a Function to Data}\label{fitting-a-function-to-data}}

The \texttt{fitModel} command is part of the mosaic package. Here is how you would fit a linear model to data

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{xdata =}\StringTok{ }\KeywordTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{,}\DecValTok{3}\NormalTok{,}\DecValTok{4}\NormalTok{,}\DecValTok{5}\NormalTok{)}
\NormalTok{ydata =}\StringTok{ }\KeywordTok{c}\NormalTok{(}\FloatTok{5.3}\NormalTok{, }\FloatTok{7.7}\NormalTok{, }\FloatTok{10.1}\NormalTok{, }\FloatTok{11.3}\NormalTok{, }\FloatTok{12.0}\NormalTok{    )}

\KeywordTok{fitModel}\NormalTok{(ydata  }\OperatorTok{~}\StringTok{ }\NormalTok{A}\OperatorTok{*}\StringTok{ }\NormalTok{xdata  }\OperatorTok{+}\StringTok{ }\NormalTok{B)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## function (xdata, ..., transformation = function (x) 
## x) 
## return(transformation(predict(model, newdata = data.frame(xdata = xdata), 
##     ...)))
## <environment: 0x7f826e760e10>
## attr(,"coefficients")
##    A    B 
## 1.70 4.18 
## attr(,"class")
## [1] "nlsfunction" "function"
\end{verbatim}

This output says that the best fitting linear function has slope \(A=1.70\) and \(y\)-intercept \(B=4.18\). So let's create the corresponding linear function and plot it with the data.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{f =}\StringTok{ }\KeywordTok{makeFun}\NormalTok{(}\FloatTok{1.70} \OperatorTok{*}\StringTok{  }\NormalTok{x }\OperatorTok{+}\StringTok{ }\FloatTok{4.18} \OperatorTok{~}\StringTok{ }\NormalTok{x)}

\KeywordTok{plotPoints}\NormalTok{(ydata }\OperatorTok{~}\StringTok{ }\NormalTok{xdata)}
\end{Highlighting}
\end{Shaded}

\includegraphics{_bookdown_files/math135_handbook_files/figure-latex/unnamed-chunk-36-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plotFun}\NormalTok{(}\KeywordTok{f}\NormalTok{(x) }\OperatorTok{~}\StringTok{ }\NormalTok{x,  }\DataTypeTok{add=}\OtherTok{TRUE}\NormalTok{, }\DataTypeTok{col=}\StringTok{'orange'}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{_bookdown_files/math135_handbook_files/figure-latex/unnamed-chunk-36-2.pdf}

\hypertarget{fitting-a-power-function-to-data}{%
\subsection{Fitting a Power Function to Data}\label{fitting-a-power-function-to-data}}

Here are the steps to fit \texttt{xdata} and \texttt{ydata} to a power function \(f(x) = c x^p\).

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Take the log of both \texttt{xdata} and \texttt{ydata}
\item
  Fit a linear function \(y = A x + B\) to the resulting data
\item
  The original constants are \texttt{p\ =\ A} and \texttt{c\ =\ exp(B)}
\end{enumerate}

Here is an example

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{f =}\StringTok{ }\KeywordTok{makeFun}\NormalTok{(}\FloatTok{4.3} \OperatorTok{*}\StringTok{ }\NormalTok{x}\OperatorTok{^}\NormalTok{(}\FloatTok{1.7}\NormalTok{)}\OperatorTok{~}\NormalTok{x)}

\NormalTok{xdata =}\StringTok{ }\KeywordTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DecValTok{3}\NormalTok{, }\DecValTok{5}\NormalTok{, }\DecValTok{7}\NormalTok{, }\DecValTok{9}\NormalTok{)}
\NormalTok{ydata =}\StringTok{ }\KeywordTok{c}\NormalTok{(}\DecValTok{7}\NormalTok{, }\DecValTok{33}\NormalTok{, }\DecValTok{65}\NormalTok{, }\DecValTok{110}\NormalTok{, }\DecValTok{180}\NormalTok{)}

\NormalTok{logxdata =}\StringTok{ }\KeywordTok{log}\NormalTok{(xdata)}
\NormalTok{logydata =}\StringTok{ }\KeywordTok{log}\NormalTok{(ydata)}

\KeywordTok{fitModel}\NormalTok{(logydata }\OperatorTok{~}\StringTok{ }\NormalTok{A }\OperatorTok{*}\StringTok{ }\NormalTok{logxdata }\OperatorTok{+}\StringTok{ }\NormalTok{B)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## function (logxdata, ..., transformation = function (x) 
## x) 
## return(transformation(predict(model, newdata = data.frame(logxdata = logxdata), 
##     ...)))
## <environment: 0x7f8251be5bd0>
## attr(,"coefficients")
##        A        B 
## 1.449432 1.915983 
## attr(,"class")
## [1] "nlsfunction" "function"
\end{verbatim}

This tells us that \(A=1.45\) and \(B=1.92\). We solve for \(c\) and plot the function with the data

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{p =}\StringTok{ }\FloatTok{1.45}
\NormalTok{p}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1.45
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{c =}\StringTok{ }\KeywordTok{exp}\NormalTok{(}\FloatTok{1.92}\NormalTok{)}
\NormalTok{c}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 6.820958
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plotPoints}\NormalTok{(ydata }\OperatorTok{~}\StringTok{ }\NormalTok{xdata)}
\end{Highlighting}
\end{Shaded}

\includegraphics{_bookdown_files/math135_handbook_files/figure-latex/unnamed-chunk-38-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plotFun}\NormalTok{(}\FloatTok{6.82} \OperatorTok{*}\StringTok{ }\NormalTok{x}\OperatorTok{^}\FloatTok{1.45} \OperatorTok{~}\StringTok{ }\NormalTok{x, }\DataTypeTok{add=}\OtherTok{TRUE}\NormalTok{, }\DataTypeTok{col=}\StringTok{'orange'}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{_bookdown_files/math135_handbook_files/figure-latex/unnamed-chunk-38-2.pdf}

\hypertarget{fitting-a-model-by-specifying-starting-values}{%
\subsection{Fitting a Model by Specifying Starting Values}\label{fitting-a-model-by-specifying-starting-values}}

Sometimes \texttt{fitModel} fails to find a good model for the data. Here are two things that can happen.

\begin{itemize}
\tightlist
\item
  The command \texttt{fitModel} fails, 7.complaining about a ``singular gradient.'' This means that \texttt{fitModel} picked a bad starting point, and can't figure out how to improve it's initial guess.
\item
  The command \texttt{fitModel} does find a function, but when we plot it, we realize that it's not what we want.
\end{itemize}

Here is an example of \texttt{fitModel} returning a function that we don't like. Let's load in the `utilities.csv' data set and look at the first few rows.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{utilitydata =}\StringTok{ }\NormalTok{fetch}\OperatorTok{::}\KeywordTok{fetchData}\NormalTok{(}\StringTok{"utilities.csv"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Retrieving from http://www.mosaic-web.org/go/datasets/utilities.csv
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{head}\NormalTok{(utilitydata)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   month day year temp  kwh ccf thermsPerDay dur totalbill gasbill
## 1     2  24 2005   29  557 166          6.0  28    213.71  166.63
## 2     3  29 2005   31  772 179          5.5  33    239.85  117.05
## 3     1  27 2005   15  891 224          7.5  30    294.96  223.92
## 4    11  23 2004   43  860  82          2.8  29    160.26   88.51
## 5    12  28 2004   23 1160 208          6.0  35    317.47  224.18
## 6     9  26 2004   71  922  15          0.5  32    117.46   21.25
##   elecbill notes
## 1    47.08      
## 2    62.80      
## 3    71.04      
## 4    71.75      
## 5    93.29      
## 6    96.21
\end{verbatim}

Now let's plot temperature versus month

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plotPoints}\NormalTok{(temp }\OperatorTok{~}\StringTok{ }\NormalTok{month, }\DataTypeTok{data=}\NormalTok{utilitydata)}
\end{Highlighting}
\end{Shaded}

\includegraphics{_bookdown_files/math135_handbook_files/figure-latex/unnamed-chunk-40-1.pdf}

We have ploted monthly temperature data for multiple years. Let's try to fit a periodic function.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{M =}\StringTok{ }\KeywordTok{fitModel}\NormalTok{(temp }\OperatorTok{~}\StringTok{ }\NormalTok{A }\OperatorTok{*}\StringTok{ }\KeywordTok{sin}\NormalTok{(w}\OperatorTok{*}\NormalTok{(month }\OperatorTok{+}\StringTok{ }\NormalTok{p))}\OperatorTok{+}\NormalTok{C, }\DataTypeTok{data=}\NormalTok{utilitydata)}
\KeywordTok{coef}\NormalTok{(M)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##         A         w         p         C 
## -28.67993  -6.78753  56.15894  47.20908
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{f =}\StringTok{ }\KeywordTok{makeFun}\NormalTok{(}\OperatorTok{-}\FloatTok{28.7} \OperatorTok{*}\StringTok{ }\KeywordTok{sin}\NormalTok{(}\OperatorTok{-}\FloatTok{6.8}\OperatorTok{*}\NormalTok{(t }\OperatorTok{+}\StringTok{ }\FloatTok{56.2}\NormalTok{))}\OperatorTok{+}\FloatTok{47.2} \OperatorTok{~}\StringTok{ }\NormalTok{t)}
\KeywordTok{plotFun}\NormalTok{(}\KeywordTok{f}\NormalTok{(t)}\OperatorTok{~}\NormalTok{t, }\DataTypeTok{add=}\OtherTok{TRUE}\NormalTok{, }\DataTypeTok{col=}\StringTok{'red'}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{_bookdown_files/math135_handbook_files/figure-latex/unnamed-chunk-41-1.pdf}

This is not what we wanted! It looks like \texttt{fitModel} was confused by the multiple data points for each month. So the frequency \texttt{w} is completely wrong. We can correct this by specifying an initial guess for \texttt{w}. We think that the period should be 12 months, so we want to start with \texttt{w=2*pi/12}.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{M =}\StringTok{ }\KeywordTok{fitModel}\NormalTok{(temp }\OperatorTok{~}\StringTok{ }\NormalTok{A }\OperatorTok{*}\StringTok{ }\KeywordTok{sin}\NormalTok{(w}\OperatorTok{*}\NormalTok{(month }\OperatorTok{+}\StringTok{ }\NormalTok{p))}\OperatorTok{+}\NormalTok{C, }\DataTypeTok{data=}\NormalTok{utilitydata, }\DataTypeTok{start=}\KeywordTok{list}\NormalTok{(}\DataTypeTok{w=}\DecValTok{2}\OperatorTok{*}\NormalTok{pi}\OperatorTok{/}\DecValTok{12}\NormalTok{))}
\KeywordTok{coef}\NormalTok{(M)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##           w           A           p           C 
##   0.5043435 -28.6799747 -22.8387987  47.2090049
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{f =}\StringTok{ }\KeywordTok{makeFun}\NormalTok{(}\OperatorTok{-}\FloatTok{28.7} \OperatorTok{*}\StringTok{ }\KeywordTok{sin}\NormalTok{(}\FloatTok{0.5}\OperatorTok{*}\NormalTok{(t }\FloatTok{-22.8}\NormalTok{))}\OperatorTok{+}\FloatTok{47.2} \OperatorTok{~}\StringTok{ }\NormalTok{t)}
\KeywordTok{plotFun}\NormalTok{(}\KeywordTok{f}\NormalTok{(t)}\OperatorTok{~}\NormalTok{t, }\DataTypeTok{add=}\OtherTok{TRUE}\NormalTok{, }\DataTypeTok{col=}\StringTok{'orange'}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{_bookdown_files/math135_handbook_files/figure-latex/unnamed-chunk-42-1.pdf}

That looks much better!

\hypertarget{plotting-surfaces-in-3d}{%
\section{Plotting Surfaces in 3D}\label{plotting-surfaces-in-3d}}

We plot functions \(z = f(x,y)\) using the \texttt{plotFun()} command. We specify the independent variables with the syntax \texttt{\textasciitilde{}\ x\&y}. By default, RStudio will create a \textbf{contour plot} of this function and include \textbf{shading} to help visualize the values of the function.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{f =}\StringTok{ }\KeywordTok{makeFun}\NormalTok{(x}\OperatorTok{^}\DecValTok{2} \OperatorTok{-}\StringTok{ }\NormalTok{y}\OperatorTok{^}\DecValTok{2} \OperatorTok{~}\StringTok{ }\NormalTok{x}\OperatorTok{&}\NormalTok{y)}

\KeywordTok{plotFun}\NormalTok{(}\KeywordTok{f}\NormalTok{(x,y) }\OperatorTok{~}\StringTok{ }\NormalTok{x}\OperatorTok{&}\NormalTok{y)}
\end{Highlighting}
\end{Shaded}

\includegraphics{_bookdown_files/math135_handbook_files/figure-latex/unnamed-chunk-43-1.pdf}

You can add more contours using the \texttt{levels} parameter, and turn off the shading with the \texttt{filled} parameter.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plotFun}\NormalTok{(}\KeywordTok{f}\NormalTok{(x,y) }\OperatorTok{~}\StringTok{ }\NormalTok{x}\OperatorTok{&}\NormalTok{y, }\DataTypeTok{levels =} \KeywordTok{seq}\NormalTok{(}\OperatorTok{-}\DecValTok{1}\NormalTok{ ,}\DecValTok{1}\NormalTok{, }\FloatTok{.2}\NormalTok{), }\DataTypeTok{filled =} \OtherTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{_bookdown_files/math135_handbook_files/figure-latex/unnamed-chunk-44-1.pdf}

You can change the plot range using \texttt{xlim} and \texttt{ylim}.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plotFun}\NormalTok{(}\KeywordTok{f}\NormalTok{(x,y) }\OperatorTok{~}\StringTok{ }\NormalTok{x}\OperatorTok{&}\NormalTok{y, }\DataTypeTok{xlim=}\KeywordTok{c}\NormalTok{(}\OperatorTok{-}\DecValTok{20}\NormalTok{,}\DecValTok{20}\NormalTok{), }\DataTypeTok{ylim=}\KeywordTok{c}\NormalTok{(}\OperatorTok{-}\DecValTok{20}\NormalTok{,}\DecValTok{20}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{_bookdown_files/math135_handbook_files/figure-latex/unnamed-chunk-45-1.pdf}

You can create a 3D plot by setting \texttt{surface=TRUE}.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plotFun}\NormalTok{(}\KeywordTok{f}\NormalTok{(x,y) }\OperatorTok{~}\StringTok{ }\NormalTok{x}\OperatorTok{&}\NormalTok{y, }\DataTypeTok{xlim=}\KeywordTok{c}\NormalTok{(}\OperatorTok{-}\DecValTok{20}\NormalTok{,}\DecValTok{20}\NormalTok{), }\DataTypeTok{ylim=}\KeywordTok{c}\NormalTok{(}\OperatorTok{-}\DecValTok{20}\NormalTok{,}\DecValTok{20}\NormalTok{), }\DataTypeTok{surface=}\OtherTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{_bookdown_files/math135_handbook_files/figure-latex/unnamed-chunk-46-1.pdf}

\hypertarget{estimating-the-derivative}{%
\section{Estimating the Derivative}\label{estimating-the-derivative}}

We can estimate the derivative of \(f'(x)\) by using the average rate of change
\[
f'(x) \approx\frac{f(x+\alpha)-f(x)}{\alpha}
\]
for some small number \(\alpha > 0\). Smaller and smaller \(\alpha\)'s lead to better and better approximations.

So we can estimate the derivative by using smaller and smaller \(\alpha\) values until our estimates stabilize. Here is an example that estimates \(f'(4)\) for the function \(f(x) = x^2 + 10*\sin(x)\).

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{f=}\KeywordTok{makeFun}\NormalTok{(x}\OperatorTok{^}\DecValTok{2}\OperatorTok{+}\DecValTok{10}\OperatorTok{*}\KeywordTok{sin}\NormalTok{(x)}\OperatorTok{~}\NormalTok{x)}
\NormalTok{alpha=}\KeywordTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{, }\FloatTok{0.1}\NormalTok{, }\FloatTok{0.01}\NormalTok{, }\FloatTok{0.001}\NormalTok{, }\FloatTok{0.0001}\NormalTok{, }\FloatTok{0.00001}\NormalTok{, }\FloatTok{0.000001}\NormalTok{, }\FloatTok{0.0000001}\NormalTok{)}
\NormalTok{d=(}\KeywordTok{f}\NormalTok{(}\DecValTok{4}\OperatorTok{+}\NormalTok{alpha)}\OperatorTok{-}\KeywordTok{f}\NormalTok{(}\DecValTok{4}\NormalTok{))}\OperatorTok{/}\NormalTok{alpha}
\NormalTok{d}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 6.978782 1.952538 1.511513 1.468349 1.464042 1.463612 1.463569
## [8] 1.463564
\end{verbatim}

The estimates stabilize to the value \(1.46356\). So our estimate is \(f'(4) \approx 1.46456\)

We can use the same method to estimate the partial derivates of \(g(x,y)\). We have
\[
\frac{\partial g}{\partial x} \approx\frac{g(x+\alpha,y)-f(x,y)}{\alpha} 
\quad \mbox{and} \quad
\frac{\partial g}{\partial y} \approx\frac{g(x,y+\alpha)-f(x,y)}{\alpha}
\]
Let's estimate the partial derivatives of \(g(x,y) = e^{x \sin(y)}\) at the point \((2, 7)\). First, let's estimate \(g_x(2,7) = \left. \frac{\partial g}{\partial x} \right|_{(2,7)}\). The code is very similar to the code we used for a single variable function.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{g=}\KeywordTok{makeFun}\NormalTok{(}\KeywordTok{exp}\NormalTok{(x}\OperatorTok{*}\KeywordTok{sin}\NormalTok{(y))}\OperatorTok{~}\NormalTok{x}\OperatorTok{&}\NormalTok{y)}
\NormalTok{alpha=}\KeywordTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{, }\FloatTok{0.1}\NormalTok{, }\FloatTok{0.01}\NormalTok{, }\FloatTok{0.001}\NormalTok{, }\FloatTok{0.0001}\NormalTok{, }\FloatTok{0.00001}\NormalTok{, }\FloatTok{0.000001}\NormalTok{, }\FloatTok{0.0000001}\NormalTok{)}
\NormalTok{d=(}\KeywordTok{g}\NormalTok{(}\DecValTok{2}\OperatorTok{+}\NormalTok{alpha,}\DecValTok{7}\NormalTok{)}\OperatorTok{-}\KeywordTok{g}\NormalTok{(}\DecValTok{2}\NormalTok{,}\DecValTok{7}\NormalTok{))}\OperatorTok{/}\NormalTok{alpha}
\NormalTok{d}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 3.456634 2.526691 2.452648 2.445403 2.444680 2.444608 2.444601
## [8] 2.444600
\end{verbatim}

We conclude that \(g_x(2,7) \approx 2.445.\)

Now let's estimate \(g_y(2,7) = \left. \frac{\partial g}{\partial y} \right|_{(2,7)}\). All we need to do is move \texttt{alpha} into the \(y\)-variable.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{g=}\KeywordTok{makeFun}\NormalTok{(}\KeywordTok{exp}\NormalTok{(x}\OperatorTok{*}\KeywordTok{sin}\NormalTok{(y))}\OperatorTok{~}\NormalTok{x}\OperatorTok{&}\NormalTok{y)}
\NormalTok{alpha=}\KeywordTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{, }\FloatTok{0.1}\NormalTok{, }\FloatTok{0.01}\NormalTok{, }\FloatTok{0.001}\NormalTok{, }\FloatTok{0.0001}\NormalTok{, }\FloatTok{0.00001}\NormalTok{, }\FloatTok{0.000001}\NormalTok{, }\FloatTok{0.0000001}\NormalTok{)}
\NormalTok{d=(}\KeywordTok{g}\NormalTok{(}\DecValTok{2}\NormalTok{,}\DecValTok{7}\OperatorTok{+}\NormalTok{alpha)}\OperatorTok{-}\KeywordTok{g}\NormalTok{(}\DecValTok{2}\NormalTok{,}\DecValTok{7}\NormalTok{))}\OperatorTok{/}\NormalTok{alpha}
\NormalTok{d}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 3.512524 5.761618 5.628032 5.612215 5.610611 5.610450 5.610434
## [8] 5.610433
\end{verbatim}

We conclude that \(g_y(2,7) \approx 5.610.\)

\hypertarget{gradient-search}{%
\section{Gradient Search}\label{gradient-search}}

Here is code that will use gradient search to find the maximum of the function
\[
f(x,y) = - x^4 -  x^3 + 10 x y + 2y - 8 y^2 
\]
whose partial derivatives are
\[
\frac{\partial f}{\partial x} = -4 x^3 -3 x^2  + 10 y
\quad \mbox{and} \quad
\frac{\partial f}{\partial x} = 10 x + 2 - 16 y
\]

First, you define the partial derivatives and then choose your starting point \texttt{(newx,\ newy)}. In this case, we start at \texttt{(1,1)}.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{partialx=}\KeywordTok{makeFun}\NormalTok{( }\DecValTok{-4}\OperatorTok{*}\NormalTok{x}\OperatorTok{^}\DecValTok{3} \DecValTok{-3}\OperatorTok{*}\NormalTok{x}\OperatorTok{^}\DecValTok{2} \OperatorTok{+}\StringTok{ }\DecValTok{10}\OperatorTok{*}\NormalTok{y}\OperatorTok{~}\NormalTok{x}\OperatorTok{&}\NormalTok{y)}
\NormalTok{partialy=}\KeywordTok{makeFun}\NormalTok{(}\DecValTok{10}\OperatorTok{*}\NormalTok{x }\OperatorTok{+}\StringTok{ }\DecValTok{2} \OperatorTok{-}\StringTok{ }\DecValTok{16}\OperatorTok{*}\NormalTok{y}\OperatorTok{~}\NormalTok{x}\OperatorTok{&}\NormalTok{y)}
\NormalTok{newx =}\StringTok{ }\DecValTok{1}
\NormalTok{newy =}\StringTok{ }\DecValTok{1}
\end{Highlighting}
\end{Shaded}

Next, you repeatedly run the following code block, which updates the current point by moving \texttt{0.1} times the gradient vector. This is equivilant to taking a small step in the uphill direction.

Repeatedly to run this code block until the partial derivatives are essentially zero (at least two zeros after the decimal point). Congrats! You have found your local maximum.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{newx=newx}\FloatTok{+0.1}\OperatorTok{*}\KeywordTok{partialx}\NormalTok{(newx,newy)}
\NormalTok{newy=newy}\FloatTok{+0.1}\OperatorTok{*}\KeywordTok{partialy}\NormalTok{(newx,newy)}
\CommentTok{# print new partial derivatives}
\KeywordTok{c}\NormalTok{(}\KeywordTok{partialx}\NormalTok{(newx,newy), }\KeywordTok{partialy}\NormalTok{(newx,newy))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] -4.858  0.600
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# print new point}
\KeywordTok{c}\NormalTok{(newx, newy)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1.3 0.9
\end{verbatim}

Repeatedly running this code block will take you to the point \texttt{(1.04,0.77)}. But note that starting at another initial point might take you to a different local maximum.

If you want to find a local minimum, then you should multiply the partials by \texttt{-0.1} instead. This is equivalent to taking a small step downhill. Try this on the function \(f(x,y) = x^2 + 2 x y + 3 x + 4 y + 5 y^2\).

\hypertarget{constrained-optimization}{%
\section{Constrained Optimization}\label{constrained-optimization}}

Suppose that we want to find the maximum of the production function \(P(x,y)=3000x^{0.2}y^{0.8}\) given the constraint \(Q(x,y)= 4x + 3y = 200\).

We want to make a contour plot of \(P(x,y)\) and then add the constraint. The maximum value is achieved where the constraint \(Q(x,y)=300\) is tangent to the contour curve of \(P(x,y)\).

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{P =}\StringTok{ }\KeywordTok{makeFun}\NormalTok{( x}\OperatorTok{^}\NormalTok{(}\FloatTok{0.2}\NormalTok{) }\OperatorTok{*}\StringTok{ }\NormalTok{y}\OperatorTok{^}\NormalTok{(}\FloatTok{0.8}\NormalTok{) }\OperatorTok{~}\StringTok{ }\NormalTok{x}\OperatorTok{&}\NormalTok{y)}
\NormalTok{Q =}\StringTok{ }\KeywordTok{makeFun}\NormalTok{( }\DecValTok{4}\OperatorTok{*}\NormalTok{x }\OperatorTok{+}\StringTok{ }\DecValTok{3}\OperatorTok{*}\NormalTok{y }\OperatorTok{~}\StringTok{ }\NormalTok{x}\OperatorTok{&}\NormalTok{y)}

\KeywordTok{plotFun}\NormalTok{(}\KeywordTok{P}\NormalTok{(x,y)}\OperatorTok{~}\NormalTok{x}\OperatorTok{&}\NormalTok{y, }\DataTypeTok{xlim=}\KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{80}\NormalTok{), }\DataTypeTok{ylim=}\KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{80}\NormalTok{), }\DataTypeTok{filled=}\OtherTok{FALSE}\NormalTok{, }\DataTypeTok{levels=}\KeywordTok{seq}\NormalTok{(}\DecValTok{20}\NormalTok{,}\DecValTok{80}\NormalTok{,}\DecValTok{5}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{_bookdown_files/math135_handbook_files/figure-latex/unnamed-chunk-53-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plotFun}\NormalTok{(}\KeywordTok{Q}\NormalTok{(x,y)}\OperatorTok{~}\NormalTok{x}\OperatorTok{&}\NormalTok{y, }\DataTypeTok{add=}\OtherTok{TRUE}\NormalTok{, }\DataTypeTok{filled=}\OtherTok{FALSE}\NormalTok{, }\DataTypeTok{levels=}\DecValTok{200}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{_bookdown_files/math135_handbook_files/figure-latex/unnamed-chunk-53-2.pdf}

In this case, the optimal value of \(38\) is achieved at approximately \((10, 55)\). Let's make another plot to get a better estimate.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plotFun}\NormalTok{(}\KeywordTok{P}\NormalTok{(x,y)}\OperatorTok{~}\NormalTok{x}\OperatorTok{&}\NormalTok{y, }\DataTypeTok{xlim=}\KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{40}\NormalTok{), }\DataTypeTok{ylim=}\KeywordTok{c}\NormalTok{(}\DecValTok{20}\NormalTok{,}\DecValTok{60}\NormalTok{), }\DataTypeTok{filled=}\OtherTok{FALSE}\NormalTok{, }\DataTypeTok{levels=}\KeywordTok{seq}\NormalTok{(}\DecValTok{20}\NormalTok{,}\DecValTok{50}\NormalTok{,}\DecValTok{2}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{_bookdown_files/math135_handbook_files/figure-latex/unnamed-chunk-54-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plotFun}\NormalTok{(}\KeywordTok{Q}\NormalTok{(x,y)}\OperatorTok{~}\NormalTok{x}\OperatorTok{&}\NormalTok{y, }\DataTypeTok{add=}\OtherTok{TRUE}\NormalTok{, }\DataTypeTok{filled=}\OtherTok{FALSE}\NormalTok{, }\DataTypeTok{levels=}\DecValTok{200}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{_bookdown_files/math135_handbook_files/figure-latex/unnamed-chunk-54-2.pdf}
On this zoomed in plot, we can refine our estimate a bit. The maximum \(f(10,53)=38\) is achieved at \(x=10\) and \(y=53\).

Now, if I want to estimate the Lagrange multiplier \(\lambda\), I would change my constraint a little bit (say to \(210\)) and then look at the change in the optimal value.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plotFun}\NormalTok{(}\KeywordTok{P}\NormalTok{(x,y)}\OperatorTok{~}\NormalTok{x}\OperatorTok{&}\NormalTok{y, }\DataTypeTok{xlim=}\KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{40}\NormalTok{), }\DataTypeTok{ylim=}\KeywordTok{c}\NormalTok{(}\DecValTok{20}\NormalTok{,}\DecValTok{60}\NormalTok{), }\DataTypeTok{filled=}\OtherTok{FALSE}\NormalTok{, }\DataTypeTok{levels=}\KeywordTok{seq}\NormalTok{(}\DecValTok{20}\NormalTok{,}\DecValTok{50}\NormalTok{,}\DecValTok{2}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{_bookdown_files/math135_handbook_files/figure-latex/unnamed-chunk-55-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plotFun}\NormalTok{(}\KeywordTok{Q}\NormalTok{(x,y)}\OperatorTok{~}\NormalTok{x}\OperatorTok{&}\NormalTok{y, }\DataTypeTok{add=}\OtherTok{TRUE}\NormalTok{, }\DataTypeTok{filled=}\OtherTok{FALSE}\NormalTok{, }\DataTypeTok{levels=}\KeywordTok{c}\NormalTok{(}\DecValTok{200}\NormalTok{,}\DecValTok{210}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{_bookdown_files/math135_handbook_files/figure-latex/unnamed-chunk-55-2.pdf}

We have
\[
\lambda = \frac{\triangle \mbox{optimal value}}{\triangle \mbox{constraint}}
= \frac{40 - 38}{210-200} = \frac{2}{10} = 0.2.
\]

\hypertarget{estimating-the-definite-integral}{%
\section{Estimating the Definite Integral}\label{estimating-the-definite-integral}}

The define integral \(\int_{a}^b f(x) dx\) is the (signed) area between the curve \(y=f(x)\) and the \(x\)-axis. We approximate this area by partitioning the interval \([a,b]\) into smaller intervals of width \(\triangle x\) and then summing the areas \(f(x) \triangle x\) of the corresponding rectangles.

Here is code that makes this approximation for the function \(f(x) = x + \sin(x^2)\) over the interval \([5,10]\). The code splits this interval into 100 subintervals. You can get a better approximation by increasing the denominator of \texttt{base=(b-a)/100} to a much larger number, for example: \texttt{base=(b-a)/1000000}.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{f=}\KeywordTok{makeFun}\NormalTok{(x }\OperatorTok{+}\StringTok{ }\KeywordTok{sin}\NormalTok{(x}\OperatorTok{^}\DecValTok{2}\NormalTok{)}\OperatorTok{~}\NormalTok{x)}
\NormalTok{a=}\DecValTok{5}
\NormalTok{b=}\DecValTok{10}
\NormalTok{base=(b}\OperatorTok{-}\NormalTok{a)}\OperatorTok{/}\DecValTok{100}
\NormalTok{points=}\KeywordTok{seq}\NormalTok{(}\DataTypeTok{from=}\NormalTok{a}\OperatorTok{+}\NormalTok{base, }\DataTypeTok{to=}\NormalTok{b, }\DataTypeTok{by=}\NormalTok{base)}
\NormalTok{heights=}\KeywordTok{f}\NormalTok{(points)}
\NormalTok{areas=base}\OperatorTok{*}\NormalTok{heights}
\KeywordTok{sum}\NormalTok{(areas)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 37.67298
\end{verbatim}

\hypertarget{troubleshooting}{%
\section{Troubleshooting}\label{troubleshooting}}

Without fail, you will run into problems. Sometimes RStudio will give you helpful error messages, but sometimes they are obtuse. Here's a list of some common errors and what might be wrong:

\begin{itemize}
\item
  \emph{Nothing ran, all I got was a plus sign\ldots{}} You probably forgot some parentheses. Try the following:

  \begin{itemize}
  \tightlist
  \item
    Enter a parenthesis on that line to see if this closes it out.
  \item
    Press the Escape key to get to a new line.
  \end{itemize}
\item
  \emph{Unexpected symbol in\ldots{}} You may have forgotten a multiplication sign or otherwise gave RStudio a symbol it cannot parse. Check your line of code again to see if you have all your symbols.
\item
  \emph{Object not found\ldots{}} You may not have defined that variable (or function) yet. Check your environment tab to see if it has the object you're looking for (or if you've called it something different than you remember!). You also may be trying to use something from a data set that you have not included as a parameter. See if you need to add in the parameter \texttt{data=....}
\item
  \emph{Could not find function\ldots{}} RStudio doesn't know what function you're using. Check your capitalization and that you have the right packages installed.
\item
  \emph{\ldots{} number of items to replace is not a multiple of replacement length \ldots{}} Your input variable doesn't match the name variable you used in the output when you called \texttt{makeFun}. Maybe you used \texttt{x} on one side of the tilde \texttt{\textasciitilde{}} and \texttt{t} on the other side?
\item
  \emph{Argument ``name'' is missing, with no default\ldots{}}
  You're probably trying to take a derivative or antiderivative without the mosaicCalc package. Go back to the packages section of the introduction for how to fix this.
\item
  \emph{I can't find my data!} You may have fetched it but did not give it a name. Go back to your fetch command and make sure you have assigned it a variable.
\end{itemize}

\hypertarget{intro-to-rstudio}{%
\chapter{Intro to RStudio}\label{intro-to-rstudio}}

Welcome to our RStudio Introduction! RStudio is a front end (user friendly) interface for R, a programming
language for statistics. We'll be using it to work with data and our various forms of functions.

RStudio is a \textbf{long term learning goal} for us. We will be adding new functions and learning new
things throughout the semester.

\hypertarget{getting-started}{%
\section{Getting Started}\label{getting-started}}

Follow my lead as we get ourselves going with RStudio. We will

\begin{itemize}
\tightlist
\item
  Log in to RStudio
\item
  Add some \emph{packages} to the R environment
\item
  Create a math135 directory to work in
\item
  Create our first Rmd (`R Markdown') file
\item
  Knit that Rmd file to create a PDF
\end{itemize}

You will need to replace the auto-generated code block at the top of your Rmd file with this one, which loads the mosaic functionality into the R environment when we knit to PDF.

\begin{verbatim}
```{r setup, include=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
suppressPackageStartupMessages(library(mosaic))
```
\end{verbatim}

\textbf{Pro Tip:} Be kind to future you.

\begin{itemize}
\tightlist
\item
  Save all of your work for this class in the \texttt{math135} subdirectory that we create today.
\item
  Give your files meaningful names. Include the unit, the topic, the date, etc, or a helpful combination of these identifiers.
\end{itemize}

\hypertarget{r-markdown-files}{%
\section{R Markdown files}\label{r-markdown-files}}

An R Markdown file is a hybrid file that has both text and code. You can then \textbf{knit} this Rmd file to make a lovely PDF.

\hypertarget{formatting-regular-text}{%
\subsection{Formatting Regular Text}\label{formatting-regular-text}}

The regular text uses Markdown, which has simple commands to create formatting such has sections, bold, italic, links, itemized lists, and much more. Here are is some example Markdown syntax.

\begin{verbatim}
# Heading 

This is a regular sentence.

## Sub Heading

You get *italics like this.* 

Skipping a line starts a new paragraph.
But if you don't skip a line then it's part of the same paragraph

### Sub Sub Heading

You get **bold text like this.**

Here is how to make an itemized list

* Make sure to skip a line before your first item
* The asterisk must be the **first** character on the line (no spaces!)
* If you want a sublist
   + Start the sublist on the line below the item
   + Indent by three spaces.
   + Use a plus sign
\end{verbatim}

Here is a nice reference page for \href{https://rmarkdown.rstudio.com/authoring_basics.html}{common R Markdown syntax}.

\hypertarget{code-chunks}{%
\subsection{Code Chunks}\label{code-chunks}}

Your R code must be placed inside \textbf{code chunks.} Here is what a code chuck looks like

\begin{verbatim}
```{r}
1 + 1

sin(pi/4)
```
\end{verbatim}

When you knit your Rmd file, the code chunks are executed in order. You can also
run an individual chunk by clicking on the green arrow in its upper right corner.

Adding a code chunk is easy!

\begin{itemize}
\tightlist
\item
  In the top bar of the Markdown window, there's a small, green plus C button.
\item
  When you click this button, it'll bring up options for code blocks to insert
\item
  Select ``R'' which is the first option. (It's the only one we will use.)
\end{itemize}

\hypertarget{writing-code}{%
\section{Writing Code}\label{writing-code}}

Add a code chunk and let's get cracking!

\hypertarget{basic-calculations}{%
\subsection{Basic Calculations}\label{basic-calculations}}

We can use that code chunk to do some basic calculations.

\hypertarget{you-try}{%
\subsubsection{You Try}\label{you-try}}

Create a code block and try to calculate each of the following. Try some other calculations, too!

\begin{itemize}
\tightlist
\item
  \(8+13\)
\item
  \(7*9\)
\item
  \(\sin(\pi/2)\)
\item
  \(\sqrt{121}\)
\item
  \((2.25)^3\)
\item
  \(8 \cos( \pi/6)\)
\end{itemize}

Which ones work? If you got an error, can you fix it? Can you guess the name of the square root function?

\hypertarget{variables-lists-and-sequences}{%
\subsection{Variables, Lists and Sequences}\label{variables-lists-and-sequences}}

When we do a calculation, we can store the result for later. Here are some examples:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{a =}\StringTok{ }\DecValTok{15}
\NormalTok{b =}\StringTok{ }\DecValTok{4} \OperatorTok{*}\StringTok{ }\NormalTok{a}
\end{Highlighting}
\end{Shaded}

R is particularly good at doing calculations on lists of data. So let's make some lists!

RStudio makes a list with the \texttt{c()} command. The ``c'' in short for ``combine''.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{P=}\KeywordTok{c}\NormalTok{(}\DecValTok{3}\NormalTok{, }\DecValTok{5}\NormalTok{, }\DecValTok{11}\NormalTok{, }\DecValTok{-1}\NormalTok{, }\DecValTok{4}\NormalTok{)}
\NormalTok{P}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1]  3  5 11 -1  4
\end{verbatim}

If you want to make a sequence, you use the \texttt{seq()} command. For example:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{S=}\KeywordTok{seq}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DecValTok{10}\NormalTok{)}
\NormalTok{S}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1]  1  2  3  4  5  6  7  8  9 10
\end{verbatim}

Notice that the values increment by 1. You can use a different step size by adding a third argument.
For exmaple, if I wanted a sequence 1, 1.1, 1.2, 1.3, etc\ldots{} all the way up to 2, I would write

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{T=}\KeywordTok{seq}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DecValTok{2}\NormalTok{, }\FloatTok{0.1}\NormalTok{)}
\NormalTok{T}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1] 1.0 1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2.0
\end{verbatim}

Now look at the \textbf{Environment} tab in the upper right window. What do you notice?

\textbf{Pro Tips}: Be kind to future you as well as current collaborators.

\begin{itemize}
\tightlist
\item
  Always write \texttt{0.1} instead of \texttt{.1} in your code. It is much easier to read and to debug later!
\item
  Consider adding a space after your commas to separate parameters. It's easier to read!
\end{itemize}

\hypertarget{you-try-1}{%
\subsubsection{You Try}\label{you-try-1}}

Try to do the following:

\begin{itemize}
\tightlist
\item
  Create a list \texttt{X} containing the values 8, 6, 7, 5, 3, 0, 9.
\item
  Create a list \texttt{Y} containing the sequence of odd integers between (and including) 1 and 19
\item
  What is the output of the command `X\^{}2'? Can you see what R is doing?
\item
  Try making another lists. Apply some functions to that list.
\end{itemize}

\hypertarget{functions}{%
\subsection{Functions}\label{functions}}

Now it's time to write your own function. Here is how you create \(f(x)= x^2 -3\).

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{f =}\StringTok{ }\KeywordTok{makeFun}\NormalTok{(x}\OperatorTok{^}\DecValTok{2} \OperatorTok{-}\StringTok{ }\DecValTok{3} \OperatorTok{~}\StringTok{ }\NormalTok{x)}
\end{Highlighting}
\end{Shaded}

Much of this is pretty intuitive, except for maybe the final \texttt{\textasciitilde{}\ x}. This tilde symbol comes up a lot in RStudio and it indicates \emph{dependence}. We need to tell RStudio that \(f\) is in terms of this variable \(x\), so it knows where to put an input when I ask it to:

Notice! In the right upper window, you now have a function called \texttt{f}. We can do a lot with this function, but
to start, let's evaluate it at 1.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{f}\NormalTok{(}\DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] -2
\end{verbatim}

What do you think this code is doing?

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{f}\NormalTok{(S)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1] -2  1  6 13 22 33 46 61 78 97
\end{verbatim}

\hypertarget{you-try-2}{%
\subsubsection{You Try}\label{you-try-2}}

\begin{itemize}
\tightlist
\item
  Create a new function \(g\) where \(g(t) = \sqrt{t-4}\)
\item
  Evaluate this function at \(t=8\), and \(t=12.34\) and \(t=100\)
\item
  What happens when you try to evaluate this function at \(t=2\)? What do you think that means?
\end{itemize}

\hypertarget{plotting}{%
\subsection{Plotting}\label{plotting}}

Let's see how to create plots using RStudio. First, let's create a plot of this data

\begin{longtable}[]{@{}lllllll@{}}
\toprule
\endhead
x & 0 & 1 & 2 & 3 & 4 & 5\tabularnewline
h(x) & 0 & 1 & 4 & 9 & 16 & 25\tabularnewline
\bottomrule
\end{longtable}

from the function \(h(x)=x^2\).

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{X =}\StringTok{ }\KeywordTok{seq}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{5}\NormalTok{)}
\NormalTok{Y =}\StringTok{ }\NormalTok{X}\OperatorTok{^}\DecValTok{2}
\KeywordTok{plotPoints}\NormalTok{(Y }\OperatorTok{~}\StringTok{ }\NormalTok{X)}
\end{Highlighting}
\end{Shaded}

\includegraphics{_bookdown_files/math135_handbook_files/figure-latex/unnamed-chunk-65-1.pdf}

Notice! We list the \textbf{dependent} variable \texttt{Y} first and then the \textbf{independent} variable \texttt{X} after the tidle \texttt{\textasciitilde{}} (which matches the syntax of \texttt{makeFun}).

We can also plot a function. Once again the dependent variable appears after the tilde.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plotFun}\NormalTok{(x}\OperatorTok{^}\DecValTok{2} \OperatorTok{~}\StringTok{ }\NormalTok{x)}
\end{Highlighting}
\end{Shaded}

\includegraphics{_bookdown_files/math135_handbook_files/figure-latex/unnamed-chunk-66-1.pdf}

We can actually plot the data and the function on the same graph. We will plot the data and then add the function by using the \texttt{add=TRUE} parameter for \texttt{plotFun}. I will also use the optional \texttt{col} parameter to change the color of the function curve.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plotPoints}\NormalTok{(Y }\OperatorTok{~}\StringTok{ }\NormalTok{X)}
\end{Highlighting}
\end{Shaded}

\includegraphics{_bookdown_files/math135_handbook_files/figure-latex/unnamed-chunk-67-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plotFun}\NormalTok{(x}\OperatorTok{^}\DecValTok{2} \OperatorTok{~}\StringTok{ }\NormalTok{x, }\DataTypeTok{add=}\OtherTok{TRUE}\NormalTok{, }\DataTypeTok{col=}\StringTok{'red'}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{_bookdown_files/math135_handbook_files/figure-latex/unnamed-chunk-67-2.pdf}

\hypertarget{you-try-3}{%
\subsubsection{You Try}\label{you-try-3}}

\begin{itemize}
\tightlist
\item
  Create a sequence of integer points \texttt{P} from 1 to 10.
\item
  Define \texttt{Q\ =\ sin(P)}
\item
  Create a plot of \texttt{Q} versus \texttt{P} and then add the function plot of \texttt{sin(x)}
\item
  Try plotting some other data and fuunctions.
\end{itemize}

\hypertarget{troubleshooting-1}{%
\section{Troubleshooting}\label{troubleshooting-1}}

Without fail, you will make mistakes. Things will break and you'll get error messages. That's ok! That's how
we learn.

\hypertarget{you-try-4}{%
\subsection{You Try}\label{you-try-4}}

Each of the following lines of code will break when run. Try them out, notice the error, and see if
you can fix it.

\begin{itemize}
\tightlist
\item
  \texttt{2\ sin(pi/2)}
\item
  \texttt{sqrt(3*(7+5)}
\item
  \texttt{Sqrt(3*(7+5))}
\item
  \texttt{makeFun(x\^{}2-4,\ x)}
\item
  \texttt{makeFun(x+1\ \textasciitilde{}\ t)}
\item
  \texttt{makefun(2x+1\ \textasciitilde{}\ x)}
\end{itemize}

\hypertarget{part-functions}{%
\part{Functions}\label{part-functions}}

\hypertarget{functions-1}{%
\chapter{Functions}\label{functions-1}}

\hypertarget{steps-of-the-modeling-cycle}{%
\section{Steps of the Modeling Cycle}\label{steps-of-the-modeling-cycle}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Ask a question about reality.
\item
  Make some observations and collect the corresponding data.
\item
  Conjecture a model or modify a known model based on the data.
\item
  Test the model against known data (from step 2.) and modify the model as needed.
\item
  Repeat steps 2, 3 and 4 to improve the model
\end{enumerate}

\hypertarget{goals}{%
\section{Goals}\label{goals}}

\begin{itemize}
\tightlist
\item
  Explain what a function is
\item
  Identify and explain independent and dependent variables
\item
  Recognize functions in a variety of forms
\item
  Find a function's intercept(s)
\item
  Identify regions where a function is increasing/decreasing
\item
  Compute the average rate of change between two points on a function
\item
  Determine where a function is concave up/down
\item
  Compute the relative change between two points on a function
\end{itemize}

\hypertarget{activities}{%
\section{Activities}\label{activities}}

\hypertarget{life-insurance}{%
\subsection{Life insurance}\label{life-insurance}}

A family needs to purchase life insurance. What possible inputs might be used to determine the premium (monthly payment) for life insurance?

\hypertarget{bat-species}{%
\subsection{Bat species}\label{bat-species}}

In the Andes mountains in Peru, the number \(N\) of species of bats is a \emph{function} of the elevation \(h\) in feet above sea level.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  What is the independent variable?
\item
  What is the dependent variable?
\item
  Interpret the statement \(f(500)=200\) if \(f\) represents this function.
\item
  Do you expect this function to be increasing or decreasing? Why?
\end{enumerate}

\hypertarget{slope-and-concavity}{%
\subsection{Slope and concavity}\label{slope-and-concavity}}

Sketch each of the following:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  An increasing function that is concave up
\item
  An increasing function that is concave down
\item
  A decreasing function that is concave up
\item
  A decreasing function that is concave down
\end{enumerate}

\hypertarget{relative-change-of-the-dow-jones-average}{%
\subsection{Relative change of the Dow Jones average}\label{relative-change-of-the-dow-jones-average}}

The \emph{relative change} of a function \(f(x)\) on interval \([a,b]\) is
\[ \frac{f(b)-f(a)}{f(a)}.\]

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  What is the \emph{relative change} in the Dow Jones average from 169.84 to 77.90 (from 1 January 1931 to 31 December 1931)?
\item
  Compare this to the \emph{relative change} in the Dow Jones average from 35,443.82 to 35369.09 (from 2 September 2021 to 3 September 2021).
\end{enumerate}

\hypertarget{measuring-rainfall}{%
\subsection{Measuring rainfall}\label{measuring-rainfall}}

One rainy summer day, measurements were recorded (in inches) from a rain gauge every hour.

\begin{longtable}[]{@{}lllllllllll@{}}
\toprule
\textbf{Time} & 8 am & 9 & 10 & 11 & noon & 1 pm & 2 & 3 & 4 & 5 pm\tabularnewline
\midrule
\endhead
\textbf{Amount} & 0.15 & 0.17 & 0.2 & 0.45 & 0.48 & 0.75 & 1.03 & 1.20 & 1.45 & 1.60\tabularnewline
\bottomrule
\end{longtable}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  What was the average rate of rainfall from 8 a.m. to 5 p.m.?
\item
  What are the units of this rate of change?
\end{enumerate}

\hypertarget{linear-functions}{%
\chapter{Linear Functions}\label{linear-functions}}

\hypertarget{goals-1}{%
\section{Goals}\label{goals-1}}

\begin{itemize}
\tightlist
\item
  Explain linear functions in words, tables, equations, and graphs
\item
  Describe the effects of varying parameters in linear functions
\item
  Assess whether given data is linear and, if so, model it with a function
\end{itemize}

\hypertarget{activities-1}{%
\section{Activities}\label{activities-1}}

\hypertarget{graph-of-a-linear-function}{%
\subsection{Graph of a linear function}\label{graph-of-a-linear-function}}

Find the equation \(y=mx+b\) for the graph shown below.

\includegraphics[width=0.5\textwidth,height=\textheight]{images/linear-graph.png}

\hypertarget{height-and-weight-of-american-men}{%
\subsection{Height and weight of American men}\label{height-and-weight-of-american-men}}

The table below lists the average weight, \(w\), in pounds of American men in their sixties for height, \(h\), in inches.

\begin{longtable}[]{@{}lllllllll@{}}
\toprule
\textbf{Height (inches)} & 68 & 69 & 70 & 71 & 72 & 73 & 74 & 75\tabularnewline
\midrule
\endhead
\textbf{Weight (pounds)} & 166 & 171 & 176 & 181 & 186 & 191 & 196 & 201\tabularnewline
\bottomrule
\end{longtable}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Which is the dependent variable and which is the independent variable?\\
\item
  Is this an increasing function or a decreasing function?
\item
  Can this be represented by a linear function? If so, find an equation to describe this data.
\end{enumerate}

\hypertarget{scooter-rates}{%
\subsection{Scooter rates}\label{scooter-rates}}

A scooter company charges for monthly service according to the formula:
\[C(t) =  5.99 + 0.23 t\]
where \(t\) is the number of minutes minutes ridden.

Find and interpret the rate of change and the vertical intercept.

\hypertarget{oil-reserves}{%
\subsection{Oil reserves}\label{oil-reserves}}

There were 1650 billion barrels of proven oil reserves in the world as of 2016. At constant consumption levels (and excluding unproven reserves), the world had enough oil to last about 47 more years beyond 2016.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Create a linear function \(R(t)\) that models the oil reserves (in \emph{billions} of barrels) where \(t\) is the number of years since 2016.
\item
  Find and interpret the rate of change and the vertical intercept of your function.
\end{enumerate}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Explain why a linear model of this data is reasonable.
\item
  Come up with an equation that (approximately) describes this data.
\item
  What decision(s) did you make in part (b)? What are the strengths and weaknesses of your choice?
\item
  Create a plot in RStudio that shows both the data points and the linear function that you found in part (b).

  \begin{itemize}
  \tightlist
  \item
    Start by doing a cut-and-paste the R code above
  \item
    You can add your linear function to this plot using \texttt{plotFun(m*t+b\textasciitilde{}t,add=TRUE)} where \texttt{m} and \texttt{b} are the slope and the vertical intercept of the function you found in part (b)
  \end{itemize}
\end{enumerate}

--\textgreater{}

\hypertarget{average-rate-of-change}{%
\chapter{Average Rate of Change}\label{average-rate-of-change}}

\hypertarget{goals-2}{%
\section{Goals}\label{goals-2}}

\begin{itemize}
\tightlist
\item
  Calculate average rate of change (AROC) on an interval
\item
  Recognize when a function is increasing or decreasing
\item
  Recognize when a function is concave up or concave down
\end{itemize}

\hypertarget{activities-2}{%
\section{Activities}\label{activities-2}}

\hypertarget{aroc-of-a-function}{%
\subsection{AROC of a function}\label{aroc-of-a-function}}

Find the average rate of change (AROC) of the function \(f(x) = 2x^2 -3x + 1\) on the interval between \(x=-1\) and \(x=3\).

\hypertarget{measuring-daily-rainfall}{%
\subsection{Measuring daily rainfall}\label{measuring-daily-rainfall}}

One rainy summer day, hourly measurements of the total rainfall were recorded (in inches) by a rain gauge.

\begin{longtable}[]{@{}lllllllllll@{}}
\toprule
\textbf{Time} & 8 am & 9 & 10 & 11 & noon & 1 pm & 2 & 3 & 4 & 5 pm\tabularnewline
\midrule
\endhead
\textbf{Amount} & 0.15 & 0.17 & 0.2 & 0.45 & 0.48 & 0.75 & 1.03 & 1.20 & 1.45 & 1.60\tabularnewline
\bottomrule
\end{longtable}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  What was the average rate of rainfall from 8 a.m. to 5 p.m.?
\item
  What are the units of this rate of change?
\end{enumerate}

\hypertarget{sketching-a-function}{%
\subsection{Sketching a function}\label{sketching-a-function}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Sketch a \emph{nonlinear} function that has an average rate of change of 1 on the interval \([0,2]\).
\item
  Compare sketches at your table. Are they similar?
\item
  Sketch a function with an AROC of 1 on \([0,2]\) that is \emph{very different} from everyone else's function.
\end{enumerate}

\textbf{The take away:} AROC is an estimation of the behavior of the function on the interval. But there is no guarantee about the quality of the estimate.

\hypertarget{slope-and-concavity-1}{%
\subsection{Slope and Concavity}\label{slope-and-concavity-1}}

Sketch an example of a function that is

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Increasing and concave up
\item
  Increasing and concave down
\item
  Decreasing and concave up
\item
  Decreasing and concave down
\end{enumerate}

\hypertarget{example-function}{%
\subsection{Example Function}\label{example-function}}

Here is the graph of a function.
\includegraphics[width=0.5\textwidth,height=\textheight]{images/slope-concavity-example.png}

Find the subintervals of \([0,10]\) where the function is

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Increasing
\item
  Decreasing
\item
  Concave up
\item
  Concave down
\end{enumerate}

\hypertarget{vinyl-lps}{%
\subsection{Vinyl LPs}\label{vinyl-lps}}

Let \(V(t)\) denote the number of vinyl LP records sold in the US (in millions) in year \(t\).

\[
\begin{array}{c|c|c|c|c|c|c}
t & 1995 & 2000 & 2005 & 2010 & 2015 & 2020 \\
\hline
V(t) & 0.8 & 1.5 & 0.9 & 2.8 & 11.9 & 27.5
\end{array}
\]

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Calculate the average rate of change for each of the five year intervals 1995-2000, 2000-2005, 2005-2010, 2010-15, 2015-2020.
\item
  Use your answers from part 1 to determine whether the function \(V(t)\) is increasing or decreasing on these five year intervals.
\item
  Use your answers from part 1 to estimate whether the function \(V(t)\) is concave up or concave down at each of the points 2000, 2005, 2010 and 2015.
\end{enumerate}

\hypertarget{relative-change-of-the-dow-jones-average-1}{%
\subsection{Relative change of the Dow Jones average}\label{relative-change-of-the-dow-jones-average-1}}

The \emph{relative change} of a function \(f(x)\) on interval \([a,b]\) is
\[ \frac{f(b)-f(a)}{f(a)}.\]

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  What is the \emph{relative change} in the Dow Jones average from 169.84 to 77.90 (from 1 January 1931 to 31 December 1931)?
\item
  Compare this to the \emph{relative change} in the Dow Jones average from 35,443.82 to 35369.09 (from 2 September 2021 to 3 September 2021).
\end{enumerate}

\hypertarget{exponential-and-logarithmic-functions}{%
\chapter{Exponential and Logarithmic Functions}\label{exponential-and-logarithmic-functions}}

\hypertarget{goals-3}{%
\section{Goals}\label{goals-3}}

\begin{itemize}
\tightlist
\item
  Explain exponential functions in words, equations, and graphs
\item
  Describe the effects of varying parameters in exponential functions
\item
  Assess whether given data is exponential, and if so, model it
\item
  Solve for unknowns in an exponent using the logarithm
\item
  Write exponential functions in equivalent forms
\item
  Determine half-lives and doubling times
\end{itemize}

\hypertarget{activities-3}{%
\section{Activities}\label{activities-3}}

\hypertarget{growing-population}{%
\subsection{Growing population}\label{growing-population}}

A population starts with \(50,000\) organisms and grows by \(6.7\%\) each year. Find an exponential model for the population.

\hypertarget{consumer-price-index}{%
\subsection{Consumer price index}\label{consumer-price-index}}

The consumer price index (CPI) for a given year is the amount of money in that year that has the same purchasing power as \$100 in 1983. At the start of 2009, the CPI was 211. Write a formula for the CPI as a function of \(t\) years after 2009, assuming the CPI increases by a rate of 2.8\% every year.

\hypertarget{two-data-sets}{%
\subsection{Two data sets}\label{two-data-sets}}

Here are approximate values of two functions. For each one, decide whether it could be a linear function or an exponentialfunction. Give a reason and then find an approximate formula.

\begin{longtable}[]{@{}llllllll@{}}
\toprule
\endhead
\(x\) & 0 & 0.5 & 1 & 1.5 & 2 & 2.5 & 3\tabularnewline
\(f(x)\) & 26.00 & 26.15 & 26.30 & 26.45 & 26.60 & 26.75 & 26.90\tabularnewline
\(g(x)\) & 190 & 217 & 247 & 282 & 321 & 366 & 418\tabularnewline
\bottomrule
\end{longtable}

\hypertarget{interest-rate-for-an-investment}{%
\subsection{Interest rate for an investment}\label{interest-rate-for-an-investment}}

Suppose that an investment triples in 15 years.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  What is the interest rate \(r\) if the interest is compounded annually: \(I(t) = I_0 (1+r)^t\).
\item
  What is the interest rate \(r\) if interest is compounded continuously: \(I(t) = I_0 e^{rt}\).
\item
  Which rate is larger? Why does that make sense?
\end{enumerate}

\hypertarget{exponential-decay}{%
\subsection{Exponential decay}\label{exponential-decay}}

Radioactive cobalt-60 has a half-life of 5.3 years. If the initial amount is 60 grams, find a formula for the amount of cobalt-60 left after \(t\) years.

\hypertarget{doubling-time}{%
\subsection{Doubling time}\label{doubling-time}}

The doubling time of an exponentially increasing fuunction is the amount of time it takes for the quantity to double. Find the doubling time for the function \(f(t) = 10 e^{1.2t}\).

\hypertarget{people-and-vehicles}{%
\subsection{People and vehicles}\label{people-and-vehicles}}

In 1980, there were about 170 million vehicles (cars and trucks) and about 227 million people in the United States. The number of vehicles has been growing at an annual rate of 4\% a year, while the population has been growing at an annual rate of 1\% a year.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  According to this model, when was there, on average, one vehicle per person?
\item
  In desmos, make a plot of the number of vehicles and the number of people over time on the same graph with a different color for each curve.
\item
  Use your models to predict the number of vehicles and the number of people in 2020. Then use Google to see how accurate these models are over time.
\end{enumerate}

\hypertarget{power-functions}{%
\chapter{Power Functions}\label{power-functions}}

\hypertarget{goals-4}{%
\section{Goals}\label{goals-4}}

\begin{itemize}
\tightlist
\item
  Describe proportional and inversely proportional relationships
\item
  Recognize power functions by creating a log-log plot.
\item
  Fit a power function to data
\end{itemize}

When you have data that you suspect comes from a power function
\[y=k x^p,\]
here is how you can find the constants \(p\) and \(k\)

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Take the natural log of both the \(x\)-axis data and the \(y\)-axis data
\item
  Fit a line to the resulting data
\item
  Use the slope and \(y\)-intercept of this line to find the values of the power \(p\) and the constant \(k\).
\end{enumerate}

\hypertarget{activities-4}{%
\section{Activities}\label{activities-4}}

\hypertarget{examples-and-non-examples}{%
\subsection{Examples and non-examples}\label{examples-and-non-examples}}

Determine whether each of the following is a power function \(y=k x^p\). If so, then find the leading constant \(k\) and the power \(p\).

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \(y=5 \cdot 3^x\)
\item
  \(y = 10 \sqrt{x}\)
\item
  \(\displaystyle{y = \frac{7}{2x}}\)
\item
  \(y = 9x^2 -2\)
\item
  \(y = (4x)^3\)
\end{enumerate}

\hypertarget{descriptions-of-power-functions}{%
\subsection{Descriptions of power functions}\label{descriptions-of-power-functions}}

Write a formula representing the function.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  The energy \(E\) expended by a swimming dolphin is proportional to the cube of its speed \(v\).
\item
  The number \(N\) of animal species with body length \(L\) is inversely proportional to the square of the body length.
\end{enumerate}

\hypertarget{allometry-of-pectoral-fins}{%
\subsection{Allometry of pectoral fins}\label{allometry-of-pectoral-fins}}

Allometry is the study of the relative sizes of parts of an animal. Often, as an animal grows, the size of a body part will be a power function of its length. Here is a table of fish body lengths \(L\) and pectoral fin lengths \(F\).

\begin{longtable}[]{@{}lllllllllll@{}}
\toprule
\textbf{Body Length (cm)} & 6.35 & 7.03 & 8.17 & 9.03 & 9.21 & 9.39 & 9.58 & 11.59 & &\tabularnewline
\midrule
\endhead
\textbf{Pectoral Fin Length (cm)} & 2.72 & 3.49 & 4.06 & 4.95 & 4.86 & 5.00 & 5.05 & 6.05 & &\tabularnewline
\bottomrule
\end{longtable}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Create a log-log plot of this data and explain why this provides evidence that there is a proportional relationship between fin length and body length.
\item
  Find the power function \(F = k L^p\) that fits this data.
\item
  Do the fin lengths increase faster, slower or at the same rate as the body lengths? How do you know?
\end{enumerate}

\hypertarget{specific-heat}{%
\subsection{Specific heat}\label{specific-heat}}

The specific heat \(s\) of an element is the number of calories of heat required to raise the temperature of one gram of the element by one degree Celcius. Use the following data to decide if \(s\) is proportional or inversely proportional to the atomic weight \(w\). Then find the function \(s(w)\).

\begin{longtable}[]{@{}lllllllll@{}}
\toprule
\textbf{Element} & Li & Mg & Al & Fe & Ag & Pb & Hg &\tabularnewline
\midrule
\endhead
\textbf{weight} \(w\) (g/mol) & 6.9 & 24.3 & 27.0 & 55.8 & 107.9 & 207.2 & 200.6 &\tabularnewline
\textbf{specific heat} \(s\) (cal) & 0.92 & 0.25 & 0.21 & 0.11 & 0.056 & 0.031 & 0.033 &\tabularnewline
\bottomrule
\end{longtable}

\hypertarget{periodic-functions}{%
\chapter{Periodic Functions}\label{periodic-functions}}

\hypertarget{goals-5}{%
\section{Goals}\label{goals-5}}

\begin{itemize}
\tightlist
\item
  Describe periodic phenomena using words, equations and graphs.
\item
  Explain the effect of changing the four parameters of sine and cosine functions.
\item
  Recognize and model periodic phenomena.
\end{itemize}

\hypertarget{activities-5}{%
\section{Activities}\label{activities-5}}

\hypertarget{periodic-function-examples}{%
\subsection{Periodic function examples}\label{periodic-function-examples}}

Brainstorm at your table! Give four examples of periodic phenomena. Can you think of a periodic phenomenon that doesn't ``look like'' a sine function. (We've already seen one: the electrocardiagram pattern for a heartbeat),

\hypertarget{find-a-periodic-formula}{%
\subsection{Find a periodic formula}\label{find-a-periodic-formula}}

For each graph shown, write down a corresponding periodic formula of the form \(A \sin(\omega x) + C\) or \(A \cos(\omega x) + C\).

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
\end{enumerate}

\includegraphics[width=0.75\linewidth]{_bookdown_files/math135_handbook_files/figure-latex/periodic4-1}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\item
\end{enumerate}

\includegraphics[width=0.75\linewidth]{_bookdown_files/math135_handbook_files/figure-latex/periodic1-1}

\hypertarget{variable-star}{%
\subsection{Variable star}\label{variable-star}}

Mira is a red giant star in the constellation Cetus. Its brightness (as seen from Earth) fluctuates as it expands and contracts. The apparent magnitude ranges from a maximum of 10th magnitude to a minimum of 2nd magnitude. This apparent brightness has a period of 332 days.

Find a formula that models the brightness of Mira as a function of time, with \(t=0\) at peak brightness.

\hypertarget{tides-and-currents}{%
\subsection{Tides and currents}\label{tides-and-currents}}

Here is a plot of the water level (in red) and the current speed (in blue) of the St.~Johns River. Each of them go through two cycles in 24.83 hours. This is the length of one \textbf{lunar day}: the time it takes for a point on the Earth to rotate from an exact point under the Moon to that same point under the Moon. (This is slightly longer than one day because the Moon revolves around the Earth in the same direction as the Earth's rotation.) So you can assume that the period for each is 12.415 hours.

Model the water level \(w(t)\) and the current speed \(c(t)\) using periodic functions, where \(t\) is the number of hours since midnight April 28, 1998.

\begin{itemize}
\tightlist
\item
  Be sure to use the appropriate vertical axis for each one!
\item
  Decide which one will be easier to model: \(w(t)\) or \(c(t)\)? Do that one first, and then adjust that function to get the other one.
\end{itemize}

\includegraphics[width=0.8\textwidth,height=\textheight]{images/tidevscurrentstjohns.jpeg}

Image Source: \url{https://tidesandcurrents.noaa.gov/}

\hypertarget{rainfall-in-seattle}{%
\subsection{Rainfall in Seattle}\label{rainfall-in-seattle}}

Here is the average rainfall in Seattle.

\begin{longtable}[]{@{}lllllllllllll@{}}
\toprule
\textbf{Month} & Jan & Feb & Mar & Apr & May & Jun & Jul & Aug & Sep & Oct & Nov & Dec\tabularnewline
\midrule
\endhead
\textbf{Rainfall} (inches) & 5.1 & 3.9 & 4 & 2.8 & 1.9 & 1.5 & 0.9 & 1.2 & 1.9 & 3.2 & 5.4 & 6.1\tabularnewline
\bottomrule
\end{longtable}

Model the monthly rainfall with a periodic function \(r(t)\) where \(t=0\) corresponds to January. Your function must attain its maximum in December, so you will need a horizontal shift!

\hypertarget{multivariable-functions}{%
\chapter{Multivariable Functions}\label{multivariable-functions}}

\hypertarget{goals-6}{%
\section{Goals}\label{goals-6}}

\begin{itemize}
\tightlist
\item
  Identify and explain independent and dependent variables in
  multivariable functions
\item
  Interpret functions represented as tables and equations
\item
  Interpret contour diagrams and make function value estimates
\item
  Interpret cross sections and connect them with contour
  diagrams
\item
  Use RStudio to create a contour plot and a surface plot of a function \(z=f(x,y)\).
\end{itemize}

\hypertarget{activities-6}{%
\section{Activities}\label{activities-6}}

\hypertarget{matching-contours}{%
\subsection{Matching Contours}\label{matching-contours}}

Match contours I - IV to surfaces A - D.

\includegraphics[width=0.8\textwidth,height=\textheight]{images/contour-match.png}

\hypertarget{plotting-in-rstudio}{%
\subsection{Plotting in RStudio}\label{plotting-in-rstudio}}

Create these plots using RStudio.

You will need to import the mosaic package. Cut and paste this code chunk into your RMD file and run it. This will load in the \texttt{plotFun} command to create surface plots and contour plots.

\begin{verbatim}
```{r setup, include=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
suppressPackageStartupMessages(library(mosaic))
```
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Windchill Function
\end{enumerate}

\[
W(T,V) = 35.74+0.6215 \, T-35.75 \, V^{0.16}+0.4275 \, T \,  V^{0.16}
\]

Surface plot

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plotFun}\NormalTok{(}\FloatTok{35.74+0.6215}\OperatorTok{*}\NormalTok{T}\FloatTok{-35.75}\OperatorTok{*}\NormalTok{V}\OperatorTok{^}\NormalTok{(}\FloatTok{0.16}\NormalTok{)}\OperatorTok{+}\FloatTok{0.4275}\OperatorTok{*}\NormalTok{T}\OperatorTok{*}\NormalTok{V}\OperatorTok{^}\NormalTok{(}\FloatTok{0.16}\NormalTok{)}\OperatorTok{~}\NormalTok{T }\OperatorTok{&}\StringTok{ }\NormalTok{V, }\DataTypeTok{T.lim=}\KeywordTok{range}\NormalTok{(}\OperatorTok{-}\DecValTok{30}\NormalTok{,}\DecValTok{30}\NormalTok{),}
\DataTypeTok{V.lim=}\KeywordTok{range}\NormalTok{(}\DecValTok{5}\NormalTok{,}\DecValTok{40}\NormalTok{),}\DataTypeTok{surface=}\OtherTok{TRUE}\NormalTok{,}\DataTypeTok{zlab=}\StringTok{"W"}\NormalTok{,}\DataTypeTok{xlab=}\StringTok{"T"}\NormalTok{,}\DataTypeTok{ylab=}\StringTok{"V"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{_bookdown_files/math135_handbook_files/figure-latex/unnamed-chunk-71-1.pdf}

Contour Plot

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plotFun}\NormalTok{(}\FloatTok{35.74+0.6215}\OperatorTok{*}\NormalTok{T}\FloatTok{-35.75}\OperatorTok{*}\NormalTok{V}\OperatorTok{^}\NormalTok{(}\FloatTok{0.16}\NormalTok{)}\OperatorTok{+}\FloatTok{0.4275}\OperatorTok{*}\NormalTok{T}\OperatorTok{*}\NormalTok{V}\OperatorTok{^}\NormalTok{(}\FloatTok{0.16}\NormalTok{)}\OperatorTok{~}\NormalTok{T }\OperatorTok{&}\StringTok{ }\NormalTok{V, }\DataTypeTok{T.lim=}\KeywordTok{range}\NormalTok{(}\OperatorTok{-}\DecValTok{40}\NormalTok{,}\DecValTok{40}\NormalTok{), }\DataTypeTok{filled=}\OtherTok{FALSE}\NormalTok{,}
\DataTypeTok{V.lim=}\KeywordTok{range}\NormalTok{(}\DecValTok{5}\NormalTok{,}\DecValTok{60}\NormalTok{),}\DataTypeTok{zlab=}\StringTok{"V"}\NormalTok{,}\DataTypeTok{xlab=}\StringTok{"T"}\NormalTok{,}\DataTypeTok{ylab=}\StringTok{"V"}\NormalTok{, }\DataTypeTok{levels =} \KeywordTok{seq}\NormalTok{(}\OperatorTok{-}\DecValTok{100}\NormalTok{,}\DecValTok{40}\NormalTok{,}\DecValTok{10}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{_bookdown_files/math135_handbook_files/figure-latex/unnamed-chunk-72-1.pdf}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  Another Function
\end{enumerate}

\[
f(x,y) = \frac{\sin(x^2+y^2)}{0.1+x^2+y^2}+ \frac{1}{2}(x^2+4y^2)e^{1-x^2-y^2}
\]
Surface Plot

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plotFun}\NormalTok{(}\KeywordTok{sin}\NormalTok{(x}\OperatorTok{^}\DecValTok{2}\OperatorTok{+}\NormalTok{y}\OperatorTok{^}\DecValTok{2}\NormalTok{)}\OperatorTok{/}\NormalTok{(}\FloatTok{0.1}\OperatorTok{+}\NormalTok{x}\OperatorTok{^}\DecValTok{2}\OperatorTok{+}\NormalTok{y}\OperatorTok{^}\DecValTok{2}\NormalTok{)}\OperatorTok{+}\NormalTok{(x}\OperatorTok{^}\DecValTok{2}\OperatorTok{+}\DecValTok{4}\OperatorTok{*}\NormalTok{y}\OperatorTok{^}\DecValTok{2}\NormalTok{)}\OperatorTok{*}\KeywordTok{exp}\NormalTok{(}\DecValTok{1}\OperatorTok{-}\NormalTok{x}\OperatorTok{^}\DecValTok{2}\OperatorTok{-}\NormalTok{y}\OperatorTok{^}\DecValTok{2}\NormalTok{)}\OperatorTok{/}\DecValTok{2}\OperatorTok{~}\NormalTok{x}\OperatorTok{&}\NormalTok{y,}
\DataTypeTok{surface=}\OtherTok{TRUE}\NormalTok{,}\DataTypeTok{zlab=}\StringTok{"f(x,y)"}\NormalTok{,}\DataTypeTok{x.lim=}\KeywordTok{range}\NormalTok{(}\OperatorTok{-}\DecValTok{3}\NormalTok{,}\DecValTok{3}\NormalTok{),}\DataTypeTok{y.lim=}\KeywordTok{range}\NormalTok{(}\OperatorTok{-}\DecValTok{3}\NormalTok{,}\DecValTok{3}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{_bookdown_files/math135_handbook_files/figure-latex/unnamed-chunk-73-1.pdf}

Contour Plot

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plotFun}\NormalTok{(}\KeywordTok{sin}\NormalTok{(x}\OperatorTok{^}\DecValTok{2}\OperatorTok{+}\NormalTok{y}\OperatorTok{^}\DecValTok{2}\NormalTok{)}\OperatorTok{/}\NormalTok{(}\FloatTok{0.1}\OperatorTok{+}\NormalTok{x}\OperatorTok{^}\DecValTok{2}\OperatorTok{+}\NormalTok{y}\OperatorTok{^}\DecValTok{2}\NormalTok{)}\OperatorTok{+}\NormalTok{(x}\OperatorTok{^}\DecValTok{2}\OperatorTok{+}\DecValTok{4}\OperatorTok{*}\NormalTok{y}\OperatorTok{^}\DecValTok{2}\NormalTok{)}\OperatorTok{*}\KeywordTok{exp}\NormalTok{(}\DecValTok{1}\OperatorTok{-}\NormalTok{x}\OperatorTok{^}\DecValTok{2}\OperatorTok{-}\NormalTok{y}\OperatorTok{^}\DecValTok{2}\NormalTok{)}\OperatorTok{/}\DecValTok{2}\OperatorTok{~}\NormalTok{x}\OperatorTok{&}\NormalTok{y,}
\DataTypeTok{filled=}\OtherTok{FALSE}\NormalTok{,}\DataTypeTok{zlab=}\StringTok{"f(x,y)"}\NormalTok{,}\DataTypeTok{x.lim=}\KeywordTok{range}\NormalTok{(}\OperatorTok{-}\DecValTok{3}\NormalTok{,}\DecValTok{3}\NormalTok{),}\DataTypeTok{y.lim=}\KeywordTok{range}\NormalTok{(}\OperatorTok{-}\DecValTok{3}\NormalTok{,}\DecValTok{3}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{_bookdown_files/math135_handbook_files/figure-latex/unnamed-chunk-74-1.pdf}

\hypertarget{cross-sections}{%
\subsection{Cross Sections}\label{cross-sections}}

For each of the the two functions in the previous problem:

\begin{itemize}
\tightlist
\item
  Sketch two or three horizontal cross sections
\item
  Sketch two or three vertical cross sections
\item
  Then use RStudio to create these cross sections and compare to your sketches. How well did you do?
\end{itemize}

\hypertarget{plotting-in-rstudio-1}{%
\subsection{Plotting in RStudio}\label{plotting-in-rstudio-1}}

Here is some sample RStudio code that defines a function \texttt{P(x,y)\ =\ x\^{}2\ -\ 4x\ y\^{}3} and then creates two contour plots. The first plot uses the default domain and default level curves (chosen by RStudio). The second plot specifies both of these using additional arguments.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{P =}\StringTok{ }\KeywordTok{makeFun}\NormalTok{(x}\OperatorTok{^}\DecValTok{2} \OperatorTok{-}\StringTok{ }\DecValTok{4}\OperatorTok{*}\NormalTok{x}\OperatorTok{*}\NormalTok{y}\OperatorTok{^}\DecValTok{3} \OperatorTok{~}\StringTok{ }\NormalTok{x}\OperatorTok{&}\NormalTok{y)}

\KeywordTok{plotFun}\NormalTok{(}\KeywordTok{P}\NormalTok{(x,y) }\OperatorTok{~}\StringTok{ }\NormalTok{x}\OperatorTok{&}\NormalTok{y, }\DataTypeTok{filled=}\OtherTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{_bookdown_files/math135_handbook_files/figure-latex/unnamed-chunk-75-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plotFun}\NormalTok{(}\KeywordTok{P}\NormalTok{(x,y) }\OperatorTok{~}\StringTok{ }\NormalTok{x}\OperatorTok{&}\NormalTok{y, }\DataTypeTok{filled=}\OtherTok{FALSE}\NormalTok{, }\DataTypeTok{x.lim=}\KeywordTok{range}\NormalTok{(}\OperatorTok{-}\DecValTok{5}\NormalTok{,}\DecValTok{5}\NormalTok{),}\DataTypeTok{y.lim=}\KeywordTok{range}\NormalTok{(}\OperatorTok{-}\DecValTok{5}\NormalTok{,}\DecValTok{5}\NormalTok{), }\DataTypeTok{levels =} \KeywordTok{seq}\NormalTok{(}\OperatorTok{-}\DecValTok{1000}\NormalTok{, }\DecValTok{1000}\NormalTok{, }\DecValTok{200}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{_bookdown_files/math135_handbook_files/figure-latex/unnamed-chunk-75-2.pdf}

Using RStudio,

\begin{itemize}
\tightlist
\item
  Use \texttt{makeFun} to create each of these functions.
\item
  Then use \texttt{plotFun} to create a contour plot.
\end{itemize}

Try out different horizontal and vertical domains that are centered around the origin. Change the level curves.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \(f(x,y) = \sin(\sqrt{x^2+y^2})\)
\item
  \(g(x,y) = 100 x^2 y^2 e^{-x^2-y^2}\)
\item
  \(h(x,y) = \sin^2x + \frac{1}{4}y^2\)
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plotFun}\NormalTok{(}\KeywordTok{W}\NormalTok{(T,}\DecValTok{40}\NormalTok{)}\OperatorTok{~}\NormalTok{T, }\DataTypeTok{T.lim=}\KeywordTok{range}\NormalTok{(}\OperatorTok{-}\DecValTok{40}\NormalTok{,}\DecValTok{40}\NormalTok{), }\DataTypeTok{xlab=}\StringTok{"T"}\NormalTok{,}\DataTypeTok{ylab=}\StringTok{"W"}\NormalTok{,  }\DataTypeTok{main=}\StringTok{"Windchill for V=40"}\NormalTok{,}\DataTypeTok{levels =} \KeywordTok{seq}\NormalTok{(}\OperatorTok{-}\DecValTok{100}\NormalTok{,}\DecValTok{40}\NormalTok{,}\DecValTok{10}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{_bookdown_files/math135_handbook_files/figure-latex/unnamed-chunk-76-2.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plotFun}\NormalTok{(}\KeywordTok{W}\NormalTok{(}\OperatorTok{-}\DecValTok{20}\NormalTok{,V)}\OperatorTok{~}\NormalTok{V, }\DataTypeTok{V.lim=}\KeywordTok{range}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{60}\NormalTok{), }\DataTypeTok{xlab=}\StringTok{"V"}\NormalTok{,}\DataTypeTok{ylab=}\StringTok{"W"}\NormalTok{,  }\DataTypeTok{main=}\StringTok{"Windchill for T=-20"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{_bookdown_files/math135_handbook_files/figure-latex/unnamed-chunk-77-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plotFun}\NormalTok{(}\KeywordTok{W}\NormalTok{(}\DecValTok{20}\NormalTok{,V)}\OperatorTok{~}\NormalTok{V, }\DataTypeTok{V.lim=}\KeywordTok{range}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{60}\NormalTok{), }\DataTypeTok{xlab=}\StringTok{"V"}\NormalTok{,}\DataTypeTok{ylab=}\StringTok{"W"}\NormalTok{,  }\DataTypeTok{main=}\StringTok{"Windchill for T=20"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{_bookdown_files/math135_handbook_files/figure-latex/unnamed-chunk-77-2.pdf}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  Here are some cross sections for the second function.
  \[
  f(x,y) = \frac{\sin(x^2+y^2)}{0.1+x^2+y^2}+ \frac{1}{2}(x^2+4y^2)e^{1-x^2-y^2}
  \]
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{f =}\StringTok{ }\KeywordTok{makeFun}\NormalTok{(}\KeywordTok{sin}\NormalTok{(x}\OperatorTok{^}\DecValTok{2}\OperatorTok{+}\NormalTok{y}\OperatorTok{^}\DecValTok{2}\NormalTok{)}\OperatorTok{/}\NormalTok{(}\FloatTok{0.1}\OperatorTok{+}\NormalTok{x}\OperatorTok{^}\DecValTok{2}\OperatorTok{+}\NormalTok{y}\OperatorTok{^}\DecValTok{2}\NormalTok{)}\OperatorTok{+}\NormalTok{(x}\OperatorTok{^}\DecValTok{2}\OperatorTok{+}\DecValTok{4}\OperatorTok{*}\NormalTok{y}\OperatorTok{^}\DecValTok{2}\NormalTok{)}\OperatorTok{*}\KeywordTok{exp}\NormalTok{(}\DecValTok{1}\OperatorTok{-}\NormalTok{x}\OperatorTok{^}\DecValTok{2}\OperatorTok{-}\NormalTok{y}\OperatorTok{^}\DecValTok{2}\NormalTok{)}\OperatorTok{/}\DecValTok{2}\OperatorTok{~}\NormalTok{x}\OperatorTok{&}\NormalTok{y)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plotFun}\NormalTok{(}\KeywordTok{f}\NormalTok{(x,}\OperatorTok{-}\FloatTok{1.5}\NormalTok{)}\OperatorTok{~}\NormalTok{x,}\DataTypeTok{x.lim=}\KeywordTok{range}\NormalTok{(}\OperatorTok{-}\DecValTok{1}\NormalTok{,}\DecValTok{1}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{_bookdown_files/math135_handbook_files/figure-latex/unnamed-chunk-79-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plotFun}\NormalTok{(}\KeywordTok{f}\NormalTok{(x,}\DecValTok{0}\NormalTok{)}\OperatorTok{~}\NormalTok{x,}\DataTypeTok{x.lim=}\KeywordTok{range}\NormalTok{(}\OperatorTok{-}\DecValTok{1}\NormalTok{,}\DecValTok{1}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{_bookdown_files/math135_handbook_files/figure-latex/unnamed-chunk-79-2.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plotFun}\NormalTok{(}\KeywordTok{f}\NormalTok{(x,}\FloatTok{1.5}\NormalTok{)}\OperatorTok{~}\NormalTok{x,}\DataTypeTok{x.lim=}\KeywordTok{range}\NormalTok{(}\OperatorTok{-}\DecValTok{1}\NormalTok{,}\DecValTok{1}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{_bookdown_files/math135_handbook_files/figure-latex/unnamed-chunk-79-3.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plotFun}\NormalTok{(}\KeywordTok{f}\NormalTok{(}\OperatorTok{-}\FloatTok{1.5}\NormalTok{,y)}\OperatorTok{~}\NormalTok{y,}\DataTypeTok{y.lim=}\KeywordTok{range}\NormalTok{(}\OperatorTok{-}\DecValTok{1}\NormalTok{,}\DecValTok{1}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{_bookdown_files/math135_handbook_files/figure-latex/unnamed-chunk-80-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plotFun}\NormalTok{(}\KeywordTok{f}\NormalTok{(}\DecValTok{0}\NormalTok{,y)}\OperatorTok{~}\NormalTok{y,}\DataTypeTok{y.lim=}\KeywordTok{range}\NormalTok{(}\OperatorTok{-}\DecValTok{1}\NormalTok{,}\DecValTok{1}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{_bookdown_files/math135_handbook_files/figure-latex/unnamed-chunk-80-2.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plotFun}\NormalTok{(}\KeywordTok{f}\NormalTok{(}\FloatTok{1.5}\NormalTok{,y)}\OperatorTok{~}\NormalTok{y,}\DataTypeTok{y.lim=}\KeywordTok{range}\NormalTok{(}\OperatorTok{-}\DecValTok{1}\NormalTok{,}\DecValTok{1}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{_bookdown_files/math135_handbook_files/figure-latex/unnamed-chunk-80-3.pdf}

\hypertarget{plotting-in-rstudio-2}{%
\subsection{Plotting in RStudio}\label{plotting-in-rstudio-2}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \(f(x,y) = \sin(\sqrt{x^2+y^2})\)
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{f =}\StringTok{ }\KeywordTok{makeFun}\NormalTok{(}\KeywordTok{sin}\NormalTok{( }\KeywordTok{sqrt}\NormalTok{((x}\OperatorTok{^}\DecValTok{2}\OperatorTok{+}\NormalTok{y}\OperatorTok{^}\DecValTok{2}\NormalTok{))) }\OperatorTok{~}\StringTok{ }\NormalTok{x}\OperatorTok{&}\NormalTok{y)}

\KeywordTok{plotFun}\NormalTok{(}\KeywordTok{f}\NormalTok{(x,y) }\OperatorTok{~}\StringTok{ }\NormalTok{x}\OperatorTok{&}\NormalTok{y, }\DataTypeTok{filled=}\OtherTok{FALSE}\NormalTok{, }\DataTypeTok{x.lim=}\KeywordTok{range}\NormalTok{(}\OperatorTok{-}\DecValTok{3}\NormalTok{,}\DecValTok{3}\NormalTok{),}\DataTypeTok{y.lim=}\KeywordTok{range}\NormalTok{(}\OperatorTok{-}\DecValTok{3}\NormalTok{,}\DecValTok{3}\NormalTok{), }\DataTypeTok{levels =} \KeywordTok{seq}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{1}\NormalTok{, }\FloatTok{0.25}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{_bookdown_files/math135_handbook_files/figure-latex/unnamed-chunk-81-1.pdf}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  \(g(x,y) = x^2 y^2 e^{-x^2-y^2}\)
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{g =}\StringTok{ }\KeywordTok{makeFun}\NormalTok{(}\DecValTok{100} \OperatorTok{*}\StringTok{ }\NormalTok{x}\OperatorTok{^}\DecValTok{2} \OperatorTok{*}\StringTok{  }\NormalTok{y}\OperatorTok{^}\DecValTok{2} \OperatorTok{*}\StringTok{ }\KeywordTok{exp}\NormalTok{(}\OperatorTok{-}\NormalTok{x}\OperatorTok{^}\DecValTok{2}\OperatorTok{-}\NormalTok{y}\OperatorTok{^}\DecValTok{2}\NormalTok{)}\OperatorTok{~}\StringTok{ }\NormalTok{x}\OperatorTok{&}\NormalTok{y)}

\KeywordTok{plotFun}\NormalTok{(}\KeywordTok{g}\NormalTok{(x,y) }\OperatorTok{~}\StringTok{ }\NormalTok{x}\OperatorTok{&}\NormalTok{y, }\DataTypeTok{filled=}\OtherTok{FALSE}\NormalTok{, }\DataTypeTok{x.lim=}\KeywordTok{range}\NormalTok{(}\OperatorTok{-}\DecValTok{2}\NormalTok{,}\DecValTok{2}\NormalTok{), }\DataTypeTok{y.lim=}\KeywordTok{range}\NormalTok{(}\OperatorTok{-}\DecValTok{2}\NormalTok{,}\DecValTok{2}\NormalTok{), }\DataTypeTok{levels=}\KeywordTok{seq}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{15}\NormalTok{,}\DecValTok{3}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{_bookdown_files/math135_handbook_files/figure-latex/unnamed-chunk-82-1.pdf}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  \(h(x,y) = \sin^2x + \frac{1}{4}y^2\)
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{g =}\StringTok{ }\KeywordTok{makeFun}\NormalTok{((}\KeywordTok{sin}\NormalTok{(x))}\OperatorTok{^}\DecValTok{2} \OperatorTok{+}\StringTok{ }\NormalTok{y}\OperatorTok{^}\DecValTok{2}\OperatorTok{/}\DecValTok{4} \OperatorTok{~}\StringTok{ }\NormalTok{x}\OperatorTok{&}\NormalTok{y)}

\KeywordTok{plotFun}\NormalTok{(}\KeywordTok{g}\NormalTok{(x,y) }\OperatorTok{~}\StringTok{ }\NormalTok{x}\OperatorTok{&}\NormalTok{y, }\DataTypeTok{filled=}\OtherTok{FALSE}\NormalTok{, }\DataTypeTok{x.lim=}\KeywordTok{range}\NormalTok{(}\OperatorTok{-}\DecValTok{5}\NormalTok{,}\DecValTok{5}\NormalTok{), }\DataTypeTok{y.lim=}\KeywordTok{range}\NormalTok{(}\OperatorTok{-}\DecValTok{3}\NormalTok{,}\DecValTok{3}\NormalTok{), }\DataTypeTok{levels=}\KeywordTok{seq}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{4}\NormalTok{,}\FloatTok{0.5}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{_bookdown_files/math135_handbook_files/figure-latex/unnamed-chunk-83-1.pdf}
--\textgreater{}

\hypertarget{part-units-and-estimation}{%
\part{Units and Estimation}\label{part-units-and-estimation}}

\hypertarget{dimensions-and-units}{%
\chapter{Dimensions and Units}\label{dimensions-and-units}}

There are 7 \textbf{fundamental dimensions}.

\begin{longtable}[]{@{}lll@{}}
\caption{Fundamental Dimensions}\tabularnewline
\toprule
Dimension & Symbol & Sample Units\tabularnewline
\midrule
\endfirsthead
\toprule
Dimension & Symbol & Sample Units\tabularnewline
\midrule
\endhead
Length & \(L\) & meter (m), foot (ft), mile (mi)\tabularnewline
Time & \(T\) & second (s), day, hour (hr)\tabularnewline
Mass & \(M\) & gram (g), kilogram (kg)\tabularnewline
Amount & \(N\) & mole (mol)\tabularnewline
Temperature & \(\theta\) & Kelvin (K), Celsius (\(^\circ \mbox{C}\))\tabularnewline
Electric Current & \(I\) & Ampere (amp)\tabularnewline
Luminosity & \(J\) & Candela (cd)\tabularnewline
\bottomrule
\end{longtable}

Everything else is a \textbf{derived dimension}. Here are some examples.

\begin{longtable}[]{@{}llll@{}}
\caption{Derived Dimensions}\tabularnewline
\toprule
\begin{minipage}[b]{0.21\columnwidth}\raggedright
Dimension\strut
\end{minipage} & \begin{minipage}[b]{0.17\columnwidth}\raggedright
Symbol\strut
\end{minipage} & \begin{minipage}[b]{0.23\columnwidth}\raggedright
Intuition\strut
\end{minipage} & \begin{minipage}[b]{0.28\columnwidth}\raggedright
Sample Units\strut
\end{minipage}\tabularnewline
\midrule
\endfirsthead
\toprule
\begin{minipage}[b]{0.21\columnwidth}\raggedright
Dimension\strut
\end{minipage} & \begin{minipage}[b]{0.17\columnwidth}\raggedright
Symbol\strut
\end{minipage} & \begin{minipage}[b]{0.23\columnwidth}\raggedright
Intuition\strut
\end{minipage} & \begin{minipage}[b]{0.28\columnwidth}\raggedright
Sample Units\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.21\columnwidth}\raggedright
Area\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedright
\(L^2\)\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
length \(\times\) width\strut
\end{minipage} & \begin{minipage}[t]{0.28\columnwidth}\raggedright
square foot (ft\(^2\)), square meter (\(m^2\)), acre\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.21\columnwidth}\raggedright
Volume\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedright
\(L^3\)\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
length \(\times\) width \(\times\) height\strut
\end{minipage} & \begin{minipage}[t]{0.28\columnwidth}\raggedright
cubic meter (m\(^3\)), liter(\(L\)), gallon (\(gal\))\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.21\columnwidth}\raggedright
Velocity\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedright
\(\frac{L}{T}\)\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
distance/time\strut
\end{minipage} & \begin{minipage}[t]{0.28\columnwidth}\raggedright
meter/second, miles/hour\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.21\columnwidth}\raggedright
Acceleration\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedright
\(\frac{L}{T^2}\)\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
velocity/time\strut
\end{minipage} & \begin{minipage}[t]{0.28\columnwidth}\raggedright
meters/second\(^2\)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.21\columnwidth}\raggedright
Force\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedright
\(\frac{ML}{T^2}\)\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
mass \(\times\) acceleration\strut
\end{minipage} & \begin{minipage}[t]{0.28\columnwidth}\raggedright
Newton (N), pound (lb)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.21\columnwidth}\raggedright
Energy (Work)\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedright
\(\frac{ML^2}{T^2}\)\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
force \(\times\) displacement\strut
\end{minipage} & \begin{minipage}[t]{0.28\columnwidth}\raggedright
Joule (J), calorie, kilowatt hour (\(kwh\)), foot-pound\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.21\columnwidth}\raggedright
Power\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedright
\(\frac{ML^2}{T^3}\)\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
energy/time\strut
\end{minipage} & \begin{minipage}[t]{0.28\columnwidth}\raggedright
Watt (W), horsepower\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.21\columnwidth}\raggedright
Density\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedright
\(\frac{M}{L^3}\)\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
mass/volume\strut
\end{minipage} & \begin{minipage}[t]{0.28\columnwidth}\raggedright
kilogram/meter\(^3\)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.21\columnwidth}\raggedright
Pressure\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedright
\(\frac{M}{LT^2}\)\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
force/area\strut
\end{minipage} & \begin{minipage}[t]{0.28\columnwidth}\raggedright
newton/meter\(^2\), pascal (\(Pa\)), psi, atm\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.21\columnwidth}\raggedright
Electric Charge\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedright
\(I T\)\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
current \(\times\) time\strut
\end{minipage} & \begin{minipage}[t]{0.28\columnwidth}\raggedright
coulomb\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\hypertarget{activities-7}{%
\section{Activities}\label{activities-7}}

\hypertarget{find-the-dimension}{%
\subsection{Find the Dimension}\label{find-the-dimension}}

Find the dimension of the following quantities.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Momentum is the product of mass and velocity.
\item
  Jerk is the rate at which acceleration changes with respect to time.
\item
  Voltage is the work needed per unit charge to move a test charge between two points.
\end{enumerate}

\hypertarget{dimensionally-feasible}{%
\subsection{Dimensionally Feasible}\label{dimensionally-feasible}}

A formula is \textbf{dimensionally feasible} when the units for the two sides match.
Decide whether each of the following formulas is dimensionally feasible or infeasible.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \(s = vt + \frac{1}{2}at^2\) where \(s\) is displacement, \(v\) is velocity and \(a\) is acceleration.
\item
  \(P = E/A\) where \(P\) is pressure, \(E\) is energy and \(A\) is area.
\end{enumerate}

\hypertarget{geometric-formulas-for-a-cylinder}{%
\subsection{Geometric Formulas for a Cylinder}\label{geometric-formulas-for-a-cylinder}}

A student is trying to remember the formulas for the surface area \(A\) and the volume \(V\) of a cylinder of radius \(r\) and height \(h\). They come across the following two formulas:
\[ \pi r^2 h\]
and
\[ 2\pi r (r+h).\]
What are the dimensions for each of these formulas? Why does this tell you which one is \(A\) and which one is \(V\)?

\hypertarget{unit-conversions}{%
\subsection{Unit Conversions}\label{unit-conversions}}

Solve the following problems by multiplying by the appropriate unit conversions.
This \href{https://www.mustangps.org/Downloads/conversion_chart.pdf}{unit conversion chart} will be helpful, or you can use Google to find a particular conversion, for example just search for ``km to miles''.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  Convert a density of 3 g/mL into pounds/in\(^3\).
\item
  A car is going 35 miles per hour. How many feet per second is it traveling?
\item
  Sunlight deposits energy at a rate of 250 W/m\(^2\) on a 10 m\(^2\) garden. How much energy (in Joules) is deposited in a week? Note that 1 Watt is 1 Joule per second)
\end{enumerate}

\hypertarget{dimensional-analysis}{%
\chapter{Dimensional Analysis}\label{dimensional-analysis}}

\hypertarget{performing-a-dimensional-analysis}{%
\section{Performing a Dimensional Analysis}\label{performing-a-dimensional-analysis}}

Given independent variables \(x,y,z\) and dependent variable \(w\):

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Write down the hypothesized ``generalized product'' \(w = k x^a y^b z^c\)
\item
  Write \& simplify the dimensional version \([w] = [x]^a [y]^b [z]^c\)
\item
  List the dimensions of all quantities
\item
  Invoke dimensional compatibility to solve.
\item
  Rewrite your equation, marvel at your awesomeness!
\end{enumerate}

\hypertarget{activities-8}{%
\section{Activities}\label{activities-8}}

\hypertarget{vocal-chord-frequency}{%
\subsection{Vocal Chord Frequency}\label{vocal-chord-frequency}}

The frequency \(f\) of the sound of an organism's vocal chords depend on their length \(\ell\), tension \(s\) (a force) and mass density \(\mu\) (mass per unit length). Find a formula for the frequency \(f = f(\ell, s, \mu).\)

\hypertarget{mixer-power}{%
\subsection{Mixer Power}\label{mixer-power}}

A mixer with power \(P\) turns a mixer with wings of length \(D\) through a liquid of viscosity \(H\). Find a formula for the angular velocity \(A = A(P,D,H)\). Note that since angles are dimensionless, we have \([A] = 1/T\). The dimensions of viscosity are \([H] = M/(LT)\).

\hypertarget{velocity-of-an-ocean-wave}{%
\subsection{Velocity of an Ocean Wave}\label{velocity-of-an-ocean-wave}}

The velocity \(V\) of a large ocean wave depends upon the period \(P\), the acceleration of gravity \(g\), and the density \(\mu\) of the water. Find a formula for the velocity \(V=V(P,g,\mu)\).

\hypertarget{fermi-estimation}{%
\chapter{Fermi Estimation}\label{fermi-estimation}}

\hypertarget{working-fermi-problems}{%
\section{Working Fermi Problems}\label{working-fermi-problems}}

Here's a general game plan for Fermi Problems:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Write down what you know.
\item
  Estimate what you don't know!

  \begin{enumerate}
  \def\labelenumii{\alph{enumii}.}
  \tightlist
  \item
    Ask a series of smaller questions.
  \item
    Estimate the answers to the smaller questions.
  \end{enumerate}
\item
  Multiply and pay attention to units.
\end{enumerate}

\bigskip

Remember, \textbf{we're trying to estimate!}

\begin{itemize}
\tightlist
\item
  Do not obsess over details, but also,
\item
  Do not guess blindly.
\item
  Find a middle ground!
\end{itemize}

\textbf{Pro Tip \#1:} Identify smaller problems that you can estimate using your everyday common sense. For example, rather than estimating the height of of a building, I would estimate the height of one floor and estimate the number of floors, and then multiply.

\textbf{Pro Tip \#2:} When estimating, determine the order of magnitude (10, 100, 1000, etc). Use the geometric mean when you think the answer is somewhere in between. For example, if you think 1,000 is too small but that 10,000 is too big, then use 3,000.

\hypertarget{some-useful-data}{%
\section{Some Useful Data}\label{some-useful-data}}

The following approximate data may be useful in various Fermi problems. Each has been stated with one or two significant figures.

\begin{itemize}
\tightlist
\item
  Population of the world: \(7 \times 10^9\) people
\item
  Population of the United States: \(3 \times 10^8\) people
\item
  Average human life span worldwide (in years): 71 years\\
\item
  United States national debt (in dollars): \(\$1.8 \times 10^{13}\)
\item
  United States federal spending (in dollars per year): \(\$3.8 \times 10^{12}\).
\item
  Fraction of United States federal spending devoted to defense (as a decimal): 0.16
\item
  Fraction of United States federal spending devoted to Medicare/Medicaid (as a decimal): 0.27
\item
  Radius of earth (in km): 6400 km
\item
  Acceleration due to gravity on the surface of the Earth: \(9.8 \text{ m/}\text{s}^2\)
\item
  Fraction of Earth's surface covered by water (as a decimal): 0.7
\item
  Density of water at sea level: \(1 \text{ g}/\text{cm}^3\)
\end{itemize}

\hypertarget{activities-9}{%
\section{Activities}\label{activities-9}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  How many blades of grass are there on a football field?
\item
  How many babies are born each day? It will be helpful to know that (a) there are 7.8 billion people on the planet, (b) the average life expectancy is 73 years, and (c) the population doesn't change that much (relatively speakiing) in one year.
\item
  If all 7.8 billion humans in the world were crammed together, how much area would we require? Is this closer to the size of a city, a state, the U.S., or North America? Start by figuring out how many people would fit in 1 square meter. Then figure out how many square kilometers we would need.
\end{enumerate}

\hypertarget{part-computational-derivatives}{%
\part{Computational Derivatives}\label{part-computational-derivatives}}

\hypertarget{the-derivative}{%
\chapter{The Derivative}\label{the-derivative}}

\hypertarget{the-derivative-1}{%
\section{The Derivative}\label{the-derivative-1}}

The derivative is the \textbf{instantaneous rate of change}.

\begin{itemize}
\item
  The derivative of \(f(x)\) is denoted by \(f'(x)\) and by \(\displaystyle{\frac{df}{dx}}\).
\item
  We approximate this the derivative \(f'(x)\) at the point \(x=a\) with the formula
  \[
   f'(a)  \approx \frac{f(a+h) - f(a)}{h} 
  \]
  where \(h\) is a \textbf{very, very small number}.
\item
  The \textbf{derivative} measures the \textbf{sensitivity} of outputs to a small change in input.
  \[
  \text{the derivative} \, \approx \, \frac{\text{change in output}}{\text{change in input}} \, = \, \frac{\Delta y}{\Delta x}
  \]
\item
  The \textbf{derivative of a function} \(f\) at a point \(a\) is the slope of the tangent line at \(x=a\).
\item
  \textbf{Economics.} Given a cost function \(C(x)\), the \textbf{marginal cost} at \(x=a\) is the cost of producing one additional unit of a good. The formula is for the marginal cost at \(x=a\) is \(C(a+1)-C(a)\).
\item
  \textbf{Physics.} Given a displacement function \(s(t)\), the velocity is \(v(t) = s'(t)\), and the acceleration is \(a(t)=v'(t)\).
\end{itemize}

\hypertarget{activities-10}{%
\section{Activities}\label{activities-10}}

\hypertarget{studying}{%
\subsection{Studying}\label{studying}}

Suppose that spending 3 extra hours on studying increases our percent grade on an exam by 14 percent.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Calculate the derivative, give the units, and give an interpretation of the number you get.
\item
  Is this rate of change constant? Explain.
\end{enumerate}

\hypertarget{marginal-cost}{%
\subsection{Marginal Cost}\label{marginal-cost}}

Economists use the term ``marginal cost'' for the derivative of the cost of production. Here is the definition:

\bigskip

The \textbf{marginal cost} is the cost to produce 1 additional good.

\bigskip

Suppose that it costs \$250,000 to produce 1000 iPhones.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  If it costs \$250,440 to produce 1002 iPhones, what's the marginal cost of 1 iPhone?
\item
  Using the marginal cost from part 1, estimate how much it will cost to produce 1030 iPhones.
\end{enumerate}

\hypertarget{farmland-in-the-united-states}{%
\subsection{Farmland in the United States}\label{farmland-in-the-united-states}}

The total acreage of farmland has been shrinking in the United States since 1980.

\begin{longtable}[]{@{}llllll@{}}
\toprule
Year & 1980 & 1985 & 1990 & 1995 & 2000\tabularnewline
\midrule
\endhead
Farmland (millions of acres) & 1039 & 1012 & 987 & 963 & 945\tabularnewline
\bottomrule
\end{longtable}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Let \(F(t)\) denote the amount of farmland at a time \(t\). Use the data to estimate \(F'(1995)\), the derivative at \(t=1995\).
\item
  Did you use 1990 or 2000 as your estmation point? Did it matter? What does that mean?
\item
  You got a negative number for \(F'(1995)\). Does that make sense with the situation? Why?
\item
  Give an example of a year that, if you had the data for it, would better help us estimate \(F'(1995)\). Why?
\end{enumerate}

\hypertarget{a-moving-particle}{%
\subsection{A Moving Particle}\label{a-moving-particle}}

A particle's position over time is given by the formula
\[
s(t)=2+3\sin(4t)+1.2t^2
\]

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Find the velocity at \(t=1\) and \(t=2\) numerically (using small subintervals). Remember that the velocity is the derivative of the position.
\item
  Use desmos to graph the position curve \(s(t)\) and the tangent lines at both \(t=1\) and \(t=2\).
\end{enumerate}

\hypertarget{the-second-derivative}{%
\chapter{The Second Derivative}\label{the-second-derivative}}

\hypertarget{activities-11}{%
\section{Activities}\label{activities-11}}

\hypertarget{estimating-the-first-and-second-derivatives-from-a-graph}{%
\subsection{Estimating the first and second derivatives from a graph}\label{estimating-the-first-and-second-derivatives-from-a-graph}}

Here is a plot of the function \(f(x)\).
\includegraphics{_bookdown_files/math135_handbook_files/figure-latex/unnamed-chunk-86-1.pdf}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Estimate the intervals on which the derivative \(f'(x)\) is positive and the intervals on which the derivative \(f'(x)\) is negative
\item
  Estimate the intervals on which the second derivative \(f''(x)\) is positive and the intervals on which the second derivative \(f''(x)\) is negative
\end{enumerate}

\hypertarget{function-matching}{%
\subsection{Function Matching}\label{function-matching}}

Three curves \(f(x), g(x), h(x)\) are plotted below. These curves are actually a function, its derivative, and its second derivative. Which is which? How do you know?

\includegraphics[width=0.75\textwidth,height=\textheight]{images/deriv-higher.png}

\hypertarget{a-plot-of-velocity}{%
\subsection{A Plot of Velocity}\label{a-plot-of-velocity}}

Recall that displacement \(x(t)\), velocity \(v(t)\) and acceleration \(a(t)\) are related by the equations

\[  v = \frac{\partial x}{\partial t} \quad \mbox{and} \quad a = \frac{\partial v}{\partial t} = \frac{\partial^2 x}{\partial t^2}.\]
Here is a plot of \textbf{velocity} \(v(t)\) of an object.

\includegraphics{_bookdown_files/math135_handbook_files/figure-latex/unnamed-chunk-87-1.pdf}

Identify the time interval(s) where:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  The object has positive acceleration.
\item
  The position of the object is increasing.
\end{enumerate}

\hypertarget{characterize-the-derivatives}{%
\subsection{Characterize the Derivatives}\label{characterize-the-derivatives}}

Each of the scenarios below describes a quantity that is changing over time. For each one, (a) determine whether the first derivative is positive, negative or zero and (b) determine whether the second derivative is positive, negative or zero.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  The number of views of a video that is going viral.
\item
  The altitude of a bird that is about to have a gentle landing on the ground.
\item
  The location of a car that is cruising at the speed limit on a straight highway.
\end{enumerate}

\hypertarget{partial-derivatives}{%
\chapter{Partial Derivatives}\label{partial-derivatives}}

\hypertarget{activities-12}{%
\section{Activities}\label{activities-12}}

\hypertarget{estimating-from-data}{%
\subsection{Estimating From Data}\label{estimating-from-data}}

The maximum duration of a scuba dive \(T(V,D)\) (in minutes) depends on the volume \(V\) of air (at sea-level pressure) in the tank and the depth \(D\) (in feet) of the dive.
The following table shows the estimated dive times for various combinations of air volume and dive depth.

Dive Time (minutes)~

~Air Volume

20~ft3

40 ft3

60 ft3

80 ft3

Depth

20 ft

12.5

25.0

37.5

50.0

40 ft

9.0

18.0

27.0

36.0

60 ft

7.1

14.2

21.3

28.4

80 ft

5.8

11.6

17.4

23.2

Use this table to estimate the derivatives
\(\displaystyle{\frac{\partial T}{\partial V}}\) and \(\displaystyle{\frac{\partial T}{\partial D}}\) at the point \((V=60, T=40)\). Give units for each of these derivatives and then interpret what these numbers mean.

\hypertarget{estimating-from-a-contour-plot}{%
\subsection{Estimating From a Contour Plot}\label{estimating-from-a-contour-plot}}

The production function \(F(L,K)\) for a factory gives the number of units produced by labor \(L\) and capital \(K\) (both measured in dollars). This production function is given by
\[
F(L,K) = 10 L^{2/7}K^{5/7}.
\]
Here is a contour plot of the production function.

\includegraphics{_bookdown_files/math135_handbook_files/figure-latex/unnamed-chunk-90-1.pdf}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Estimate the production output for \(L=400\) and \(K=600\).
\item
  Estimate the partial derivative \(\displaystyle{\frac{\partial F}{\partial L}}\) at \((400,600)\).
\item
  Estimate the partial derivative \(\displaystyle{\frac{\partial F}{\partial K}}\) at \((400,600)\).
\end{enumerate}

\hypertarget{estimating-using-desmos}{%
\subsection{Estimating Using Desmos}\label{estimating-using-desmos}}

Use desmos to define the prodution function \(F(L,K) = L^{2/7} K^{5/7}\) from the previous problem and to answer the analogous questions

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Calculate the production outpuut \(F(400,600)\).
\item
  Estimate the partial derivative \(\displaystyle{\frac{\partial F}{\partial L}}\) at \((400,600)\). Your answer must be correct to two decimal places.
\item
  Estimate the partial derivative \(\displaystyle{\frac{\partial F}{\partial K}}\) at \((400,600)\).
  Your answer must be correct to two decimal places.
\end{enumerate}

Compare your three answers to the estimates from the contour plot in the previous problem.

\hypertarget{local-linear-approximation}{%
\chapter{Local Linear Approximation}\label{local-linear-approximation}}

The linearization of \(f(x)\) at \(x=a\) is
\[
L_a(x) = f(a) + f'(a) (x-a).
\]

\hypertarget{activities-13}{%
\section{Activities}\label{activities-13}}

\hypertarget{estimating-sugar-solution-temperature}{%
\subsection{Estimating Sugar Solution Temperature}\label{estimating-sugar-solution-temperature}}

We are boiling a sugar solution to make salt water taffy. When we start, the temperature of the solution is \(80^\circ\)F, after 5 minutes it's \(115^\circ\)F, and after 10 minutes it's \(165^\circ\)F.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Estimate the temperature after 17 minutes.
\item
  The sugar solution needs to reach \(289^\circ\)F to be the consistancy of taffy. Estimate when this will happen.
\end{enumerate}

\hypertarget{comparing-linearizations}{%
\subsection{Comparing Linearizations}\label{comparing-linearizations}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Draw two (nonlinear) functions \(f(x)\) and \(g(x)\) and their linearizations at \(x=1\). One function should be ``well estimated'' by the linearization around \(x=1\) and the other should be ``poorly estimated'' by the linearization around \(x=1\).
\item
  What feature(s) of the curve \(y=f(x)\) result in a good approximation?
\item
  What feature(s) of the curve \(y=g(x)\) result in a bad approximation?
\end{enumerate}

\hypertarget{estimating-a-function}{%
\subsection{Estimating a Function}\label{estimating-a-function}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  Find the linearization \(L_2(x)\) the function \(g(t)=t^3+e^t-4\).

  \begin{itemize}
  \tightlist
  \item
    Remember that \(L_2(x)\) means ``the local linear approximation at \(x=2\).''\\
  \item
    You will need to use desmos to approximate \(f'(2)\).
  \end{itemize}
\item
  Use your formula for \(L_2(x)\) to estimate \(g(2.1)\), \(g(1.98)\), \(g(3)\) and \(g(0.7)\).
\item
  Check your estimations with the original function.
\item
  What do you notice about your approximations as you get further from the spot where you built the linearization?
\end{enumerate}

\hypertarget{estimating-the-windchill}{%
\subsection{Estimating the Windchill}\label{estimating-the-windchill}}

We've talked about windchill \(w(t,v)\) as a function of temperature \(t\) and wind speed \(v\). Here is the table that we've used

\includegraphics[width=1\textwidth,height=\textheight]{images/wind-chill.png}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  The perceived temperature when \(t=-10 ^\circ\)F and \(v=40\) mph is \(w(-10,40)=-43\). I have used desmos to estimate that
  \[
  w_t(-10,-40) = 1.39, \qquad w_v(-10,40)=0.28.
  \]
  Use these values to find the linearization \(L_{(-10,40)}(t,v)\) at the point \((-10,40)\).
\item
  Use your linearization (and desmos!) to estimate the four windchill values \(w(-5,40)\), \(w(-15,40)\), \(w(-10,45)\) and \(w(-10,35)\). Are your estimates close to the actual values?
\item
  Find the linearization of \(w(t,v)\) at \(t=-10\) and \(v=40\) using the
  the partial derivatives of the formula \(w(t,v) = 35.74+0.6215 t-35.75 v^{0.16}+0.4275 t \, v^{0.16}\). Here is a \href{https://www.desmos.com/calculator/dvuhpknthj}{link to my desmos calculator for the partial derivatives of this function.}
\end{enumerate}

\hypertarget{unit-3-summary}{%
\chapter{Unit 3 Summary}\label{unit-3-summary}}

\hypertarget{the-derivative-2}{%
\section{The Derivative}\label{the-derivative-2}}

I can\ldots{}

\begin{itemize}
\tightlist
\item
  Define what a derivative is.
\item
  Interpret the derivative \(f'(x)\) as

  \begin{itemize}
  \tightlist
  \item
    a rate of change
  \item
    a measure of the sensitivity of output to changes in input
  \item
    the slope of a tangent line.
  \end{itemize}
\item
  Estimate the derivative using a table of data.
\item
  Estimate the derivatives from the plot of a function and its tangent line.
\item
  Estimate the derivative \(f'(x)\) at \(x=a\) using the average rate of change.
  \[
  f'(a) = \frac{f(a+h)-f(a)}{h}
  \]
  where \(h\) is a very small number
\item
  Use desmos to find an approximation of the derivative of a function to a desired accuracy.
\item
  Use the derivative to determine whether a function is increasing or decreasing.
\item
  Define marginal cost.
\item
  Calculate the marginal cost of \(C(x)\) at \(x=a\) using the formula \(C(a+1)-C(a)\)
\item
  Explain why marginal cost is an example of an approximate derivative
\item
  Explain how the derivative connects displacement, velocity and acceleration.
\end{itemize}

\hypertarget{the-second-derivative-1}{%
\section{The Second Derivative}\label{the-second-derivative-1}}

I can\ldots{}

\begin{itemize}
\tightlist
\item
  Give the definition of the \(k\)th derivative
  \(\displaystyle{\frac{d^kf}{dx^k} = f^{(k)}(x)}.\)
\item
  Explain why acceleration \(a(t)\) is the second derivative of displacement \(s(t)\). That is, \(a(t) = s''(t).\)
\item
  Use the second derivative to determine the concavity of a function.
\end{itemize}

\hypertarget{partial-derivatives-1}{%
\section{Partial Derivatives}\label{partial-derivatives-1}}

\begin{itemize}
\tightlist
\item
  Define what a partial derivative is.
\item
  Explain the difference between \(\displaystyle{f_x = \frac{df}{dx}}\) and \(\displaystyle{f_y = \frac{df}{dy}}\)
\item
  Estimate the partial derivatives from a table of data
\item
  Estimate the partial derivatives from a contour plot.
\item
  Use desmos to approximate the partial derivatives using
  \[
  \frac{\partial f}{\partial x} \approx \frac{f(x+h,y) - f(x,y)}{h} \quad \mbox{and} \quad \frac{\partial f}{\partial y} \approx \frac{f(x,y+h) - f(x,y)}{h}
  \]
  where \(h\) is a very, very small number.
\end{itemize}

\hypertarget{local-linear-approximation-1}{%
\section{Local Linear Approximation}\label{local-linear-approximation-1}}

I can\ldots{}

\begin{itemize}
\tightlist
\item
  Create the linearization \(L_a(x)\) for function \(f(x)\) at \(x=a\) using the formula
  \[
  L_a(x) = f(a) + f'(a) (x-a).
  \]
\item
  Approximate \(f(x)\) using the linearization \(L_a(x)\).
\item
  Create the linearization \(L_{(a,b)}(x,y)\) for function \(f(x,y)\) at point \((a,b)\) using the formula
  \[
  L_{(a,b)}(x,y) = f(a,b) + f_x(a,b) (x-a) + f_y(a,b) (y-b).
  \]
\item
  Approximate \(f(x,y)\) near the point \((x,y)\) using the linearization \(L_{(a,b)}(x)\).
\end{itemize}

\hypertarget{part-symbolic-derivatives}{%
\part{Symbolic Derivatives}\label{part-symbolic-derivatives}}

\hypertarget{rules-of-differentiation}{%
\chapter{Rules of Differentiation}\label{rules-of-differentiation}}

\hypertarget{derivatives-of-familiar-functions}{%
\section{Derivatives of Familiar Functions}\label{derivatives-of-familiar-functions}}

\hypertarget{constant-rule}{%
\subsection{Constant Rule}\label{constant-rule}}

The derivative of a constant is 0.
\[\frac{d}{dx}(c)= 0\]

\hypertarget{linear-function-rule}{%
\subsection{Linear Function Rule}\label{linear-function-rule}}

If \(f(x)=mx+b\), then the derivative is the slope \(m\).
\[\frac{d}{dx}(mx+b)= m\]

\hypertarget{power-rule}{%
\subsection{Power Rule}\label{power-rule}}

\[\frac{d}{dx}(x^n)=n x^{n-1}\]

\hypertarget{trig-rules}{%
\subsection{Trig Rules}\label{trig-rules}}

\[\frac{d}{dx}\sin(x)=\cos(x)\]
and
\[\frac{d}{dx}\cos(x)=-\sin(x)\]

\hypertarget{exponential-rules}{%
\subsection{Exponential Rules}\label{exponential-rules}}

\[\frac{d}{dx}(e^x)=e^x\]
and for any positive number \(a >0\),
\[\frac{d}{dx}(a^x)=(\ln a)a^x\]

\hypertarget{logarithmic-rules}{%
\subsection{Logarithmic Rules}\label{logarithmic-rules}}

\[\frac{d}{dx}(\ln (x))=\frac{1}{x}\]
and for any positive number \(a >0\),
\[\frac{d}{dx}(\log_a x)= \frac{1}{\ln (a)} \cdot \frac{1}{x}\]

\hypertarget{arithmetic-rules-for-derivatives}{%
\section{Arithmetic Rules for Derivatives}\label{arithmetic-rules-for-derivatives}}

\hypertarget{constant-multiple-rule}{%
\subsection{Constant Multiple Rule}\label{constant-multiple-rule}}

If \(c\) is a constant, then
\[\frac{d}{dx}(cf(x))=c\frac{d}{dx}f(x)=cf'(x)\]

\hypertarget{sum-and-difference-rules}{%
\subsection{Sum and Difference Rules}\label{sum-and-difference-rules}}

\[\frac{d}{dx}(f(x)+g(x))=\frac{d}{dx}f(x)+\frac{d}{dx}g(x)=f'(x)+g'(x)\]
and
\[\frac{d}{dx}(f(x)-g(x))=\frac{d}{dx}f(x)-\frac{d}{dx}g(x)=f'(x)-g'(x)\]

\hypertarget{rules-for-combinations-of-functions}{%
\section{Rules for Combinations of Functions}\label{rules-for-combinations-of-functions}}

\hypertarget{product-rule}{%
\subsection{Product Rule}\label{product-rule}}

If \(f(x)\) and \(g(x)\) are functions then
\[(fg)'=f'g+fg' \phantom{hihi} \text{ or } \phantom{hihi}(1st \cdot 2nd )'=D1st \cdot 2nd + 1st \cdot D2nd\]

\hypertarget{quotient-rule}{%
\subsection{Quotient Rule}\label{quotient-rule}}

If \(f(x)\) and \(g(x)\) are functions then
\[\left(\frac{f}{g} \right ) '=\frac{gf'-fg'}{g^2} \phantom{hihi}\text{ or } \phantom{hihi}\left(\frac{hi}{lo} \right ) '=\frac{loDhi-hiDlo}{lo^2}\]

\hypertarget{chain-rule}{%
\subsection{Chain Rule}\label{chain-rule}}

If \(y=f(t)\) and \(t=g(x)\) are functions, then the derivative of \(y=f(g(x))\) is given by
\[\frac{dy}{dx}=\frac{dy}{dt}\frac{dt}{dx} \phantom{hihi}\text{ or } \phantom{hihi}\frac{d}{dx}(f(g(x)))=f'(g(x))g'(x)=D(outside)D(inside)\]

\hypertarget{symbolic-differentiation}{%
\chapter{Symbolic Differentiation}\label{symbolic-differentiation}}

\hypertarget{activities-14}{%
\section{Activities}\label{activities-14}}

\hypertarget{basic-derivative-practice}{%
\subsection{Basic Derivative Practice}\label{basic-derivative-practice}}

Find the derivative for each of the following functions.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \(W(r) = r^3 + 5r - 12\)
\item
  \(f(x) = x^2 - 3\ln x\)
\item
  \(P(t) = 4t^2 + 7\sin t\)
\item
  \(f(x) = 1/x^2 + 5\sqrt{x} - 7\)
\item
  \(s(x) = 2e^{x} + x^2\)
\item
  \(h(\theta) = 1/\sqrt[3]{\theta}\)
\item
  \(b(t) = t^2 + 5\cos t\)
\end{enumerate}

\hypertarget{more-basic-derivative-practice}{%
\subsection{More Basic Derivative Practice}\label{more-basic-derivative-practice}}

Find the derivative for each of the following functions.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \(g(x) = -\frac{1}{2}\left(x^5 +2x -9 \right)\)
\item
  \(s(t) = 6t^{-2} + 3t^3 - 4t^{1/2}\)
\item
  \(q(x) = 3x - 2\cdot 4^x\)
\item
  \(y(x) = \sqrt{x}(x+1)\)
\item
  \(P(t) = 3000(1.02)^t\)
\item
  \(f(x) = 2^x + x^2 + 1\)
\item
  \(d(r) = Ae^{r} - Br^2 + C\)
\item
  \(s(t) = t^2 + 2\ln t\)
\item
  \(g(x) = 2x - \frac{1}{\sqrt[3]{x}} + 3^x - e\)
\item
  \(y(g) = 5\sin g - 5g + 4\)
\end{enumerate}

\hypertarget{product-rule-and-quotient-rule-practice}{%
\subsection{Product Rule and Quotient Rule Practice}\label{product-rule-and-quotient-rule-practice}}

Find the derivative for each of the following functions.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \(s(t)=(t^2+4)(5t-1)\)
\item
  \(y(x)=x^2\ln x\)
\item
  \(g(x)= \frac{25x^2}{e^x}\)
\item
  \(y(x)=x^2\cos x\)
\item
  \(h(t)=\frac{t+4}{t-4}\)
\end{enumerate}

\hypertarget{the-chain-rule}{%
\chapter{The Chain Rule}\label{the-chain-rule}}

\hypertarget{activities-15}{%
\section{Activities}\label{activities-15}}

\hypertarget{chain-rule-practice}{%
\subsection{Chain Rule Practice}\label{chain-rule-practice}}

Find the derivative for each of the following functions.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \(g(z)=(z^2+5)^3\)
\item
  \(g(m) = 200 e^{0.12m}\)
\item
  \(h(x) = e^{5x^2+1}\)
\item
  \(g(x) = \sqrt{1+x^3}\)
\item
  \(f(t) = \cos(2t^3+5t^2)\)
\item
  \(k(x) = \ln(4x^2)\)
\end{enumerate}

\hypertarget{more-chain-rule-practice}{%
\subsection{More Chain Rule Practice}\label{more-chain-rule-practice}}

Find the derivative for each of the following functions.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \(f(x)=\sin(2x)\)
\item
  \(P(t)=e^{2t}\)
\item
  \(y(x)=x e^{3x}\)
\item
  \(f(z)=\ln(z^2+1)\)
\item
  \(R(t)=(\sin t)^5\)
\item
  \(f(t)=\sin \sqrt{e^{t}+1}\)
\item
  \(g(y)=e^{2e^{y^3}}\)
\end{enumerate}

\hypertarget{conceptual-chain-rule-problems}{%
\subsection{Conceptual Chain Rule Problems}\label{conceptual-chain-rule-problems}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  The amount of gasoline \(G\), in gallons, used by a car is a function of the distance traveled \(s\), in miles. The distance traveled \(s\) depends on the time \(t\), in hours, spent driving.
  If the rate at which gas is consumed is 0.06 gallons per mile, and if the car is traveling at 40 miles per hour, how fast is the gas being used?
\item
  The radius of a circular oil spill is increasing at a rate of 2 meters per minute. Find how fast the area is changing when \(r=50\) meters
\end{enumerate}

\hypertarget{visual-chain-rule-problem}{%
\subsection{Visual Chain Rule Problem}\label{visual-chain-rule-problem}}

Below are the graphs of two functions, \(f(x)\) and \(g(x)\). Use the chain rule to calculate the derivatives specified below

\includegraphics[width=0.7\textwidth,height=\textheight]{images/TwoFunctions.jpg}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \((f(g(x))'\) when \(x=3\).
\item
  \((g(f(x)))'\) when \(x=1\).
\item
  \((g(f(x)))'\) when \(x=2\).
\end{enumerate}

\hypertarget{the-gradient}{%
\chapter{The Gradient}\label{the-gradient}}

\hypertarget{activities-16}{%
\section{Activities}\label{activities-16}}

\hypertarget{partial-derivative-practice}{%
\subsection{Partial Derivative Practice}\label{partial-derivative-practice}}

Find the partial derivatives \(f_x\) and \(f_y\) for each of these functions.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \(f(x,y) = x^5 + x^2y^3 + y^4\)
\item
  \(f(x,y) = e^x \sin(y) + \ln(y) \cos(x)\)
\item
  \(f(x,y) = \ln (x^2 - y^2)\)
\item
  \(f(x,y) = x^2 y^3 e^x \sin(y)\)
\end{enumerate}

\hypertarget{second-partial-derivative-practice}{%
\subsection{Second Partial Derivative Practice}\label{second-partial-derivative-practice}}

For each of these functions, find the second partial derivatives \(f_{xx}, f_{yy}, f_{xy}\) and \(f_{yx}\). Confirm that \(f_{xy} = f_{yx}\)

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \(f(x,y) = 7x^3 + \cos(4y)\)
\item
  \(f(x,y) = e^{2x+3y}\)
\end{enumerate}

\hypertarget{gradient-practice}{%
\subsection{Gradient Practice}\label{gradient-practice}}

Calculate the gradient \(\nabla f(x,y)\) for each of these functions

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \(f(x,y) = 8x^2y^4\)
\item
  \(\displaystyle{f(x,y) = \frac{x}{y}}\)
\item
  \(f(x,y) = \ln(xy)\)
\end{enumerate}

\hypertarget{gradient-on-a-contour-diagram}{%
\subsection{Gradient on a Contour Diagram}\label{gradient-on-a-contour-diagram}}

Here is a contour plot of \(f(x,y)\). At each of the three points indicated by \(*\), draw a vector in the direction of the gradient \(\nabla f\).

\includegraphics{_bookdown_files/math135_handbook_files/figure-latex/unnamed-chunk-92-1.pdf}

\hypertarget{gradient-and-the-direction-of-greatest-increase}{%
\subsection{Gradient and the Direction of Greatest Increase}\label{gradient-and-the-direction-of-greatest-increase}}

Let \(f(x,y) = 3x^2 - 4xy + y^2\).

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Find the gradient vector \(\nabla f(2,1)\) the at the point \((2,1)\).
\item
  Find the rate of change of \(f(x,y)\) at \((2,1)\) in the direction of greatest increase.
\end{enumerate}

\hypertarget{gradient-and-the-direction-of-greatest-increase-1}{%
\subsection{Gradient and the Direction of Greatest Increase}\label{gradient-and-the-direction-of-greatest-increase-1}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \(\nabla f(x,y) = \langle 6x - 4y, -4x + 2y \rangle\) so
  \(\nabla f(x,y) = \langle 12 - 4, -8 + 2 \rangle = \langle 8, -6 \rangle\).
\item
  \(\| \nabla f(2,1) \| = \sqrt{8^2 + (-6)^2} = \sqrt{64+36} = \sqrt{100} = 10.\)
\end{enumerate}

--\textgreater{}

\hypertarget{unit-4-summary}{%
\chapter{Unit 4 Summary}\label{unit-4-summary}}

\hypertarget{symbolic-derivatives}{%
\section{Symbolic Derivatives}\label{symbolic-derivatives}}

I can \ldots{}

\begin{itemize}
\tightlist
\item
  Find the derivative of \(x^n\), \(\sin(x)\), \(\cos(x)\), \(e^x\), \(a^x\), \(\ln(x)\), and \(\log_a(x)\).
\item
  Find the derivative \ldots{}

  \begin{itemize}
  \tightlist
  \item
    of the sum of function
  \item
    using the product rule
  \item
    using the quotient rule
  \item
    using the chain rule
  \end{itemize}
\item
  Explain why the derivative is not defined for a cusp point.
\item
  Solve a ``word problem'' about rates of change by using derivatives.
\end{itemize}

\hypertarget{partial-derivatives-2}{%
\section{Partial Derivatives}\label{partial-derivatives-2}}

I can \ldots{}

\begin{itemize}
\tightlist
\item
  Interpret the partial derivatives \(\frac{\partial f}{\partial x}\) and \(\frac{\partial f}{\partial y}\) as rates of change.
\item
  Find the partial derivatives of a function \(f(x,y)\) by holding one variable fixed and then applying the rules of differentiation.
\item
  Find the second partial derivatives \(f_{xx}, f_{xy}, f_{yx}, f_{yy}\).
\item
  Solve a ``word problem'' about rates of change of a multivariable function using partial derivatives.
\end{itemize}

\hypertarget{the-gradient-1}{%
\section{The Gradient}\label{the-gradient-1}}

I can \ldots{}

\begin{itemize}
\tightlist
\item
  Explain what a vector \(\langle a, b \rangle\) is, draw it as an arrrow, and find its magnitude \(\| \langle a, b \rangle \| = \sqrt{a^2+b^2}.\)
\item
  Find the gradient vector \(\nabla f(x,y) = \langle f_x, f_y \rangle\)
\item
  Evaluate the gradient vector at a point \((a,b)\)
\item
  Use the gradient to find the direction of greatest increase, and the magnitude of the gradient to find the rate of change (slope) in that direction
\item
  Draw a vector in the direction of greatest increase on a contour diagram.
\end{itemize}

\hypertarget{part-optimization}{%
\part{Optimization}\label{part-optimization}}

\hypertarget{d-optimization}{%
\chapter{1D Optimization}\label{d-optimization}}

\hypertarget{activities-17}{%
\section{Activities}\label{activities-17}}

\hypertarget{characterize-the-extrema}{%
\subsection{Characterize the Extrema}\label{characterize-the-extrema}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Each of the functions below is defined on \((-\infty, \infty)\). Find all the local extrema and global extrema.
\end{enumerate}

\includegraphics[width=1\textwidth,height=\textheight]{images/minmax-ex1.png}

image: \url{https://openstax.org/books/calculus-volume-1/pages/4-3-maxima-and-minima}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  Each of the functions below is defined on a finite interval. Find all the local extrema and global extrema.
\end{enumerate}

\includegraphics[width=1\textwidth,height=\textheight]{images/minmax-ex2.png}
image: \url{https://openstax.org/books/calculus-volume-1/pages/4-3-maxima-and-minima}

\hypertarget{first-derivative-test}{%
\subsection{First Derivative Test}\label{first-derivative-test}}

Find the critical point(s) of the following functions. Then use the first derivative test to determine whether it is a local minimum, a local maximum, or neither

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \(f(x) = x - e^x\)
\item
  \(g(x) = x + \sin(x)\) on \([0,2\pi]\)
\end{enumerate}

\hypertarget{second-derivative-test}{%
\subsection{Second Derivative Test}\label{second-derivative-test}}

The function \(f(x) = x^4-8 x^3+22 x^2-24 x\) has critical points at \(x=1\) and \(x=2\) and \(x=3\).

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Find \(f''(x)\).
\item
  Use the second derivative test to determine whether each of the critical points is a minimum or a maximum.
\end{enumerate}

\hypertarget{cupcake-store}{%
\subsection{Cupcake Store}\label{cupcake-store}}

A cupcake store finds that at a price of \$4.00, the demand is 400 cupcakes. For every \$.25 decrease in price, the demand increases by 20 cupcakes.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Define a function \(q(x)\) that gives the demand for cupcakes at a price of \(x\) dollars.
\item
  The revenue for a price of \(x\) dollars is \(r(x) = x \cdot q(x)\). Use your function from part (a) to find the price that maximizes revenue.
\end{enumerate}

Find the price and quantity that maximize the revenue.

\hypertarget{d-optimization-1}{%
\chapter{2D Optimization}\label{d-optimization-1}}

\hypertarget{summary}{%
\section{Summary}\label{summary}}

The \textbf{critical points} of \(f(x,y)\) are the points \((a,b)\) where both \(f_x(a,b)=0\) and \(f_y(a,b)=0\).

There are three ways to determine whether a critical point \((a,b)\) is a minimum, a maximum, or a saddle point.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  The second derivative test relies on the value
  \[
  D = f_{xx} f_{yy} - (f_{xy})^2.
  \]

  \begin{itemize}
  \tightlist
  \item
    If \(D > 0\) and \(f_{xx} > 0\) then \((a,b)\) is a local minimum.
  \item
    If \(D > 0\) and \(f_{xx} < 0\) then \((a,b)\) is a local maximum
  \item
    If \(D < 0\) then \((a,b)\) is a saddle point
  \item
    If \(D=0\) then the test fails
  \end{itemize}
\item
  Create a contour plot for \(f(x,y)\) on a very small neighborhood of \((a,b)\). Use the contours to figure out whether it is a local max, a local min, or a saddle point.
\item
  Find the values of \(f(a,b) - f(x,y)\) for points \((x,y)\) in a small circle around \((a,b)\).

  \begin{itemize}
  \tightlist
  \item
    If these values are ALL positive then \((a,b)\) is a local maximum
  \item
    If these values are ALL negative then \((a,b)\) is a local minimum
  \item
    If some values are positive and some values are negative, then \((a,b)\) is a saddle point.
  \end{itemize}
\end{enumerate}

Here is some R code that you can use to check values of \(f(x,y)\) in a small circle around a point \((a,b)\).

\begin{verbatim}
r = 0.1
theta = seq(0,2*pi,pi/10)
f(a,b) - f(a+r*cos(theta), b+r*sin(theta)) 
\end{verbatim}

\hypertarget{activities-18}{%
\section{Activities}\label{activities-18}}

\hypertarget{characterize-the-extrema-1}{%
\subsection{Characterize the Extrema}\label{characterize-the-extrema-1}}

Multiple 2D functions have been (contour) plotted below. For each, identify the critical points and determine if they are maximums, minimums, or saddle points.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{f =}\StringTok{ }\KeywordTok{makeFun}\NormalTok{(x}\OperatorTok{^}\DecValTok{2}\OperatorTok{+}\NormalTok{y}\OperatorTok{^}\DecValTok{2}\OperatorTok{+}\DecValTok{3}\OperatorTok{~}\NormalTok{x}\OperatorTok{&}\NormalTok{y)}
\KeywordTok{plotFun}\NormalTok{(}\KeywordTok{f}\NormalTok{(x,y)}\OperatorTok{~}\NormalTok{x}\OperatorTok{&}\NormalTok{y, }\DataTypeTok{xlim=}\KeywordTok{range}\NormalTok{(}\OperatorTok{-}\DecValTok{2}\NormalTok{,}\DecValTok{2}\NormalTok{), }\DataTypeTok{ylim=}\KeywordTok{range}\NormalTok{(}\OperatorTok{-}\DecValTok{2}\NormalTok{,}\DecValTok{2}\NormalTok{), }\DataTypeTok{filled=}\OtherTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{_bookdown_files/math135_handbook_files/figure-latex/unnamed-chunk-94-1} \end{center}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{f =}\StringTok{ }\KeywordTok{makeFun}\NormalTok{(}\OperatorTok{-}\NormalTok{x}\OperatorTok{*}\NormalTok{y}\OperatorTok{*}\KeywordTok{exp}\NormalTok{(}\OperatorTok{-}\NormalTok{x}\OperatorTok{^}\DecValTok{2}\OperatorTok{-}\NormalTok{y}\OperatorTok{^}\DecValTok{2}\NormalTok{)}\OperatorTok{~}\NormalTok{x}\OperatorTok{&}\NormalTok{y)}
\KeywordTok{plotFun}\NormalTok{(}\KeywordTok{f}\NormalTok{(x,y)}\OperatorTok{~}\NormalTok{x}\OperatorTok{&}\NormalTok{y, }\DataTypeTok{xlim=}\KeywordTok{range}\NormalTok{(}\OperatorTok{-}\FloatTok{1.5}\NormalTok{,}\FloatTok{1.5}\NormalTok{), }\DataTypeTok{ylim=}\KeywordTok{range}\NormalTok{(}\OperatorTok{-}\FloatTok{1.5}\NormalTok{,}\FloatTok{1.5}\NormalTok{), }\DataTypeTok{filled=}\OtherTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{_bookdown_files/math135_handbook_files/figure-latex/unnamed-chunk-95-1} \end{center}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{f =}\StringTok{ }\KeywordTok{makeFun}\NormalTok{(y}\OperatorTok{^}\DecValTok{2}\OperatorTok{-}\NormalTok{x}\OperatorTok{^}\DecValTok{2}\OperatorTok{~}\NormalTok{x}\OperatorTok{&}\NormalTok{y)}
\KeywordTok{plotFun}\NormalTok{(}\KeywordTok{f}\NormalTok{(x,y)}\OperatorTok{~}\NormalTok{x}\OperatorTok{&}\NormalTok{y, }\DataTypeTok{xlim=}\KeywordTok{range}\NormalTok{(}\OperatorTok{-}\DecValTok{2}\NormalTok{,}\DecValTok{2}\NormalTok{), }\DataTypeTok{ylim=}\KeywordTok{range}\NormalTok{(}\OperatorTok{-}\DecValTok{2}\NormalTok{,}\DecValTok{2}\NormalTok{), }\DataTypeTok{filled=}\OtherTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{_bookdown_files/math135_handbook_files/figure-latex/unnamed-chunk-96-1} \end{center}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{f =}\StringTok{ }\KeywordTok{makeFun}\NormalTok{(}\KeywordTok{cos}\NormalTok{(x)}\OperatorTok{*}\NormalTok{(x}\OperatorTok{^}\DecValTok{2}\OperatorTok{-}\NormalTok{y}\OperatorTok{^}\DecValTok{2}\NormalTok{)}\OperatorTok{~}\NormalTok{x}\OperatorTok{&}\NormalTok{y)}
\KeywordTok{plotFun}\NormalTok{(}\KeywordTok{f}\NormalTok{(x,y)}\OperatorTok{~}\NormalTok{x}\OperatorTok{&}\NormalTok{y, }\DataTypeTok{xlim=}\KeywordTok{range}\NormalTok{(}\OperatorTok{-}\FloatTok{1.5}\NormalTok{,}\FloatTok{1.5}\NormalTok{), }\DataTypeTok{ylim=}\KeywordTok{range}\NormalTok{(}\OperatorTok{-}\FloatTok{1.5}\NormalTok{,}\FloatTok{1.5}\NormalTok{), }\DataTypeTok{filled=}\OtherTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{_bookdown_files/math135_handbook_files/figure-latex/unnamed-chunk-97-1} \end{center}

\hypertarget{classifying-a-critical-point-using-a-small-circle-of-values}{%
\subsection{Classifying a critical point using a small circle of values}\label{classifying-a-critical-point-using-a-small-circle-of-values}}

The function \(f(x,y) =3x^2y + y^3 -3x^2-3y^2+3\) has four critical points:
\[
(0,0) \qquad (0,2) \qquad (1,1) \qquad (1,,-1).
\]
For each critical point \((a,b)\), evaluate \(f(a,b) - f(x,y)\) in a small circle centered at \((a,b)\) to determine whether it is a local minimum, a local maximum, or a saddle point

\hypertarget{the-2d-second-derivative-test}{%
\subsection{The 2D Second Derivative Test}\label{the-2d-second-derivative-test}}

The function \(f(x,y)=10 + x^3 + 8y^3 - 3xy\) has two critical points: \((0,0)\) and \((1/2,1/4)\).

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Use the second derivative test to classify each point as a local minimum, local maximum, or saddle point. For convenience, here are the second derivatives of \(f(x,y)\).
\end{enumerate}

\[
f_{xx} = 6x, \qquad f_{yy} = 48y, \qquad f_{xy} = -3.
\]

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  Confirm that your answer is correct by creating a contour plot on a very small neighborhood around each critical point.
\end{enumerate}

\hypertarget{classify-the-critical-points}{%
\subsection{Classify the Critical Points}\label{classify-the-critical-points}}

Find the critical points of \(f(x,y)=9-2x+4y-x^2-4y^2\). Then use any method that you like to classify each one as a local minimum, a local maximum or a saddle point.

\hypertarget{optimizing-flight-control}{%
\subsection{Optimizing Flight Control}\label{optimizing-flight-control}}

The range over which a flying drone can be guided is related to the atmospheric temperature and humidity. The range function is
\[
R(t,h)=27800-5t^2-6ht-3h^2+400t+300h
\]
What are the optimal atmospheric conditions?

\hypertarget{gradient-search-1}{%
\chapter{Gradient Search}\label{gradient-search-1}}

\hypertarget{gradient-search-example}{%
\section{Gradient Search Example}\label{gradient-search-example}}

Let's use gradient search to find the maximum of the function
\[
f(x,y) = - x^4 -  x^3 + 10 x y + 2y - 8 y^2 
\]
whose partial derivatives are
\[
\frac{\partial f}{\partial x} = -4 x^3 -3 x^2  + 10 y
\quad \mbox{and} \quad
\frac{\partial f}{\partial x} = 10 x + 2 - 16 y
\]

First, you define the partial derivatives and then choose your starting point \texttt{(newx,\ newy)}. In this case, we start at \texttt{(1,1)}.

\medskip

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{partialx =}\StringTok{ }\KeywordTok{makeFun}\NormalTok{( }\DecValTok{-4}\OperatorTok{*}\NormalTok{x}\OperatorTok{^}\DecValTok{3} \DecValTok{-3}\OperatorTok{*}\NormalTok{x}\OperatorTok{^}\DecValTok{2} \OperatorTok{+}\StringTok{ }\DecValTok{10}\OperatorTok{*}\NormalTok{y }\OperatorTok{~}\StringTok{ }\NormalTok{x}\OperatorTok{&}\NormalTok{y)}
\NormalTok{partialy =}\StringTok{ }\KeywordTok{makeFun}\NormalTok{(}\DecValTok{10}\OperatorTok{*}\NormalTok{x }\OperatorTok{+}\StringTok{ }\DecValTok{2} \OperatorTok{-}\StringTok{ }\DecValTok{16}\OperatorTok{*}\NormalTok{y }\OperatorTok{~}\StringTok{ }\NormalTok{x}\OperatorTok{&}\NormalTok{y)}
\NormalTok{newx =}\StringTok{ }\DecValTok{1}
\NormalTok{newy =}\StringTok{ }\DecValTok{1}
\end{Highlighting}
\end{Shaded}

\medskip

Next, you \textbf{repeatedly} run the following code block, which updates the current point by moving \texttt{0.1} times the gradient vector. This takes a small step in the uphill direction.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{newx =}\StringTok{ }\NormalTok{newx }\OperatorTok{+}\StringTok{ }\FloatTok{0.1}\OperatorTok{*}\KeywordTok{partialx}\NormalTok{(newx, newy)}
\NormalTok{newy =}\StringTok{ }\NormalTok{newy }\OperatorTok{+}\StringTok{ }\FloatTok{0.1}\OperatorTok{*}\KeywordTok{partialy}\NormalTok{(newx, newy)}
\CommentTok{# print new partial derivatives}
\KeywordTok{c}\NormalTok{(}\KeywordTok{partialx}\NormalTok{(newx, newy), }\KeywordTok{partialy}\NormalTok{(newx, newy))}
\CommentTok{# print new point}
\KeywordTok{c}\NormalTok{(newx, newy)}
\end{Highlighting}
\end{Shaded}

Repeatedly run this code block until the partial derivatives are essentially zero (at least two zeros after the decimal point). Congrats! You have found your local maximum.

You will end at the point \texttt{(1.04,0.77)}. But note that starting at another initial point might take you to a different local maximum!

\hypertarget{activities-19}{%
\section{Activities}\label{activities-19}}

\hypertarget{finding-a-local-minimum}{%
\subsection{Finding a Local Minimum}\label{finding-a-local-minimum}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  How should I change to the code if I want to find a \textbf{local minimum} instead of a local maximum? (Hint: we want to take a small step downhill.)
\item
  Use gradient search to find a \textbf{local minimum} of
  \[f(x,y) = x^2 + 2 x y + 3 x + 4 y + 5 y^2.\]
\end{enumerate}

\hypertarget{constrained-2d-optimization}{%
\chapter{Constrained 2D Optimization}\label{constrained-2d-optimization}}

\hypertarget{creating-a-contour-plot-for-2d-optimization}{%
\section{Creating a Contour Plot for 2D Optimization}\label{creating-a-contour-plot-for-2d-optimization}}

Here is some example code to create a plot of an objective function \(P(x,y) = x^{0.2} y^{0.8}\) and a constraint function \(Q(x,y)=4x + 3y=200\).

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{P =}\StringTok{ }\KeywordTok{makeFun}\NormalTok{( x}\OperatorTok{^}\NormalTok{(}\FloatTok{0.2}\NormalTok{) }\OperatorTok{*}\StringTok{ }\NormalTok{y}\OperatorTok{^}\NormalTok{(}\FloatTok{0.8}\NormalTok{) }\OperatorTok{~}\StringTok{ }\NormalTok{x}\OperatorTok{&}\NormalTok{y)}
\NormalTok{Q =}\StringTok{ }\KeywordTok{makeFun}\NormalTok{( }\DecValTok{4}\OperatorTok{*}\NormalTok{x }\OperatorTok{+}\StringTok{ }\DecValTok{3}\OperatorTok{*}\NormalTok{y }\OperatorTok{~}\StringTok{ }\NormalTok{x}\OperatorTok{&}\NormalTok{y)}

\KeywordTok{plotFun}\NormalTok{(}\KeywordTok{P}\NormalTok{(x,y)}\OperatorTok{~}\NormalTok{x}\OperatorTok{&}\NormalTok{y, }\DataTypeTok{xlim=}\KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{40}\NormalTok{), }\DataTypeTok{ylim=}\KeywordTok{c}\NormalTok{(}\DecValTok{20}\NormalTok{,}\DecValTok{60}\NormalTok{), }\DataTypeTok{filled=}\OtherTok{FALSE}\NormalTok{, }\DataTypeTok{levels=}\KeywordTok{seq}\NormalTok{(}\DecValTok{20}\NormalTok{,}\DecValTok{50}\NormalTok{,}\DecValTok{4}\NormalTok{))}

\KeywordTok{plotFun}\NormalTok{(}\KeywordTok{Q}\NormalTok{(x,y)}\OperatorTok{~}\NormalTok{x}\OperatorTok{&}\NormalTok{y, }\DataTypeTok{add=}\OtherTok{TRUE}\NormalTok{, }\DataTypeTok{filled=}\OtherTok{FALSE}\NormalTok{, }\DataTypeTok{levels=}\DecValTok{200}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\hypertarget{activities-20}{%
\section{Activities}\label{activities-20}}

\hypertarget{constrained-production}{%
\subsection{Constrained Production}\label{constrained-production}}

A company produces \(P(x,y) = 100 x^{4/11} y^{7/11}\) units of its product from raw materials \(x\) and \(y\). The cost of each unit of \(x\) is \$5 and the cost of each unit of \(y\) is \$4.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  Find the maximal output for a budget of \$500, along with how much input \(x\) and \(y\) is used to create them. (Hint: plot your contour diagram on the domain \(0 \leq x \leq 100\) and \(0 \leq y \leq 100\). Start with the \textbf{default} contours by removing the \texttt{levels} input.)
\item
  What is the maximal output if the unit cost of \(x\) increases to \$7? How much of inputs \(x\) and \(y\) are used?
\item
  What is the maximal output if the unit cost of \(x\) returns to \$5 and the budget is decreased to \$300? How much of inputs \(x\) and \(y\) are used?
\end{enumerate}

\hypertarget{constrained-optimization-on-a-circle}{%
\subsection{Constrained Optimization on a Circle}\label{constrained-optimization-on-a-circle}}

Below is a plot of an objective function \(f(x,y)\) in red, and its constraint function \(g(x,y)=9\) in blue.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Estimate the \textbf{minimum} value of \(f(x,y)\) constrained to \(g(x,y)=9\). What point achieves this minimum?
\item
  Estimate the \textbf{maximum} value of \(f(x,y)\) constrained to \(g(x,y)=9\). What point achieves this maximum?
\end{enumerate}

\includegraphics[width=0.5\textwidth,height=\textheight]{images/constrained-circle.png}

\hypertarget{estimating-the-lagrange-multiplier}{%
\subsection{Estimating the Lagrange Multiplier}\label{estimating-the-lagrange-multiplier}}

Below is a plot of an objective function \(f(x,y)\) in red, and its constraint function \(g(x,y)\) for various budgets in blue (in thousands of dollars).

\includegraphics[width=0.5\textwidth,height=\textheight]{images/cobb-douglas2.png}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Estimate the point \((x,y)\) that maximizes production for a budget of \(g(x,y)=15\). What is the production level?
\item
  Estimate the point \((x,y)\) that maximizes production for a budget of \(g(x,y)=20\). What is the production level?
\item
  What is the value of the Lagrange multiplier for the budget \(g(x,y)=15\)? What are the units? What does this number mean?
\item
  What price would make this increase useful to the company? (Hint: the units for your answer are ``dollars per unit produced.'')
\end{enumerate}

The maximum output for our budget occurs where the \(Q(x,y)=500\) constraint is tangent to a contour of \(P(x,y)\). This occurs at (approximately) the point \((38,78)\) and we estimate that the maximum production is \(P(38,78)=60\).

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  We need to make a new plot using an updated constraint function.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{P =}\StringTok{ }\KeywordTok{makeFun}\NormalTok{( x}\OperatorTok{^}\NormalTok{(}\DecValTok{4}\OperatorTok{/}\DecValTok{11}\NormalTok{) }\OperatorTok{*}\StringTok{ }\NormalTok{y}\OperatorTok{^}\NormalTok{(}\DecValTok{7}\OperatorTok{/}\DecValTok{11}\NormalTok{) }\OperatorTok{~}\StringTok{ }\NormalTok{x}\OperatorTok{&}\NormalTok{y)}
\NormalTok{Q =}\StringTok{ }\KeywordTok{makeFun}\NormalTok{( }\DecValTok{7}\OperatorTok{*}\NormalTok{x }\OperatorTok{+}\StringTok{ }\DecValTok{4}\OperatorTok{*}\NormalTok{y }\OperatorTok{~}\StringTok{ }\NormalTok{x}\OperatorTok{&}\NormalTok{y)}

\KeywordTok{plotFun}\NormalTok{(}\KeywordTok{P}\NormalTok{(x,y)}\OperatorTok{~}\NormalTok{x}\OperatorTok{&}\NormalTok{y, }\DataTypeTok{xlim=}\KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{100}\NormalTok{), }\DataTypeTok{ylim=}\KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{100}\NormalTok{), }\DataTypeTok{filled=}\OtherTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plotFun}\NormalTok{(}\KeywordTok{Q}\NormalTok{(x,y)}\OperatorTok{~}\NormalTok{x}\OperatorTok{&}\NormalTok{y, }\DataTypeTok{add=}\OtherTok{TRUE}\NormalTok{, }\DataTypeTok{filled=}\OtherTok{FALSE}\NormalTok{, }\DataTypeTok{levels=}\DecValTok{500}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{_bookdown_files/math135_handbook_files/figure-latex/unnamed-chunk-114-1.pdf}

Now, the constraint isn't tangent to any of the shown contours, but it IS tangent to a contour that we haven't drawn! That point is somewhere around (25, 80), and the optimal productions probably around 52 or so. Let's make another plot on a smaller domain and pick some contours to draw.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plotFun}\NormalTok{(}\KeywordTok{P}\NormalTok{(x,y)}\OperatorTok{~}\NormalTok{x}\OperatorTok{&}\NormalTok{y, }\DataTypeTok{xlim=}\KeywordTok{c}\NormalTok{(}\DecValTok{20}\NormalTok{,}\DecValTok{40}\NormalTok{), }\DataTypeTok{ylim=}\KeywordTok{c}\NormalTok{(}\DecValTok{60}\NormalTok{,}\DecValTok{100}\NormalTok{), }\DataTypeTok{filled=}\OtherTok{FALSE}\NormalTok{, }\DataTypeTok{levels=}\KeywordTok{seq}\NormalTok{(}\DecValTok{47}\NormalTok{,}\DecValTok{66}\NormalTok{,}\DecValTok{3}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plotFun}\NormalTok{(}\KeywordTok{Q}\NormalTok{(x,y)}\OperatorTok{~}\NormalTok{x}\OperatorTok{&}\NormalTok{y, }\DataTypeTok{add=}\OtherTok{TRUE}\NormalTok{, }\DataTypeTok{filled=}\OtherTok{FALSE}\NormalTok{, }\DataTypeTok{levels=}\DecValTok{500}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{_bookdown_files/math135_handbook_files/figure-latex/unnamed-chunk-116-1.pdf}

After some experimentation, I realized that \(P(x,y)=53\) is the contour that is tangent \$ Q(x,y)=500\$. So the optimal point is \((26,80)\) and the optimal output is 53.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  Now we return to the original constraint function, but decrease the budget to \(300\).
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{P =}\StringTok{ }\KeywordTok{makeFun}\NormalTok{( x}\OperatorTok{^}\NormalTok{(}\DecValTok{4}\OperatorTok{/}\DecValTok{11}\NormalTok{) }\OperatorTok{*}\StringTok{ }\NormalTok{y}\OperatorTok{^}\NormalTok{(}\DecValTok{7}\OperatorTok{/}\DecValTok{11}\NormalTok{) }\OperatorTok{~}\StringTok{ }\NormalTok{x}\OperatorTok{&}\NormalTok{y)}
\NormalTok{Q =}\StringTok{ }\KeywordTok{makeFun}\NormalTok{( }\DecValTok{5}\OperatorTok{*}\NormalTok{x }\OperatorTok{+}\StringTok{ }\DecValTok{4}\OperatorTok{*}\NormalTok{y }\OperatorTok{~}\StringTok{ }\NormalTok{x}\OperatorTok{&}\NormalTok{y)}

\KeywordTok{plotFun}\NormalTok{(}\KeywordTok{P}\NormalTok{(x,y)}\OperatorTok{~}\NormalTok{x}\OperatorTok{&}\NormalTok{y, }\DataTypeTok{xlim=}\KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{100}\NormalTok{), }\DataTypeTok{ylim=}\KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{100}\NormalTok{), }\DataTypeTok{filled=}\OtherTok{FALSE}\NormalTok{, }\DataTypeTok{levels=}\KeywordTok{seq}\NormalTok{(}\DecValTok{15}\NormalTok{,}\DecValTok{85}\NormalTok{,}\DecValTok{10}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plotFun}\NormalTok{(}\KeywordTok{Q}\NormalTok{(x,y)}\OperatorTok{~}\NormalTok{x}\OperatorTok{&}\NormalTok{y, }\DataTypeTok{add=}\OtherTok{TRUE}\NormalTok{, }\DataTypeTok{filled=}\OtherTok{FALSE}\NormalTok{, }\DataTypeTok{levels=}\DecValTok{300}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{_bookdown_files/math135_handbook_files/figure-latex/unnamed-chunk-118-1.pdf}

The optimal point is at \((21,40)\) and the optimal production is approximately \(f(21,40)=35\). (This is a slight under-estimate, but it's pretty close.)

\hypertarget{constrained-optimization-on-a-circle-1}{%
\subsection{Constrained Optimization on a Circle}\label{constrained-optimization-on-a-circle-1}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  The minimum is approximately \(f(1.5, 1.5) = 20\).
\item
  The maximum is approximately \(f(4.5, 4.5) = 210\).
\end{enumerate}

\hypertarget{estimating-the-lagrange-multiplier-1}{%
\subsection{Estimating the Lagrange Multiplier}\label{estimating-the-lagrange-multiplier-1}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  For a budget of 15, the maximal production is \(f(25,18)=250\).
\item
  For a budget of 20, the maximal production is \(f(32,26)=360\).
\item
  The Lagrange multiplier is
  \[
  \lambda = \frac{\triangle \mbox{production}}{\triangle \mbox{constraint}} \approx \frac{360-250}{20-15}=\frac{110}{5}=22  \frac{\mbox{units}}{\mbox{dollar}}
  \]
  So if we increase our budget by \$1, then we will produce 22 more units.
\item
  The Lagrange multiplier is approximately \(22\) units/dollar. We will break even if we can sell one unit for \(1/22=0.045\) dollars/unit. So if the sale price is at least \$0.045, we will decide to increase production.
\end{enumerate}

--\textgreater{}

\hypertarget{unit-5-summary}{%
\chapter{Unit 5 Summary}\label{unit-5-summary}}

\hypertarget{d-optimization-2}{%
\section{1D Optimization}\label{d-optimization-2}}

I can \ldots{}

\begin{itemize}
\tightlist
\item
  Find the local maxima, local minima, global maximum and global minimum for the graph of a function.
\item
  Find the critical points of \(f(x)\) by solving \(f'(x)=0\).
\item
  Use the first derivative test to determine whether a critical point is a local minimum, a local maximum or a point of inflection.
\item
  Use the second derivative test to determine whether a critical point is a local minimum or a local maximum.
\end{itemize}

\hypertarget{d-optimization-3}{%
\section{2D Optimization}\label{d-optimization-3}}

I can \ldots{}

\begin{itemize}
\tightlist
\item
  Find the 2D critical points of \(f(x,y)\) by (simultaneously) solving \(f_x(x,y)=0\) and \(f_y(x,y)=0\).
\item
  Characterize a 2D critical point \((a,b)\) as a local minimimum, local maximum or saddle point by:

  \begin{itemize}
  \tightlist
  \item
    Using the 2D second derivative test at \((a,b)\)
  \item
    Making a contour plot near \((a,b)\)
  \item
    Looking at the values of \(f(a,b)-f(x,y)\) on a small circle around \((a,b)\).
  \end{itemize}
\end{itemize}

\hypertarget{gradient-search-2}{%
\section{Gradient Search}\label{gradient-search-2}}

I can \ldots{}

\begin{itemize}
\tightlist
\item
  Find a local maximum of a 2D function \(f(x,y)\) using gradient search in \emph{RStudio}.
\item
  Find a local minimum of a 2D function \(f(x,y)\) using gradient search in \emph{RStudio}.
\item
  Simulate gradient search using the contour plot of a 2D function to find the trajectory that gradient search follows to reach an extreme point.
\item
  Explain why the extreme point found by gradient search depends upon the starting point that we use.
\end{itemize}

\hypertarget{constrained-optimization-1}{%
\section{Constrained Optimization}\label{constrained-optimization-1}}

I can \ldots{}

\begin{itemize}
\tightlist
\item
  Identify the objective function and the constaint function for a constrained optimization problem.
\item
  Explain why the extreme point for a constrained optimization problem occurs where the constraint contour is tangent to a contour of the objective function.
\item
  Use RStudio to create a contour plot to solve a constrained optimization problem.
\item
  Estimate the value of the Lagrange multiplier \(\lambda\) using a contour plot.
\item
  Interpret the Lagrange multiplier \(\lambda\) as a rate of change.
\end{itemize}

\hypertarget{part-integration}{%
\part{Integration}\label{part-integration}}

\hypertarget{accumulating-change}{%
\chapter{Accumulating Change}\label{accumulating-change}}

\hypertarget{activities-21}{%
\section{Activities}\label{activities-21}}

\hypertarget{growing-bacteria}{%
\subsection{Growing Bacteria}\label{growing-bacteria}}

A bacteria population is growing at a rate given by
\[f(t)=3+0.1t^2 \quad \text{  millions of bacteria per hour}\]

A plot of this growth rate is shown below.

\includegraphics[width=0.5\textwidth,height=\textheight]{images/integrate-intro.png}

We have already estimated the change in population from \(t=0\) to \(t=3\) using intervals of width 1. Find a better estimate of the increase in population by

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Using intervals of width 1/2 and evaluating \(f(t)\) at the \textbf{right endpoint} of each interval.
\item
  Using intervals of width 1/2 and evaluating \(f(t)\) at the \textbf{left endpoint} of each interval.
\end{enumerate}

You can do this by hand, or use Desmos to help out. Decide whether your value is an over-estimate or an under-estimate.

\hypertarget{the-change-in-world-population}{%
\subsection{The Change in World Population}\label{the-change-in-world-population}}

The rate of change of the world's population, in millions of people per year, is in the table below.

\begin{longtable}[]{@{}lllllll@{}}
\toprule
Year & 1950 & 1960 & 1970 & 1980 & 1990 & 2000\tabularnewline
\midrule
\endhead
Rate of Change & 37 & 41 & 78 & 77 & 86 & 79\tabularnewline
\bottomrule
\end{longtable}

Using this information, estimate the \textbf{total change} in the world's population between 1950 and 2000 by using

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  A left endpoint estimate
\item
  A right endpoint estimate
\end{enumerate}

\hypertarget{speed-tests}{%
\subsection{Speed Tests}\label{speed-tests}}

The velocity of a new electric car is measured every two seconds. The data is shown below.

\begin{longtable}[]{@{}llllll@{}}
\toprule
Time (seconds) & 0 & 2 & 4 & 6 & 8\tabularnewline
\midrule
\endhead
Velocity (m/s) & 0 & 8 & 16.7 & 27.3 & 36.2\tabularnewline
\bottomrule
\end{longtable}

Estimate the total distance traveled by this car in the first eight seconds by using

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  A left endpoint estimate
\item
  A right endpoint estimate
\end{enumerate}

\hypertarget{estimating-area-with-rstudio}{%
\subsection{Estimating Area with RStudio}\label{estimating-area-with-rstudio}}

Here is some RStudio code that will estimate the area under the curve \(f(x)=2+4x^2-x^3\) on the interval \(0 \leq x \leq 4\) using a \textbf{right endpoint estimation} on intervals of size \(0.5\).

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{f=}\KeywordTok{makeFun}\NormalTok{(}\DecValTok{2}\OperatorTok{+}\DecValTok{4}\OperatorTok{*}\NormalTok{x}\OperatorTok{^}\DecValTok{2}\OperatorTok{-}\NormalTok{x}\OperatorTok{^}\DecValTok{3}\OperatorTok{~}\NormalTok{x)}
\NormalTok{a=}\DecValTok{0}
\NormalTok{b=}\DecValTok{4}
\NormalTok{base =}\StringTok{ }\FloatTok{0.5}
\NormalTok{points =}\StringTok{ }\KeywordTok{seq}\NormalTok{(}\DataTypeTok{from=}\NormalTok{a}\OperatorTok{+}\NormalTok{base, }\DataTypeTok{to=}\NormalTok{b, }\DataTypeTok{by=}\NormalTok{base)}
\NormalTok{heights =}\StringTok{ }\KeywordTok{f}\NormalTok{(points)}
\NormalTok{areas =}\StringTok{ }\NormalTok{base}\OperatorTok{*}\NormalTok{heights}
\KeywordTok{sum}\NormalTok{(areas)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 29
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Update this code to estimate this area using

  \begin{enumerate}
  \def\labelenumii{\alph{enumii}.}
  \tightlist
  \item
    A \textbf{right endpoint estimation} on intervals of size \(0.1\)
  \item
    A \textbf{right endpoint estimation} on intervals of size \(0.01\)
  \item
    A \textbf{left endpoint estimation} on intervals of size \(0.5\)
  \item
    A \textbf{left endpoint estimation} on intervals of size \(0.01\)
  \item
    A \textbf{left endpoint estimation} on intervals of size \(0.00001\)
  \end{enumerate}
\item
  Make a plot of \(f(x)\) on \([0,4]\). Is is clear whether each of the values about is an over-estimate? an under-estimate? or neither?
\end{enumerate}

It is \textbf{not} clear whether any of these values is an over-estimate or an under-estimate. There is a maximum at \(x=2.75\).

\begin{itemize}
\tightlist
\item
  A left endpoint estimate will be an under-estimate on \([0,2.75]\) and an over-estimate on \([2.75,4]\).
\item
  A right endpoint estimate will be an over-estimate on \([0,2.75]\) and an under-estimate on \([2.75,4]\).
\end{itemize}

So we can't easily tell whether it's an under-estimate or an over-estimate.

--\textgreater{}

\hypertarget{the-definite-integral}{%
\chapter{The Definite Integral}\label{the-definite-integral}}

\hypertarget{introduction}{%
\section{Introduction}\label{introduction}}

Here is some code that approximates the area under \(f(x)=x^2\) on the interval \([a,b]\) using \textbf{right hand endpoints} on 100 subintervals. (How would you change this code to use \textbf{left hand endpoints} instead?)

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{f=}\KeywordTok{makeFun}\NormalTok{(x}\OperatorTok{^}\DecValTok{2} \OperatorTok{~}\StringTok{ }\NormalTok{x)}
\NormalTok{a =}\StringTok{ }\DecValTok{0}
\NormalTok{b =}\StringTok{ }\DecValTok{3}
\NormalTok{num =}\StringTok{ }\DecValTok{100}
\CommentTok{### the approximation of f(x) on interval [a,b]}
\NormalTok{base =}\StringTok{ }\NormalTok{(b}\OperatorTok{-}\NormalTok{a)}\OperatorTok{/}\NormalTok{num}
\NormalTok{points =}\StringTok{ }\KeywordTok{seq}\NormalTok{(}\DataTypeTok{from=}\NormalTok{a}\OperatorTok{+}\NormalTok{base, }\DataTypeTok{to=}\NormalTok{b, }\DataTypeTok{by=}\NormalTok{base)}
\NormalTok{heights =}\StringTok{ }\KeywordTok{f}\NormalTok{(points)}
\NormalTok{areas =}\StringTok{ }\NormalTok{base}\OperatorTok{*}\NormalTok{heights}
\KeywordTok{sum}\NormalTok{(areas)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 9.13545
\end{verbatim}

\hypertarget{activities-22}{%
\section{Activities}\label{activities-22}}

\hypertarget{drive-my-car}{%
\subsection{Drive My Car}\label{drive-my-car}}

A car is driving at a rate of \(v(t)=-t+5\). Here is a plot of the velocity.

\includegraphics{_bookdown_files/math135_handbook_files/figure-latex/unnamed-chunk-133-1.pdf}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Use RStudio to approximate these definite integrals using 1000 subintervals.
\end{enumerate}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\tightlist
\item
  \(\displaystyle{\int_0^5 v(x)dx}\)
\item
  \(\displaystyle{\int_0^8 v(x)dx}\)
\item
  \(\displaystyle{\int_0^{12} v(x)dx}\)
\end{enumerate}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\item
  When does the car \textbf{turn around}?
\item
  When does the car \textbf{return to where it started}?
\end{enumerate}

\hypertarget{accelerate-my-car}{%
\subsection{Accelerate My Car}\label{accelerate-my-car}}

A car is traveling at 55 feet per second at time \(t=0\). The plot below shows the car's \textbf{acceleration} on the interval \([0,18]\).

\begin{center}\includegraphics{_bookdown_files/math135_handbook_files/figure-latex/unnamed-chunk-134-1} \end{center}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Is the velocity increasing or decreasing at \(t=2\)? \(t=15\)?
\item
  What happens when \(t=6\)?
\item
  When else (besides \(t=0\)) is the velocity 55 feet per second?
\item
  When is velocity at a \textbf{global maximum}?
\item
  When is velocity at a \textbf{global minimum}?
\end{enumerate}

\hypertarget{making-cupcakes}{%
\subsection{Making Cupcakes}\label{making-cupcakes}}

The marginal cost of making cupcakes is given by \[K'(q)=\frac{1}{100}q^2+\frac{1}{5}q+1,\]
where \(q\) is in dozens of cupcakes.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Set up a definite integral to calculate \(K(30)-K(0)\), which is the change in costs when we create 30 dozen cupcakes.
\item
  Estimate this definite integral using \emph{RStudio}.
\item
  If our fixed costs are \$1500, what is the \textbf{total cost} to make 30 dozen cupcakes?
\end{enumerate}

\hypertarget{area-between-curves}{%
\subsection{Area Between Curves}\label{area-between-curves}}

Below is a graph of both \(\sin(x)\) and \(\cos(x)\) on the interval \([0,2\pi]\).

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plotFun}\NormalTok{(}\KeywordTok{sin}\NormalTok{(x)}\OperatorTok{~}\NormalTok{x,}\DataTypeTok{xlim=}\KeywordTok{range}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{2}\OperatorTok{*}\NormalTok{pi),}\DataTypeTok{ylim=}\KeywordTok{range}\NormalTok{(}\OperatorTok{-}\FloatTok{1.1}\NormalTok{,}\FloatTok{1.1}\NormalTok{),}\DataTypeTok{xlab=}\StringTok{""}\NormalTok{,}\DataTypeTok{ylab=}\StringTok{""}\NormalTok{)}
\KeywordTok{plotFun}\NormalTok{(}\KeywordTok{cos}\NormalTok{(x)}\OperatorTok{~}\NormalTok{x,}\DataTypeTok{add=}\OtherTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{_bookdown_files/math135_handbook_files/figure-latex/unnamed-chunk-135-1} \end{center}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Write a \textbf{sum of integrals} which represents the \emph{area} enclosed by the two curves.\\
  Hint: \(\sin(x) = \cos(x)\) at \(x=\pi/4\) and \(x=5\pi/4\).
\item
  Use \emph{RStudio} to estimate the area between these two curves.
\end{enumerate}

\hypertarget{rules-of-integration}{%
\chapter{Rules of Integration}\label{rules-of-integration}}

\hypertarget{the-fundamental-theorem-of-calculus}{%
\section{The Fundamental Theorem of Calculus}\label{the-fundamental-theorem-of-calculus}}

\[ \int f'(x) \, dx = f(x) + C\]
and
\[ \int_a^b f'(x) \, dx = f(b)-f(a)\]

\hypertarget{integrals-of-familiar-functions}{%
\section{Integrals of Familiar Functions}\label{integrals-of-familiar-functions}}

\hypertarget{constant-rule-1}{%
\subsection{Constant Rule}\label{constant-rule-1}}

The integral of a constant \(a\) is \(ax+C\).
\[\int a \, dx= ax +C\]

\hypertarget{power-rules}{%
\subsection{Power Rules}\label{power-rules}}

For \(n \neq -1\),
\[\int x^n \, dx= \frac{1}{n+1} x^{n+1} +C\]
and
\[
\int \frac{1}{x} \, dx = \ln (x) + C
\]

\hypertarget{trig-rules-1}{%
\subsection{Trig Rules}\label{trig-rules-1}}

\[\int \sin(x) \, dx = -\cos(x) +C\]
and
\[\int \cos(x) \, dx= \sin(x) + C\]

\hypertarget{exponential-rules-1}{%
\subsection{Exponential Rules}\label{exponential-rules-1}}

\[\int e^x \, dx=e^x +C\]
and for any positive number \(a >0\),
\[\int a^x \, dx =\frac{1}{\ln(a)}a^x + C\]

\hypertarget{logarithmic-rules-1}{%
\subsection{Logarithmic Rules}\label{logarithmic-rules-1}}

\[\int \ln (x) \, dx =x \ln(x) -x + C\]
and for any positive number \(a >0\),
\[\int \log_a (x) \, dx = x \log_a(x) - \frac{1}{\ln (a)} x + C \]

\hypertarget{arithmetic-rules-for-integrals}{%
\section{Arithmetic Rules for Integrals}\label{arithmetic-rules-for-integrals}}

\hypertarget{constant-multiple-rule-1}{%
\subsection{Constant Multiple Rule}\label{constant-multiple-rule-1}}

If \(c\) is a constant, then
\[\int  cf(x) \, dx =c \int f(x) \, dx\]

\hypertarget{sum-and-difference-rules-1}{%
\subsection{Sum and Difference Rules}\label{sum-and-difference-rules-1}}

\[\int (f(x)+g(x)) \,dx= \int f(x) \, dx + \int g(x)\, dx\]
and
\[\int (f(x)-g(x)) \,dx= \int f(x) \, dx - \int g(x)\, dx\]

\hypertarget{substitution-rule}{%
\subsection{Substitution Rule}\label{substitution-rule}}

For any constant \(k\),
\[\int f'(kx) = \frac{1}{k} f(kx) + C\]

\hypertarget{rules-for-endpoints}{%
\section{Rules for Endpoints}\label{rules-for-endpoints}}

\hypertarget{decomposition-rule}{%
\subsection{Decomposition Rule}\label{decomposition-rule}}

For \(a < c < b\), we have
\[ \int_a^b f(x) \, dx = \int_a^c f(x) \, dx + \int_c^b f(x) \, dx\]

\hypertarget{zero-integral-rule}{%
\subsection{Zero Integral Rule}\label{zero-integral-rule}}

\[\int_c^c f(x) dx = 0\]

\hypertarget{the-indefinite-integral}{%
\chapter{The Indefinite Integral}\label{the-indefinite-integral}}

\hypertarget{activities-23}{%
\section{Activities}\label{activities-23}}

\hypertarget{indefinite-integral-practice}{%
\subsection{Indefinite Integral Practice}\label{indefinite-integral-practice}}

Find the indefinite integral.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \(\displaystyle{\int 3x^4\,dx}\)
\item
  \(\displaystyle{\int r^5-\frac{7}{r^3}+r^{3/4}\,dr}\)
\item
  \(\displaystyle{\int 8t^2-t^{13}\,dt}\)
\item
  \(\displaystyle{\int 5e^{4x}\,dx}\)
\item
  \(\displaystyle{\int(x+2)^2\,dx}\)
\item
  \(\displaystyle{\int 4\sqrt{x}-9x+e\,dx}\)
\item
  \(\displaystyle{\int 3^t-7t^4 +\frac{9}{t}\,dt}\)
\item
  \(\displaystyle{\int \cos(x)+2e^x +7\,dx}\)
\item
  \(\displaystyle{\int \sin(3x)-2\cos(x)dx}\)
\item
  \(\displaystyle{\int 7e^{-0.02t}+\frac{4}{t}\,dt}\)
\end{enumerate}

\hypertarget{definite-integral-practice}{%
\subsection{Definite Integral Practice}\label{definite-integral-practice}}

Evaluate the definite integral using antiderivates.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \(\displaystyle{\int_{-2}^5 x^2 \,dx}\)
\item
  \(\displaystyle{\int_0^{\pi/4} \sin(x) + e^{x}\,dx}\)
\item
  \(\displaystyle{\int_1^e 4t + \frac{1}{4t} \,dt}\)
\end{enumerate}

\hypertarget{area-between-curves-1}{%
\subsection{Area Between Curves}\label{area-between-curves-1}}

Find the area enclosed by the curves \(f(x)=5-x^2\) and \(g(x)=x^2-3\) by following the steps below

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Find the points of intersection of \(f(x)\) and \(g(x)\).
\item
  Which curve is above the other?
\item
  Set up the definite integral.
\item
  Evaluate (symbolically or with RStudio)
\end{enumerate}

\hypertarget{average-value}{%
\subsection{Average Value}\label{average-value}}

The average value of a function \(f(x)\) on interval \([a,b]\) is given by
\[ \frac{1}{b-a} \int_a^b f(x) \, dx.\]

Find the average value of function on the given interval.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  The average value of \(\sin(x)\) on \([0, \pi]\).
\item
  The average value of \(e^{2x}\) on \([0,5]\).
\item
  The average value of \(x^2 + 3\) on \([4,6]\)
\end{enumerate}

\hypertarget{modeling-population-growth}{%
\subsection{Modeling Population Growth}\label{modeling-population-growth}}

The second phase of bacteria growth is called the \emph{log phase}. The rate of population growth is proportional to the number of bacteria at that time with proportionality constant 0.003. In other words

\[
\frac{dP}{dt} = 0.003 P
\]

This is equivalent to the integration formula
\[
\int \frac{1}{P} \, dP = \int 0.003 \, dt.
\]

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Integrate both sides of this equation and find a general equation for \(P\).
\item
  Suppose there are 1000 bacteria initially. Find the specific equation for \(P\).
\end{enumerate}

\hypertarget{zombie-apocalypse}{%
\subsection{Zombie Apocalypse}\label{zombie-apocalypse}}

The \textbf{rate} \(r(t)\) at which people become zombies during the inevitable zombie apocalypse can be approximated by
\[ r(t)=1000 e^{-0.5t}\]
where \(t\) is the number of days since the start of the outbreak.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Write the number of infected people \(I(T)\) as an indefinite integral.
\item
  How many total people get infected by time \(T\) where \(T\) is a very large number?
\end{enumerate}

\hypertarget{unit-6-summary}{%
\chapter{Unit 6 Summary}\label{unit-6-summary}}

\hypertarget{accumulating-change-1}{%
\section{Accumulating Change}\label{accumulating-change-1}}

I can \ldots{}

\begin{itemize}
\tightlist
\item
  Estimate the accumulated change of \(f(x)\) using rectangles under the curve of \(y=f(x)\) and

  \begin{itemize}
  \tightlist
  \item
    Using a left endpoint approximation (LEP)
  \item
    Using a right endpoint approximation (REP)
  \end{itemize}
\item
  Evaluate when a LEP or REP approximation is an under-estimate or an over-estimate.
\item
  Estimate the accumulated change for a table of data
\item
  Estimate the accumulated change of \(f(x)\) using RStudio
\end{itemize}

\hypertarget{the-definite-integral-1}{%
\section{The Definite Integral}\label{the-definite-integral-1}}

I can \ldots{}

\begin{itemize}
\tightlist
\item
  Calculate or estimate a definite integral using a sum of signed areas.
\item
  Interpret a definite integral of a rate of change as the total accumulated change.
\item
  Find the change in distance (or displacement) using a velocity versus time graph.
\item
  Find the change in velocity using an acceleration versus time graph.
\item
  Find the total cost by finding the definite integral of a marginal cost function.
\item
  Find the area between two curves.
\end{itemize}

\hypertarget{the-indefinite-integral-1}{%
\section{The Indefinite Integral}\label{the-indefinite-integral-1}}

I can \ldots{}

\begin{itemize}
\tightlist
\item
  Find the antiderivative(s) of our familiar functions.
\item
  Explain why we need ``\(+ C\)'' when finding antiderivatives.
\item
  Use the rules of integration to write a complicated indefinite integral as the sum of multiple indefinite integrals.
\item
  Use substitution to evaluate and integral of the form \(\int f(kx) \, dx\) wherre \(k\) is a constant.
\item
  Calculate the average value of \(f(x)\) on interval \([a,b]\) using the formula
  \[
  \mbox{average value} = \frac{1}{b-a} \int_a^b f(x) \, dx.
  \]
\end{itemize}

\end{document}
