# Symbolic Differentiation


## Activities

### Basic Derivative Practice

Find the derivative for each of the following functions.

1. $W(r) = r^3 + 5r - 12$
1. $f(x) = x^2 - 3\ln x$
1. $P(t) = 4t^2 + 7\sin t$
1. $f(x) = 1/x^2 + 5\sqrt{x} - 7$
1. $s(x) = 2e^{x} + x^2$
1. $h(\theta) = 1/\sqrt[3]{\theta}$
1. $b(t) = t^2 + 5\cos t$


### More Basic Derivative Practice

Find the derivative for each of the following functions.

1. $g(x) = -\frac{1}{2}\left(x^5 +2x -9 \right)$
1. $s(t) = 6t^{-2} + 3t^3 - 4t^{1/2}$
1. $q(x) = 3x - 2\cdot 4^x$
1. $y(x) = \sqrt{x}(x+1)$
1. $P(t) = 3000(1.02)^t$
1. $f(x) = 2^x + x^2 + 1$
1. $d(r) = Ae^{r}  - Br^2 + C$
1. $s(t) = t^2 + 2\ln t$
1. $g(x) = 2x - \frac{1}{\sqrt[3]{x}} + 3^x - e$
1. $y(g) = 5\sin g - 5g + 4$


### Product Rule and Quotient Rule Practice

Find the derivative for each of the following functions.

1. $s(t)=(t^2+4)(5t-1)$
1. $y(x)=x^2\ln x$
1. $g(x)= \frac{25x^2}{e^x}$
1. $y(x)=x^2\cos x$
1. $h(t)=\frac{t+4}{t-4}$














## Solutions

### Basic Derivative Practice

1. $W'(r) = 3r^2 + 5$
1. $f'(x) = 2x - 3/x$
1. $P'(t) = 8t + 7\cos t$
1. $f'(x) = -2x^{-3} + \frac{5}{2}x^{-1/2}$
1. $s'(x) = 2e^{x} + 2x$
1. $h'(\theta) = -\frac{1}{3}\theta^{-4/3}$
1. $b'(t) = 2t - 5\sin t$


### More Basic Derivative Practice 

1. $g'(x) = -\frac{1}{2}(5x^4 + 2)$
1. $s'(t) = -12 t^{-3} + 9t^2 -2t^{-1/2}$
1. $q'(x) = 3 - 2\cdot \ln 4 \cdot 4^x$
1. $y'(x) = \frac{3}{2}x^{1/2} + \frac{1}{2}x^{-1/2}$
1. $P'(t) = 3000\cdot \ln 1.02 \cdot (1.02)^t$
1. $f'(x) = \ln 2 \cdot 2^x + 2x$
1. $d'(r) = Ae^{r} - 2Br$
1. $s'(t) = 2t + 2/t$
1. $g'(x) = 2 + \frac{1}{3}x^{-4/3} + \ln 3 \cdot 3^x$
1. $y'(g) = 5\cos g - 5$



### Product Rule and Quotient Rule Practice


1. $s'(t) = 2t(5t-1) + (t^2+4)5$
1. $y'(x) = 2x\ln x + x^2 \cdot 1/x$
1. $f'(x) = 50xe^{-x} - 25x^2e^{-x}$
1. $y'(x) = 2x\cos x - x^2\sin x$
1. $h'(t) = \frac{(t-4) - (t+4)}{(t-4)^2}$


