# Population Models

## Important Models


Here are the three important differential equations that are also population models.


### Exponential Growth/Decay
The differential equation
$$\displaystyle{\frac{dP}{dt} = r P}$$
has solution
$$\displaystyle{P(t) = C e^{r \, t}}.$$

When $r>0$, we have the exponential growth population model.

When $r < 0$, we have exponential decay. This includes radioactive decay, and the metabolization of a drug in the bloodstream.

### Exponential Growth/Decay with Constant Input/Output
The differential equation
$$\frac{dP}{dt} = r (P-A)$$
is exponential growth/decay with constant input/output.  Its solution is 
$$P(t) = A + C e^{r \, t}.$$ 
When $k >0$ and $H =rA$, we have the population model 
$$
\frac{dP}{dt} = rP-H
$$
for exponential growth at rate $r$ with constant harvesting at rate $H$.

### Constrained Growth
The differential equation
$$\frac{dP}{dt} = r \, P \left(1 - \frac{P}{K}\right)$$ 
has the logistic function as its solution
$$P(t) = \frac{K}{1+ C e^{-r \, t}}.$$
When $r>0$ and $K>0$, we have constrained growth at rate $r$ with carrying capacity $K$.

### Newton's Law of Cooling

Newton's Law of Cooling states that the rate of change of temperature of an object $\frac{dT}{dt}$ is related to the ambient temperature $A$ by the equation:
\[ \frac{dT}{dt}=r(T-A).\]
Note that this is the same differential equation as exponential growth with constant harvesting. 

## Activities


### Drug Metabolization

1. After a drug is administered in a single injection, the rate at which the drug leaves the body is proportional to the quantity $Q$ present.
    a. What differential equation models this process?
    a. Suppose that 10 mg of a drug is injected into the bloodstream. 3 hours later, only 2 mg remains in the bloodstream. Find the formula for the amount of the drug $Q(t)$, in mg, after $t$ hours.

2. Suppose that a drug is being administered at a constant rate of 60 mg/hour and its decreasing at a rate of 20% of the amount present.
    a. What differential equation models this process?
    a. Assuming that $Q(t)=0$, find the formula for the amount of drug $Q(t)$, in mg, after $t$ hours.
    a. What value does $Q(t)$ converge to for large values of $t$?

### Elementary, My Dear Watson

In a mystery novel, the body of a murder victim is found at noon in a room with a constant temperature of $20^\circ C$. At noon, the body is $35^\circ C$ and at 2 pm the body is $33^\circ C$. Normal body temperature is $37^\circ C$. What time did the murder occur?

### Optimal Coffee Temperature

In my $22^\circ C$ office, my coffee starts at $80^\circ C$, but cools to $75^\circ C$ after 10 minutes. If I like my coffee between $63^\circ C$ and $70^\circ C$, how long is my window to drink it?

### Constrained Rabbit Population

The yearly population $P(t)$ of rabbits is modeled by 
$$
\frac{dP}{dt} = 0.45 P  \left(1 - \frac{P}{90} \right).
$$

1. If the current population is $P=120$, will the population increase or decrease?  How do you know?
2. For what values of $P$ is $\frac{dP}{dt}=0$?
3. What value does  $P(t)$ converge to for large values of $t$?


### Constrained Deer Population

The annual population $P(t)$ of deer is modeled by the constrained growth equation
$$
\frac{dP}{dt} = 0.22 P - 0.0275 P^2.
$$

1. What is the growth rate $r$? 
2. What is the carrying capacity $K$?
3. How large is the deer population when that population is growing  at its fastest rate? How fast is the population growing at that time?

## Solutions


### Drug Metabolization

1. This is an exponential decay function.
    a. $\displaystyle={\frac{dQ}{dt} = rQ}$
    a. The solution is expoential decay  $Q(t) = Ce^{rt}$. We have $Q(0) = 10 = C e^{r\cdot 0} = C$. So $Q(t) = 10e^{rt}$, Next we have $Q(3) = 2 = 10 e^{3r}$ so $r = \frac{1}{3} \ln (1/5) = -0.537$. Our final formula is $Q(t) = 10 e^{-0537t}$.

2. Suppose that  a drug is being administered at a constant rate of 60 mg/hour and its decreasing at a rate of 20% of the amount present.
    a. $\displaystyle={\frac{dQ}{dt} = -0.2 Q + 60}$
    a. We need to rewrite the differential equation as $\displaystyle={\frac{dQ}{dt} = -0.2 (Q - 300)}$. The solution is
    $Q(t) = 300 - 300 e^{-0.2t}$.
    a. $Q(t)$ converges to $300$

### Elementary, My Dear Watson

In a mystery novel, the body of a murder victim is found at noon in a room with a constant temperature of $20^\circ C$. At noon, the body is $35^\circ C$ and at 2 pm the body is $33^\circ C$. Normal body temperature is $37^\circ C$. What time did the murder occur?

We use Newton's Law of Cooling $\frac{dT}{dt} = r(T-A)$ where $A=20$. Let's set $t=0$ to be noon. We have $T(0)=35$ and $T(2)=33$.
The initial condition tell us that the solution is $T(t) = 20 + 15e^{rt}$. Next, we have $T(2)  = 33 = 20 + 15e^{2r}$ and so $r = \frac{1}{2} \ln(13/15) = -0.072.$ Our temperature function is $T(t) = 20+15e^{-0.072t}.$

Finally, we solve $37 = 20+15e^{-0.072t}$ which is equivalent to $17/15 = e^{-0.072t}$. Our time of death is $t= -1/(0.072) \ln(17/15) = -1.74$. So the time of death was 10:15 am.

### Optimal Coffee Temperature

In my $22^\circ C$ office, my coffee starts at $80^\circ C$, but cools to $75^\circ C$ after 10 minutes. If I like my coffee between $63^\circ C$ and $70^\circ C$, how long is my window to drink it?

We have $T(t) = 22 + 58 e^{rt}$. Solving $75 = 22 + 58e^{10r}$ gives
$r= \frac{1}{10} \ln (53/58) = -0.009$. The temperature formula is $22 + 68 e^{-0.009 t}$.

Next, we solve $63 = 22 + 58 e^{-0.009 t}$ to find that $t= -1/0.009 \ln(41/58)=38.54$. Finally we solve $70 = 22 + 58 e^{-0.009 t}$ to find that $t= -1/0.009 \ln(48/58)=21.03$. So the coffee is drinkable from minute 21 to minute $38.5$.

### Constrained Rabbit Population

The yearly population $P(t)$ of rabbits is modeled by 
$$
\frac{dP}{dt} = 0.45 P  \left(1 - \frac{P}{90} \right).
$$

1. We have $\frac{dP}{dt} = 0.45 \cdot 120  \left(1 - \frac{120}{90} \right) < 0$. The population will decrease  because the rate of change is negative. 
2. $P'(t)=0$ when $P=0$ and when $P=90$.
3. The carrying capacity is 90.


### Constrained Deer Population

The annual population $P(t)$ of deer is modeled by the constrained growth equation
$$
\frac{dP}{dt} = 0.22 P - 0.0275 P^2.
$$

1. The growth rate is $r=0.23$. 
2. We rewrite the derivative as
$$
\frac{dP}{dt} = 0.22 P\left( 1 - \frac{0.0275}{0.22} P \right) = 0.22 P\left( 1 - \frac{P}{8} \right)
$$
So the carrying capacity is $K=8$.

3. The rate of change is largest when $P=K/2=4$. The rate of change is $0.22 \cdot 4 \cdot \frac{1}{2} =  0.44$.


