

# (PART) Functions {-}

# Functions

## Steps of the Modeling Cycle

1. Ask a question about reality.
2. Make some observations and collect the corresponding data.
3. Conjecture a model or modify a known model based on the data.
4. Test the model against known data (from step 2.) and modify the model as needed.
5. Repeat steps 2, 3 and 4 to improve the model

## Goals

- Explain what a function is
- Identify and explain independent and dependent variables
- Recognize functions in a variety of forms
- Find a function's intercept(s)
- Identify regions where a function is increasing/decreasing
- Compute the average rate of change between two points on a function
- Determine where a function is concave up/down
- Compute the relative change between two points on a function


## Activities

### Life insurance 
A family needs to purchase life insurance. What possible inputs might be used to determine the premium (monthly payment) for life insurance?

### Bat species
In the Andes mountains in Peru, the number $N$ of species of bats is a *function* of the elevation $h$ in feet above sea level.

1. What is the independent variable?
2. What is the dependent variable?
3. Interpret the statement $f(500)=200$ if $f$ represents this function.
4. Do you expect this function to be increasing or decreasing? Why?

### Slope and concavity
Sketch each of the following:

1. An increasing function that is concave up
2. An increasing function that is concave down
3. A decreasing function that is concave up
4. A decreasing function that is concave down

### Relative change of the Dow Jones average 
The *relative change* of a function $f(x)$ on interval $[a,b]$ is
$$ \frac{f(b)-f(a)}{f(a)}.$$

1. What is the *relative change* in the Dow Jones average from 169.84 to 77.90 (from 1 January 1931 to 31 December 1931)? 
2. Compare this to the *relative change* in the Dow Jones average from 35,443.82 to 35,369.09 (from 2 September 2021 to 3 September 2021).

### Measuring rainfall
One rainy summer day, measurements were recorded (in inches) from a rain gauge every hour. 

**Time**   | 8 am | 9 | 10 | 11 | noon | 1 pm | 2 | 3 | 4 | 5 pm
-------|-------|-------|-------|-------|-------|-------|-------|-------|-------|-------
**Amount** | 0.15 | 0.17 | 0.2 | 0.45 | 0.48 | 0.75 | 1.03 | 1.20 | 1.45 | 1.60

1. What was the average rate of rainfall from 8 a.m. to 5 p.m.? 
2. What are the units of this rate of change? 

